var lang_msgs = {
  "msg_id": {
    "type_e-mail": "type_e-mail",
    "type_e-mail_again": "type_e-mail_again",
    "type_e-mail_twice": "type_e-mail_twice",
    "listen_and_fill": "listen_and_fill",
    "match_correct": "match_correct",
    "choose_the_level": "choose_the_level",
    "select_what_you_hear": "select_what_you_hear",
    "select_correct_one": "select_correct_one",
    "learned_these_word": "learned_these_word",
    "span_learn_by_examples": "span_learn_by_examples",
    "Btn_Start_learning": "Btn_Start_learning",
    "btn_continue": "btn_continue",
    "btn_listen_continue": "btn_listen_continue",
    "btn_listen": "btn_listen",
    "btn_hard": "btn_hard",
    "btn_easy": "btn_easy",
    "btn_too_easy": "btn_too_easy",
    "btn_login": "btn_login",
    "Btn_StartA": "Btn_StartA",
    "Btn_logout": "Btn_logout",
    "wordsA": "wordsA",
    "words_to_reviewA": "words_to_reviewA",
    "familiarA": "familiarA",
    "masteredA": "masteredA",
    "progressA": "progressA",
    "pointsA": "pointsA",
    "progress_msg": "progress_msg",
    "wrong_progress_input": "wrong_progress_input",
    "learned_these_words": "learned_these_words",
    "select_wrong_word": "select_wrong_word",
    "Span_start_learn": "Span_start_learn",
  },
  "en-us": {
    "type_e-mail": "Type in your e-mail adress.",
    "type_e-mail_again": "Type in your e-mail adress again.",
    "type_e-mail_twice": "Enter your e-mail twice.",
    "listen_and_fill": "Listen and fill blanks.",
    "match_correct": "Match correct pairs.",
    "choose_the_level": "Choose the level how you feel about this.",
    "select_what_you_hear": "Select what you hear.",
    "select_correct_one": "Select correct one.",
    "learned_these_word": "You have just learned these words.",
    "span_learn_by_examples": "Learn Esperanto by Examples",
    "Btn_Start_learning": "Start Learning",
    "btn_continue": "Continue",
    "btn_listen_continue": "Listen and Continue",
    "btn_listen": "Listen",
    "btn_hard": "Hard for me",
    "btn_easy": "Easy to me",
    "btn_too_easy": "Too easy",
    "btn_login": "Login",
    "Btn_StartA": "Start Learning",
    "Btn_logout": "Logout",
    "wordsA": "Words",
    "words_to_reviewA": "Words to review",
    "familiarA": "Familiar",
    "masteredA": "Mastered",
    "progressA": "Progress",
    "pointsA": "Points",
    "progress_msg": "Current progress is $PROGRESS %. What percent position do you want to jump to? If you want half, enter 50.",
    "wrong_progress_input": "Invalid input! Enter a percentage value between 0 and 100 as an integer.",
    "learned_these_words": "You have just learned these words.",
    "select_wrong_word": "Select a wrong word.",
    "Span_start_learn": "Start Learning",
  },
  "ko-kr": {
    "type_e-mail": "이메일 주소를 입력해 주세요.",
    "type_e-mail_again": "이메일 주소를 한 번 더 입력해 주세요.",
    "type_e-mail_twice": "이메일을 두 번 입력해주세요.",
    "listen_and_fill": "듣고 빈칸을 채우세요.",
    "match_correct": "짝을 맞추세요.",
    "choose_the_level": "이것이 쉽나요? 어렵나요?",
    "select_what_you_hear": "들어보고 선택하세요.",
    "select_correct_one": "맞는 것을 선택하세요.",
    "learned_these_word": "방금 학습하신 목록입니다.",
    "span_learn_by_examples": "예제를 통한 에스페란토 학습",
    "Btn_Start_learning": "학습 시작하기",
    "btn_continue": "다음",
    "btn_listen_continue": "듣고 다음으로",
    "btn_listen": "들어보기",
    "btn_hard": "어려워요",
    "btn_easy": "쉬워요",
    "btn_too_easy": "너무쉬워요",
    "btn_login": "로그인",
    "Btn_StartA": "학습시작",
    "Btn_logout": "로그아웃",
    "wordsA": "전체 항목 수",
    "words_to_reviewA": "복습 필요 항목",
    "familiarA": "익숙해진 항목",
    "masteredA": "마스터한 항목",
    "progressA": "진도율",
    "pointsA": "누적 점수",
    "progress_msg": "지금 진도율이 $PROGRESS %입니다. 몇 퍼센트 위치로 점프하시겠습니까? 만약 절반을 원하시면 50을 입력해주세요.",
    "wrong_progress_input": "입력이 잘못되었습니다! 0-100사이의 퍼센트 값을 정수로 입력하세요.",
    "learned_these_words": "지금 학습하신 단어 목록입니다.",
    "select_wrong_word": "틀린 단어를 선택하세요",
    "Span_start_learn": "학습 시작하기",
  },
  "zh-tw": {
    "type_e-mail": "請輸入電子郵件地址。",
    "type_e-mail_again": "請再輸入一次電子郵件地址。",
    "type_e-mail_twice": "請輸入兩次電子郵件",
    "listen_and_fill": "聽完後填滿空格。",
    "match_correct": "請配對。",
    "choose_the_level": "這容易嗎? 很難嗎？",
    "select_what_you_hear": "請聽後選擇。",
    "select_correct_one": "請選擇正確的。",
    "learned_these_word": "這是您剛學習的清單。",
    "span_learn_by_examples": "透過例題學習世界語",
    "Btn_Start_learning": "開始學習",
    "btn_continue": "下一個",
    "btn_listen_continue": "聽完之後",
    "btn_listen": "聽",
    "btn_hard": "好難",
    "btn_easy": "簡單",
    "btn_too_easy": "很簡單",
    "btn_login": "登入",
    "Btn_StartA": "學習開始",
    "Btn_logout": "註銷",
    "wordsA": "總項目數",
    "words_to_reviewA": "複習項目",
    "familiarA": "熟悉的項目",
    "masteredA": "掌握的項目",
    "progressA": "進度率",
    "pointsA": "累計分數",
    "progress_msg": "當前進度為 $PROGRESS %。 你想跳到百分之幾的位置？ 如果您想要一半，請輸入 50。",
    "wrong_progress_input": "輸入無效！ 輸入 0 到 100 之間的整數百分比值。",
    "learned_these_words": "你剛剛學會了這些單字。",
    "select_wrong_word": "選擇一個錯誤的單字。",
    "Span_start_learn": "開始學習",
  },
  "zh-cn": {
    "type_e-mail": "请输入电子邮件地址。",
    "type_e-mail_again": "请再输入一次电子邮件地址。",
    "type_e-mail_twice": "请输入两次电子邮件",
    "listen_and_fill": "听完后填满空格。",
    "match_correct": "请配对。",
    "choose_the_level": "这容易吗? 很难吗？",
    "select_what_you_hear": "请听后选择。",
    "select_correct_one": "请选择正确的。",
    "learned_these_word": "这是您刚刚学习的列表。",
    "span_learn_by_examples": "通过例题学习世界语",
    "Btn_Start_learning": "开始学习",
    "btn_continue": "下一个",
    "btn_listen_continue": "听完之后",
    "btn_listen": "听",
    "btn_hard": "好难",
    "btn_easy": "简单",
    "btn_too_easy": "很简单",
    "btn_login": "登录",
    "Btn_StartA": "学习开始",
    "Btn_logout": "注销",
    "wordsA": "总项目数",
    "words_to_reviewA": "复习项目",
    "familiarA": "熟悉的项目",
    "masteredA": "掌握的项目",
    "progressA": "进度率",
    "pointsA": "累计分数",
    "progress_msg": "当前进度为 $PROGRESS %。 你想跳到百分之几的位置？ 如果您想要一半，请输入 50。",
    "wrong_progress_input": "输入无效！ 输入 0 到 100 之间的整数百分比值。",
    "learned_these_words": "你刚刚学会了这些词。",
    "select_wrong_word": "选择一个错误的单词。",
    "Span_start_learn": "开始学习",
  },
  "ja-jp": {
    "type_e-mail": "メールアドレスを入力してください。",
    "type_e-mail_again": "メールアドレスをもう一度入力してください。",
    "type_e-mail_twice": "Eメールを二度入力してください。",
    "listen_and_fill": "聞いて空欄を埋めてください。",
    "match_correct": "ペアを組んでください。",
    "choose_the_level": "これが簡単ですか？ 難しいですか？",
    "select_what_you_hear": "聞いてみて選択してください。",
    "select_correct_one": "正しいものを選択してください。",
    "learned_these_word": "先ほど学習したリストです。",
    "span_learn_by_examples": "例題によるエスペラント学習",
    "Btn_Start_learning": "学習を始める",
    "btn_continue": "次",
    "btn_listen_continue": "聞いてから次へ",
    "btn_listen": "聞いてみる",
    "btn_hard": "難しいです",
    "btn_easy": "簡単です",
    "btn_too_easy": "とても簡単です",
    "btn_login": "ログイン",
    "Btn_StartA": "学習開始",
    "Btn_logout": "ログアウト",
    "wordsA": "全項目数",
    "words_to_reviewA": "復習必要項目",
    "familiarA": "慣れた項目",
    "masteredA": "マスターな項目",
    "progressA": "進度率",
    "pointsA": "累積点数",
    "progress_msg": "今進歩率は$PROGRESS％です。 何パーセントの位置にジャンプしますか？ 半分が必要な場合は50を入力してください。",
    "wrong_progress_input": "入力が間違っています！ 0〜100の間のパーセント値を整数で入力してください。",
    "learned_these_words": "今学んだ単語のリストです。",
    "select_wrong_word": "間違った単語を選択してください。",
    "Span_start_learn": "学習を始める",
  },
  "vi-vn": {
    "type_e-mail": "Nhập địa chỉ email của bạn.",
    "type_e-mail_again": "Nhập lại địa chỉ email của bạn.",
    "type_e-mail_twice": "Nhập e-mail của bạn hai lần.",
    "listen_and_fill": "Nghe và điền vào chỗ trống.",
    "match_correct": "Ghép các cặp đúng.",
    "choose_the_level": "Hãy chọn mức độ bạn cảm nhận về điều này.",
    "select_what_you_hear": "Chọn những gì bạn nghe thấy",
    "select_correct_one": "Chọn đúng.",
    "learned_these_word": "Bạn vừa học được những từ này.",
    "span_learn_by_examples": "Học Esperanto qua ví dụ",
    "Btn_Start_learning": "Bắt đầu học",
    "btn_continue": "Tiếp tục",
    "btn_listen_continue": "Nghe và tiếp tục",
    "btn_listen": "Nghe này",
    "btn_hard": "Khó",
    "btn_easy": "Dễ",
    "btn_too_easy": "Quá dễ",
    "btn_login": "Đăng nhập",
    "Btn_StartA": "Bắt đầu học",
    "Btn_logout": "Đăng xuất",
    "wordsA": "Từ",
    "words_to_reviewA": "Những từ cần ôn lại",
    "familiarA": "Quen thuộc",
    "masteredA": "Thành thạo",
    "progressA": "Tiến trình",
    "pointsA": "Điểm",
    "progress_msg": "Tiến độ hiện tại là $PROGRESS %. Bạn muốn nhảy tới vị trí phần trăm nào? Nếu bạn muốn một nửa, hãy nhập 50.",
    "wrong_progress_input": "Đâu vao không hợp lệ! Nhập giá trị phần trăm từ 0 đến 100 dưới dạng số nguyên.",
    "learned_these_words": "Bạn vừa học được những từ này.",
    "select_wrong_word": "Chọn một từ sai.",
    "Span_start_learn": "Bắt đầu học",
  },
  "fr": {
    "type_e-mail": "Saisissez votre adresse e-mail.",
    "type_e-mail_again": "Saisissez à nouveau votre adresse e-mail.",
    "type_e-mail_twice": "Entrez votre e-mail deux fois.",
    "listen_and_fill": "Écoutez et remplissez les vides.",
    "match_correct": "Faites correspondre les bonnes paires.",
    "choose_the_level": "Choisissez le niveau de ce que vous ressentez à ce sujet.",
    "select_what_you_hear": "Sélectionnez ce que vous entendez.",
    "select_correct_one": "Sélectionnez le correct.",
    "learned_these_word": "Vous venez d'apprendre ces mots.",
    "span_learn_by_examples": "Apprendre l'espéranto par des exemples",
    "Btn_Start_learning": "Commencer à apprendre",
    "btn_continue": "Continuer",
    "btn_listen_continue": "Écoutez et continuez",
    "btn_listen": "Écouter",
    "btn_hard": "Difficile pour moi",
    "btn_easy": "Facile pour moi",
    "btn_too_easy": "Trop facile",
    "btn_login": "Se connecter",
    "Btn_StartA": "Commencer à apprendre",
    "Btn_logout": "Se déconnecter",
    "wordsA": "Mots",
    "words_to_reviewA": "Mots à revoir",
    "familiarA": "Familier",
    "masteredA": "Maîtrisé",
    "progressA": "Progrès",
    "pointsA": "Points",
    "progress_msg": "La progression actuelle est de $PROGRESS %. À quel pourcentage de position souhaitez-vous accéder ? Si vous en voulez la moitié, entrez 50.",
    "wrong_progress_input": "Entrée invalide! Entrez une valeur de pourcentage comprise entre 0 et 100 sous forme d'entier.",
    "learned_these_words": "Vous venez d'apprendre ces mots.",
    "select_wrong_word": "Sélectionnez un mauvais mot.",
    "Span_start_learn": "Commencer à apprendre",
  },
  "mn": {
    "type_e-mail": "Имэйл хаягаа оруулна уу.",
    "type_e-mail_again": "Имэйл хаягаа дахин бичнэ үү.",
    "type_e-mail_twice": "Имэйлээ хоёр удаа оруулна уу.",
    "listen_and_fill": "Сонсож, хоосон зайг бөглөнө үү.",
    "match_correct": "Зөв хосуудыг тааруулна уу.",
    "choose_the_level": "Энэ талаар ямар түвшинд байгаагаа сонго.",
    "select_what_you_hear": "Сонссон зүйлээ сонго.",
    "select_correct_one": "Зөвийг сонго.",
    "learned_these_word": "Та эдгээр үгсийг саяхан сурсан.",
    "span_learn_by_examples": "Эсперанто хэлийг жишээгээр сур",
    "Btn_Start_learning": "Сураж эхэл",
    "btn_continue": "Үргэлжлүүлэх",
    "btn_listen_continue": "Сонсож, үргэлжлүүлээрэй",
    "btn_listen": "Сонсооч",
    "btn_hard": "Надад хэцүү",
    "btn_easy": "Надад амархан",
    "btn_too_easy": "Хэт амархан",
    "btn_login": "Нэвтрэх",
    "Btn_StartA": "Сураж эхэл",
    "Btn_logout": "Гарах",
    "wordsA": "Үг",
    "words_to_reviewA": "Шалгах үгс",
    "familiarA": "Танил",
    "masteredA": "Мэргэшсэн",
    "progressA": "Ахиц дэвшил",
    "pointsA": "Оноо",
    "progress_msg": "Одоогийн явц нь $PROGRESS % байна. Та хэдэн хувийн байрлал руу үсрэхийг хүсч байна вэ? Хэрэв та хагасыг хүсвэл 50-г оруулна уу.",
    "wrong_progress_input": "Буруу оролт! 0-ээс 100 хүртэлх хувийн утгыг бүхэл тоогоор оруулна уу.",
    "learned_these_words": "Вы только что выучили эти слова.",
    "select_wrong_word": "Буруу үг сонго.",
    "Span_start_learn": "Сураж эхэл",
  },
  "th": {
    "type_e-mail": "พิมพ์อีเมลของคุณ",
    "type_e-mail_again": "พิมพ์อีเมลของคุณอีกครั้ง",
    "type_e-mail_twice": "กรอกอีเมลของคุณสองครั้ง",
    "listen_and_fill": "ฟังและเติมคำในช่องว่าง",
    "match_correct": "จับคู่ให้ถูกต้อง",
    "choose_the_level": "เลือกระดับความรู้สึกของคุณเกี่ยวกับเรื่องนี้",
    "select_what_you_hear": "เลือกสิ่งที่คุณได้ยิน",
    "select_correct_one": "เลือกข้อความที่ถูกต้อง",
    "learned_these_word": "คุณเพิ่งเรียนรู้คำศัพท์เหล่านี้",
    "span_learn_by_examples": "เรียนรู้คำศัพท์ภาษาเอสเปรันโตจากตัวอย่าง",
    "Btn_Start_learning": "เริ่ม",
    "btn_continue": "ไปต่อ",
    "btn_listen_continue": "ฟังและไปต่อ",
    "btn_listen": "ฟัง",
    "btn_hard": "ยาก",
    "btn_easy": "ง่าย",
    "btn_too_easy": "ง่ายเกินไป",
    "btn_login": "เข้าสู่ระบบ",
    "Btn_StartA": "เริ่ม",
    "Btn_logout": "ออกจากระบบ",
    "wordsA": "คำ",
    "words_to_reviewA": "คำศัพท์ที่ต้องทบทวน",
    "familiarA": "คุ้นเคย",
    "masteredA": "เชี่ยวชาญ",
    "progressA": "ความคืบหน้า",
    "pointsA": "คะแนน",
    "progress_msg": "ความคืบหน้าปัจจุบันคือ $PROGRESS % คุณต้องการข้ามไปยังตำแหน่งกี่เปอร์เซ็นต์? หากต้องการครึ่งหนึ่งให้ป้อน 50",
    "wrong_progress_input": "ข้อมูลไม่ถูกต้อง! ป้อนค่าเปอร์เซ็นต์เป็นจำนวนเต็มระหว่าง 0 ถึง 100",
    "learned_these_words": "คุณเพิ่งเรียนรู้คำศัพท์เหล่านี้",
    "select_wrong_word": "เลือกคำผิด.",
    "Span_start_learn": "เริ่ม",
  },
  "ms": {
    "type_e-mail": "Taipkan alamat e-mel anda.",
    "type_e-mail_again": "Taipkan alamat e-mel anda sekali lagi.",
    "type_e-mail_twice": "Masukkan e-mel anda dua kali.",
    "listen_and_fill": "Dengar dan isi tempat kosong.",
    "match_correct": "Padankan pasangan yang betul.",
    "choose_the_level": "Pilih tahap perasaan anda tentang perkara ini.",
    "select_what_you_hear": "Pilih apa yang anda dengar.",
    "select_correct_one": "Pilih yang betul.",
    "learned_these_word": "Anda baru sahaja mempelajari perkataan ini.",
    "span_learn_by_examples": "Belajar Esperanto dengan Contoh",
    "Btn_Start_learning": "Mula Belajar",
    "btn_continue": "teruskan",
    "btn_listen_continue": "Dengar dan Teruskan",
    "btn_listen": "Dengar",
    "btn_hard": "Sukar untuk saya",
    "btn_easy": "Mudah bagi saya",
    "btn_too_easy": "Terlalu mudah",
    "btn_login": "Log masuk",
    "Btn_StartA": "Mula Belajar",
    "Btn_logout": "Log keluar",
    "wordsA": "Kata-kata",
    "words_to_reviewA": "Kata-kata untuk disemak",
    "familiarA": "Biasa",
    "masteredA": "Menguasai",
    "progressA": "Kemajuan",
    "pointsA": "mata",
    "progress_msg": "Kemajuan semasa ialah $PROGRESS %. Berapa peratus kedudukan yang anda mahu lompat? Kalau nak separuh, masukkan 50.",
    "wrong_progress_input": "Input tidak sah! Masukkan nilai peratusan antara 0 dan 100 sebagai integer.",
    "learned_these_words": "Anda baru sahaja mempelajari perkataan ini.",
    "select_wrong_word": "Pilih perkataan yang salah.",
    "Span_start_learn": "Mula Belajar",
  },
  "id": {
    "type_e-mail": "Masukkan alamat email Anda.",
    "type_e-mail_again": "Masukkan alamat email Anda sekali lagi.",
    "type_e-mail_twice": "Masukkan email Anda dua kali.",
    "listen_and_fill": "Dengarkan dan isilah bagian yang kosong.",
    "match_correct": "Cocokkan pasangan yang benar.",
    "choose_the_level": "Pilih tingkat perasaan Anda tentang hal ini.",
    "select_what_you_hear": "Pilih opsi yang Anda dengar.",
    "select_correct_one": "Pilih opsi yang benar.",
    "learned_these_word": "Anda baru saja mempelajari kata-kata ini.",
    "span_learn_by_examples": "Belajar Esperanto dengan Contoh",
    "Btn_Start_learning": "Mulai Belajar",
    "btn_continue": "Lanjutkan",
    "btn_listen_continue": "Dengarkan dan Lanjutkan",
    "btn_listen": "Dengarkan",
    "btn_hard": "Sulit bagi saya",
    "btn_easy": "Mudah bagi saya",
    "btn_too_easy": "Terlalu mudah",
    "btn_login": "Masuk",
    "Btn_StartA": "Mulai Belajar",
    "Btn_logout": "Keluar",
    "wordsA": "Kata-kata",
    "words_to_reviewA": "Kata-kata untuk dipelajari kembali",
    "familiarA": "Dikenal",
    "masteredA": "Dikuasai",
    "progressA": "Kemajuan",
    "pointsA": "Poin",
    "progress_msg": "Kemajuan saat ini adalah $PROGRESS %. Posisi berapa persen yang ingin Anda capai? Jika Anda ingin posisi setengah, masukkan '50'.",
    "wrong_progress_input": "Input tidak valid! Masukkan nilai persentase antara 0 dan 100 sebagai bilangan bulat.",
    "learned_these_words": "Anda baru saja mempelajari kata-kata ini.",
    "select_wrong_word": "Pilih kata yang salah.",
    "Span_start_learn": "Mulai Belajar",
  },
  "hi": {
    "type_e-mail": "अपना ई-मेल पता टाइप करें.",
    "type_e-mail_again": "अपना ई-मेल पता दोबारा टाइप करें।",
    "type_e-mail_twice": "अपना ई-मेल दो बार दर्ज करें.",
    "listen_and_fill": "सुनें और रिक्त स्थान भरें.",
    "match_correct": "सही जोड़े मिलाएँ.",
    "choose_the_level": "आप इसके बारे में कैसा महसूस करते हैं, इसका स्तर चुनें।",
    "select_what_you_hear": "आप जो सुनते हैं उसे चुनें.",
    "select_correct_one": "सही का चयन करें.",
    "learned_these_word": "आपने अभी-अभी ये शब्द सीखे हैं।",
    "span_learn_by_examples": "उदाहरणों द्वारा एस्पेरान्तो सीखें",
    "Btn_Start_learning": "सीखना शुरू करें",
    "btn_continue": "जारी रखना",
    "btn_listen_continue": "सुनें और जारी रखें",
    "btn_listen": "सुनना",
    "btn_hard": "मेरे लिए मुश्किल",
    "btn_easy": "मेरे लिए आसान है",
    "btn_too_easy": "बहुत आसान",
    "btn_login": "लॉग इन करें",
    "Btn_StartA": "सीखना शुरू करें",
    "Btn_logout": "लॉग आउट",
    "wordsA": "शब्द",
    "words_to_reviewA": "समीक्षा के लिए शब्द",
    "familiarA": "परिचित",
    "masteredA": "महारत हासिल",
    "progressA": "प्रगति",
    "pointsA": "अंक",
    "progress_msg": "वर्तमान प्रगति $PROGRESS% है। आप किस प्रतिशत स्थान पर पहुंचना चाहते हैं? यदि आप आधा चाहते हैं, तो 50 दर्ज करें।",
    "wrong_progress_input": "अमान्य निवेश! पूर्णांक के रूप में 0 और 100 के बीच प्रतिशत मान दर्ज करें।",
    "learned_these_words": "आपने अभी-अभी ये शब्द सीखे हैं।",
    "select_wrong_word": "ग़लत शब्द चुनें.",
    "Span_start_learn": "सीखना शुरू करें",
  },
  "fa": {
    "type_e-mail": "آدرس ایمیل خود را تایپ کنید",
    "type_e-mail_again": "آدرس ایمیل خود را دوباره وارد کنید.",
    "type_e-mail_twice": "ایمیل خود را دو بار وارد کنید.",
    "listen_and_fill": "گوش کنید و جاهای خالی را پر کنید.",
    "match_correct": "جفت های صحیح را مطابقت دهید",
    "choose_the_level": "سطح احساسی که در این مورد دارید را انتخاب کنید.",
    "select_what_you_hear": "آنچه می شنوید را انتخاب کنید.",
    "select_correct_one": "صحیح را انتخاب کنید",
    "learned_these_word": "شما تازه این کلمات را یاد گرفتید.",
    "span_learn_by_examples": "اسپرانتو را با مثال بیاموزید",
    "Btn_Start_learning": "شروع به یادگیری",
    "btn_continue": "ادامه هید",
    "btn_listen_continue": "گوش کن و ادامه بده",
    "btn_listen": "گوش بده",
    "btn_hard": "برای من سخت است",
    "btn_easy": "برای من آسان است",
    "btn_too_easy": "بیش از حد آسان",
    "btn_login": "وارد شدن",
    "Btn_StartA": "شروع به یادگیری",
    "Btn_logout": "خروج",
    "wordsA": "کلمات",
    "words_to_reviewA": "کلمات برای بررسی",
    "familiarA": "آشنا",
    "masteredA": "مسلط شد",
    "progressA": "پیش رفتن",
    "pointsA": "نکته ها",
    "progress_msg": "پیشرفت فعلی $PROGRESS ٪ است. به چند درصد می خواهید بپرید؟ اگر نصف می خواهید 50 وارد کنید.",
    "wrong_progress_input": "ورودی نامعتبر! مقدار درصدی بین 0 تا 100 را به عنوان یک عدد صحیح وارد کنید.",
    "learned_these_words": "شما تازه این کلمات را یاد گرفتید.",
    "select_wrong_word": "یک کلمه اشتباه انتخاب کنید",
    "Span_start_learn": "شروع به یادگیری",
  },
  "ne": {
    "type_e-mail": "आफ्नो इमेल ठेगाना टाइप गर्नुहोस्।",
    "type_e-mail_again": "आफ्नो इमेल ठेगाना फेरि टाइप गर्नुहोस्।",
    "type_e-mail_twice": "आफ्नो इमेल दुई पटक प्रविष्ट गर्नुहोस्।",
    "listen_and_fill": "सुन्नुहोस् र खाली ठाउँहरू भर्नुहोस्।",
    "match_correct": "सही जोडी मिलाउनुहोस्।",
    "choose_the_level": "तपाईं यस बारे कस्तो महसुस गर्नुहुन्छ स्तर छान्नुहोस्।",
    "select_what_you_hear": "तपाईंले सुन्नु भएको कुरा चयन गर्नुहोस्।",
    "select_correct_one": "सही एक छान्नुहोस्।",
    "learned_these_word": "तपाईंले भर्खर यी शब्दहरू सिक्नुभयो।",
    "span_learn_by_examples": "उदाहरणहरूद्वारा एस्पेरान्तो सिक्नुहोस्",
    "Btn_Start_learning": "सिक्न सुरु गर्नुहोस्",
    "btn_continue": "जारी राख्नुहोस्",
    "btn_listen_continue": "सुन्नुहोस् र जारी राख्नुहोस्",
    "btn_listen": "सुन्नुहोस्",
    "btn_hard": "मेरो लागि गाह्रो",
    "btn_easy": "मलाई सजिलो",
    "btn_too_easy": "एकदम सजिलो",
    "btn_login": "लग - इन",
    "Btn_StartA": "सिक्न सुरु गर्नुहोस्",
    "Btn_logout": "बाहिर निस्कनु",
    "wordsA": "शब्दहरू",
    "words_to_reviewA": "समीक्षा गर्न शब्दहरू",
    "familiarA": "परिचित",
    "masteredA": "निपुण",
    "progressA": "प्रगति",
    "pointsA": "अंक",
    "progress_msg": "हालको प्रगति $PROGRESS % हो। तपाई कुन प्रतिशत स्थानमा उफ्रन चाहनुहुन्छ? यदि तपाईं आधा चाहनुहुन्छ भने, 50 प्रविष्ट गर्नुहोस्।",
    "wrong_progress_input": "अवैध इनपुट! पूर्णांकको रूपमा ० र १०० बीचको प्रतिशत मान प्रविष्ट गर्नुहोस्।",
    "learned_these_words": "तपाईंले भर्खर यी शब्दहरू सिक्नुभयो।",
    "select_wrong_word": "गलत शब्द चयन गर्नुहोस्।",
    "Span_start_learn": "सिक्न सुरु गर्नुहोस्",
  },
  "ur": {
    "type_e-mail": "اپنا ای میل ایڈریس ٹائپ کریں۔",
    "type_e-mail_again": "اپنا ای میل ایڈریس دوبارہ ٹائپ کریں۔",
    "type_e-mail_twice": "اپنا ای میل دو بار درج کریں۔",
    "listen_and_fill": "سنیں اور خالی جگہ پر کریں۔",
    "match_correct": "صحیح جوڑوں کو جوڑیں۔",
    "choose_the_level": "اس سطح کا انتخاب کریں کہ آپ اس کے بارے میں کیسا محسوس کرتے ہیں۔",
    "select_what_you_hear": "آپ جو سنتے ہیں اسے منتخب کریں۔",
    "select_correct_one": "صحیح ایک کو منتخب کریں۔",
    "learned_these_word": "آپ نے یہ الفاظ ابھی سیکھے ہیں۔",
    "span_learn_by_examples": "مثالوں سے ایسپرانٹو سیکھیں۔",
    "Btn_Start_learning": "سیکھنا شروع کریں۔",
    "btn_continue": "جاری رہے",
    "btn_listen_continue": "سنیں اور جاری رکھیں",
    "btn_listen": "سنو",
    "btn_hard": "میرے لیے مشکل",
    "btn_easy": "میرے لیے آسان",
    "btn_too_easy": "بہت آسان",
    "btn_login": "لاگ ان کریں",
    "Btn_StartA": "سیکھنا شروع کریں۔",
    "Btn_logout": "لاگ آوٹ",
    "wordsA": "الفاظ",
    "words_to_reviewA": "جائزہ لینے کے لیے الفاظ",
    "familiarA": "مانوس",
    "masteredA": "مہارت حاصل کی۔",
    "progressA": "پیش رفت",
    "pointsA": "پوائنٹس",
    "progress_msg": "موجودہ پیش رفت $PROGRESS % ہے۔ آپ کس فیصد پوزیشن پر جانا چاہتے ہیں؟ اگر آپ آدھا چاہتے ہیں تو 50 درج کریں۔",
    "wrong_progress_input": "غلط ان پٹ! بطور عدد 0 اور 100 کے درمیان فیصد کی قدر درج کریں۔",
    "learned_these_words": "آپ نے یہ الفاظ ابھی سیکھے ہیں۔",
    "select_wrong_word": "غلط لفظ منتخب کریں۔",
    "Span_start_learn": "سیکھنا شروع کریں۔",
  },
  "tr": {
    "type_e-mail": "E-posta adresinizi yazın.",
    "type_e-mail_again": "E-posta adresinizi tekrar yazın.",
    "type_e-mail_twice": "E-postanızı iki kez girin.",
    "listen_and_fill": "Dinleyin ve boşlukları doldurun.",
    "match_correct": "Doğru çiftleri eşleştirin.",
    "choose_the_level": "Bu konuda ne hissettiğinizi seviyeyi seçin.",
    "select_what_you_hear": "Ne duyduğunuzu seçin.",
    "select_correct_one": "Doğru olanı seçin.",
    "learned_these_word": "Bu kelimeleri yeni öğrendiniz.",
    "span_learn_by_examples": "Örneklerle Esperanto Öğrenin",
    "Btn_Start_learning": "Öğrenmeye başla",
    "btn_continue": "Devam etmek",
    "btn_listen_continue": "Dinle ve Devam Et",
    "btn_listen": "Dinlemek",
    "btn_hard": "Benim için zor",
    "btn_easy": "Benim için kolay",
    "btn_too_easy": "Çok kolay",
    "btn_login": "Giriş yapmak",
    "Btn_StartA": "Öğrenmeye başla",
    "Btn_logout": "Çıkış Yap",
    "wordsA": "Kelimeler",
    "words_to_reviewA": "İncelenecek kelimeler",
    "familiarA": "Aşina",
    "masteredA": "Ustalaşmış",
    "progressA": "İlerlemek",
    "pointsA": "Puanlar",
    "progress_msg": "Şu anki ilerleme %$PROGRESS. Yüzde kaç pozisyona atlamak istiyorsunuz? Yarısını istiyorsanız 50 girin.",
    "wrong_progress_input": "Geçersiz Giriş! Tam sayı olarak 0 ile 100 arasında bir yüzde değeri girin.",
    "learned_these_words": "Bu kelimeleri yeni öğrendiniz.",
    "select_wrong_word": "Yanlış bir kelime seçin.",
    "Span_start_learn": "Öğrenmeye başla",
  },
  "he": {
    "type_e-mail": "הקלד את כתובת הדואר האלקטרוני שלך.",
    "type_e-mail_again": "הקלד שוב את כתובת הדואר האלקטרוני שלך.",
    "type_e-mail_twice": "הכנס את המייל שלך פעמיים.",
    "listen_and_fill": "הקשיבו והשלימו מקומות ריקים.",
    "match_correct": "התאם זוגות נכונים.",
    "choose_the_level": "בחר את הרמה איך אתה מרגיש לגבי זה.",
    "select_what_you_hear": "בחר את מה שאתה שומע.",
    "select_correct_one": "בחר אחד נכון.",
    "learned_these_word": "זה עתה למדת את המילים הללו.",
    "span_learn_by_examples": "למד אספרנטו לפי דוגמאות",
    "Btn_Start_learning": "תתחיל ללמוד",
    "btn_continue": "לְהַמשִׁיך",
    "btn_listen_continue": "הקשב והמשך",
    "btn_listen": "להקשיב",
    "btn_hard": "קשה לי",
    "btn_easy": "קל לי",
    "btn_too_easy": "קל מדי",
    "btn_login": "התחברות",
    "Btn_StartA": "תתחיל ללמוד",
    "Btn_logout": "להתנתק",
    "wordsA": "מילים",
    "words_to_reviewA": "מילים לביקורת",
    "familiarA": "מוּכָּר",
    "masteredA": "מאסטר",
    "progressA": "התקדמות",
    "pointsA": "נקודות",
    "progress_msg": "ההתקדמות הנוכחית היא $PROGRESS %. לאיזה אחוז עמדה אתה רוצה לקפוץ? אם אתה רוצה חצי, הזן 50.",
    "wrong_progress_input": "קלט לא תקין! הזן ערך אחוז בין 0 ל-100 כמספר שלם.",
    "learned_these_words": "זה עתה למדת את המילים הללו.",
    "select_wrong_word": "בחר מילה שגויה.",
    "Span_start_learn": "תתחיל ללמוד",
  },
  "ar": {
    "type_e-mail": "اكتب عنوان البريد الإلكتروني الخاص بك.",
    "type_e-mail_again": "اكتب عنوان البريد الإلكتروني الخاص بك مرة أخرى.",
    "type_e-mail_twice": "أدخل بريدك الإلكتروني مرتين.",
    "listen_and_fill": "استمع واملأ الفراغات.",
    "match_correct": "تطابق الأزواج الصحيحة.",
    "choose_the_level": "اختر المستوى الذي تشعر به حيال ذلك.",
    "select_what_you_hear": "حدد ما تسمعه.",
    "select_correct_one": "اختر واحدة صحيحة.",
    "learned_these_word": "لقد تعلمت للتو هذه الكلمات.",
    "span_learn_by_examples": "تعلم الاسبرانتو بالأمثلة",
    "Btn_Start_learning": "ابدا بالتعلم",
    "btn_continue": "يكمل",
    "btn_listen_continue": "الاستماع والمتابعة",
    "btn_listen": "يستمع",
    "btn_hard": "صعب علي",
    "btn_easy": "سهل بالنسبة لي",
    "btn_too_easy": "سهل جدا",
    "btn_login": "تسجيل الدخول",
    "Btn_StartA": "ابدا بالتعلم",
    "Btn_logout": "تسجيل خروج",
    "wordsA": "كلمات",
    "words_to_reviewA": "كلمات للمراجعة",
    "familiarA": "مألوف",
    "masteredA": "يتقن",
    "progressA": "تقدم",
    "pointsA": "نقاط",
    "progress_msg": "التقدم الحالي هو $PROGRESS %. ما هو موضع النسبة المئوية الذي تريد الانتقال إليه؟ إذا كنت تريد النصف، أدخل 50.",
    "wrong_progress_input": "مدخل غير صالح! أدخل قيمة النسبة المئوية بين 0 و100 كعدد صحيح.",
    "learned_these_words": "لقد تعلمت للتو هذه الكلمات.",
    "select_wrong_word": "اختر كلمة خاطئة.",
    "Span_start_learn": "ابدا بالتعلم",
  },
  "de": {
    "type_e-mail": "Geben Sie Ihre E-Mail-Adresse ein.",
    "type_e-mail_again": "Geben Sie Ihre E-Mail-Adresse erneut ein.",
    "type_e-mail_twice": "Geben Sie Ihre E-Mail-Adresse zweimal ein.",
    "listen_and_fill": "Hören Sie zu und füllen Sie Lücken aus.",
    "match_correct": "Ordnen Sie die richtigen Paare zu.",
    "choose_the_level": "Wählen Sie die Ebene, auf der Sie dazu stehen.",
    "select_what_you_hear": "Wählen Sie aus, was Sie hören.",
    "select_correct_one": "Wählen Sie die richtige aus.",
    "learned_these_word": "Sie haben gerade diese Wörter gelernt.",
    "span_learn_by_examples": "Lernen Sie Esperanto anhand von Beispielen",
    "Btn_Start_learning": "Beginne zu lernen",
    "btn_continue": "Weitermachen",
    "btn_listen_continue": "Hören Sie zu und fahren Sie fort",
    "btn_listen": "Hören",
    "btn_hard": "Schwer für mich",
    "btn_easy": "Für mich einfach",
    "btn_too_easy": "Zu einfach",
    "btn_login": "Anmeldung",
    "Btn_StartA": "Beginne zu lernen",
    "Btn_logout": "Ausloggen",
    "wordsA": "Wörter",
    "words_to_reviewA": "Wörter zur Überprüfung",
    "familiarA": "Vertraut",
    "masteredA": "Gemeistert",
    "progressA": "Fortschritt",
    "pointsA": "Punkte",
    "progress_msg": "Der aktuelle Fortschritt beträgt $PROGRESS %. Zu welcher Prozentposition möchten Sie springen? Wenn Sie die Hälfte möchten, geben Sie 50 ein.",
    "wrong_progress_input": "Ungültige Eingabe! Geben Sie einen Prozentwert zwischen 0 und 100 als Ganzzahl ein.",
    "learned_these_words": "Sie haben gerade diese Wörter gelernt.",
    "select_wrong_word": "Wählen Sie ein falsches Wort.",
    "Span_start_learn": "Beginne zu lernen",
  },
  "es": {
    "type_e-mail": "Escriba su dirección de correo electrónico.",
    "type_e-mail_again": "Escriba su dirección de correo electrónico nuevamente.",
    "type_e-mail_twice": "Ingrese su correo electrónico dos veces.",
    "listen_and_fill": "Escuche y complete los espacios en blanco.",
    "match_correct": "Une los pares correctos.",
    "choose_the_level": "Elige el nivel de cómo te sientes al respecto.",
    "select_what_you_hear": "Selecciona lo que escuchas.",
    "select_correct_one": "Seleccione el correcto.",
    "learned_these_word": "Acabas de aprender estas palabras.",
    "span_learn_by_examples": "Aprende esperanto con ejemplos",
    "Btn_Start_learning": "Comienza a aprender",
    "btn_continue": "Continuar",
    "btn_listen_continue": "Escuche y continúe",
    "btn_listen": "Escuchar",
    "btn_hard": "Es difícil para mí",
    "btn_easy": "fácil para mi",
    "btn_too_easy": "Demasiado fácil",
    "btn_login": "Acceso",
    "Btn_StartA": "Comienza a aprender",
    "Btn_logout": "Cerrar sesión",
    "wordsA": "Palabras",
    "words_to_reviewA": "Palabras para repasar",
    "familiarA": "Familiar",
    "masteredA": "dominado",
    "progressA": "Progreso",
    "pointsA": "Puntos",
    "progress_msg": "El progreso actual es $PROGRESS %. ¿A qué posición porcentual quieres saltar? Si quieres la mitad, ingresa 50.",
    "wrong_progress_input": "¡Entrada inválida! Introduzca un valor porcentual entre 0 y 100 como un número entero.",
    "learned_these_words": "Acabas de aprender estas palabras.",
    "select_wrong_word": "Seleccione una palabra incorrecta.",
    "Span_start_learn": "Comienza a aprender",
  },
  "it": {
    "type_e-mail": "Inserisci il tuo indirizzo email.",
    "type_e-mail_again": "Inserisci nuovamente il tuo indirizzo email.",
    "type_e-mail_twice": "Inserisci due volte la tua email.",
    "listen_and_fill": "Ascolta e riempi gli spazi vuoti.",
    "match_correct": "Abbina le coppie corrette.",
    "choose_the_level": "Scegli il livello in cui ti senti a riguardo.",
    "select_what_you_hear": "Seleziona ciò che senti.",
    "select_correct_one": "Seleziona quello corretto.",
    "learned_these_word": "Hai appena imparato queste parole.",
    "span_learn_by_examples": "Impara l'esperanto con esempi",
    "Btn_Start_learning": "Inizia a imparare",
    "btn_continue": "Continua",
    "btn_listen_continue": "Ascolta e continua",
    "btn_listen": "Ascoltare",
    "btn_hard": "Difficile per me",
    "btn_easy": "Facile per me",
    "btn_too_easy": "Troppo facile",
    "btn_login": "Login",
    "Btn_StartA": "Inizia a imparare",
    "Btn_logout": "Disconnettersi",
    "wordsA": "Parole",
    "words_to_reviewA": "Parole da rivedere",
    "familiarA": "Familiare",
    "masteredA": "Masterizzato",
    "progressA": "Progresso",
    "pointsA": "Punti",
    "progress_msg": "Il progresso attuale è $PROGRESS%. A quale posizione percentuale vuoi saltare? Se ne vuoi la metà, inserisci 50.",
    "wrong_progress_input": "Inserimento non valido! Immettere un valore percentuale compreso tra 0 e 100 come numero intero.",
    "learned_these_words": "Hai appena imparato queste parole.",
    "select_wrong_word": "Seleziona una parola sbagliata.",
    "Span_start_learn": "Inizia a imparare",
  },
  "pt": {
    "type_e-mail": "Digite seu endereço de e-mail.",
    "type_e-mail_again": "Digite seu endereço de e-mail novamente.",
    "type_e-mail_twice": "Digite seu e-mail duas vezes.",
    "listen_and_fill": "Ouça e preencha os espaços em branco.",
    "match_correct": "Combine os pares corretos.",
    "choose_the_level": "Escolha o nível como você se sente sobre isso.",
    "select_what_you_hear": "Selecione o que você ouve.",
    "select_correct_one": "Selecione o correto.",
    "learned_these_word": "Você acabou de aprender estas palavras.",
    "span_learn_by_examples": "Aprenda esperanto com exemplos",
    "Btn_Start_learning": "Comece a aprender",
    "btn_continue": "Continuar",
    "btn_listen_continue": "Ouça e continue",
    "btn_listen": "Ouvir",
    "btn_hard": "Difícil para mim",
    "btn_easy": "Fácil para mim",
    "btn_too_easy": "Muito fácil",
    "btn_login": "Conecte-se",
    "Btn_StartA": "Comece a aprender",
    "Btn_logout": "Sair",
    "wordsA": "Palavras",
    "words_to_reviewA": "Palavras para revisar",
    "familiarA": "Familiar",
    "masteredA": "Dominado",
    "progressA": "Progresso",
    "pointsA": "Pontos",
    "progress_msg": "O progresso atual é de $PROGRESS%. Para qual posição percentual você deseja pular? Se você quiser metade, digite 50.",
    "wrong_progress_input": "Entrada inválida! Insira um valor percentual entre 0 e 100 como um número inteiro.",
    "learned_these_words": "Você acabou de aprender estas palavras.",
    "select_wrong_word": "Selecione uma palavra errada.",
    "Span_start_learn": "Comece a aprender",
  },
  "ru": {
    "type_e-mail": "Введите свой адрес электронной почты.",
    "type_e-mail_again": "Введите свой адрес электронной почты еще раз.",
    "type_e-mail_twice": "Введите свой адрес электронной почты дважды.",
    "listen_and_fill": "Прослушайте и заполните пропуски.",
    "match_correct": "Сопоставьте правильные пары.",
    "choose_the_level": "Выберите уровень, как вы к этому относитесь.",
    "select_what_you_hear": "Выберите то, что вы слышите.",
    "select_correct_one": "Выберите правильный.",
    "learned_these_word": "Вы только что выучили эти слова.",
    "span_learn_by_examples": "Изучайте эсперанто на примерах",
    "Btn_Start_learning": "Начать обучение",
    "btn_continue": "Продолжать",
    "btn_listen_continue": "Слушайте и продолжайте",
    "btn_listen": "Слушать",
    "btn_hard": "Тяжело для меня",
    "btn_easy": "Мне легко",
    "btn_too_easy": "Слишком легко",
    "btn_login": "Авторизоваться",
    "Btn_StartA": "Начать обучение",
    "Btn_logout": "Выйти",
    "wordsA": "Слова",
    "words_to_reviewA": "Слова для рассмотрения",
    "familiarA": "Привычный",
    "masteredA": "Освоен",
    "progressA": "Прогресс",
    "pointsA": "Точки",
    "progress_msg": "Текущий прогресс составляет $PROGRESS %. На какую процентную позицию вы хотите перейти? Если хотите половину, введите 50.",
    "wrong_progress_input": "Неверный Ввод! Введите процентное значение от 0 до 100 в виде целого числа.",
    "learned_these_words": "Вы только что выучили эти слова.",
    "select_wrong_word": "Выберите неправильное слово.",
    "Span_start_learn": "Начать обучение",
  },
  "pl": {
    "type_e-mail": "Wpisz swój adres e-mail.",
    "type_e-mail_again": "Wpisz ponownie swój adres e-mail.",
    "type_e-mail_twice": "Wpisz dwukrotnie swój adres e-mail.",
    "listen_and_fill": "Posłuchaj i uzupełnij puste miejsca.",
    "match_correct": "Dopasuj odpowiednie pary.",
    "choose_the_level": "Wybierz poziom, co o tym myślisz.",
    "select_what_you_hear": "Wybierz to, co słyszysz.",
    "select_correct_one": "Wybierz właściwy.",
    "learned_these_word": "Właśnie nauczyłeś się tych słów.",
    "span_learn_by_examples": "Ucz się esperanta na przykładach",
    "Btn_Start_learning": "Zacząć naukę",
    "btn_continue": "Kontynuować",
    "btn_listen_continue": "Posłuchaj i kontynuuj",
    "btn_listen": "Słuchać",
    "btn_hard": "Dla mnie trudne",
    "btn_easy": "Dla mnie łatwe",
    "btn_too_easy": "Zbyt łatwe",
    "btn_login": "Zaloguj sie",
    "Btn_StartA": "Zacząć naukę",
    "Btn_logout": "Wyloguj",
    "wordsA": "Słowa",
    "words_to_reviewA": "Słowa do sprawdzenia",
    "familiarA": "Znajomy",
    "masteredA": "Opanowany",
    "progressA": "Postęp",
    "pointsA": "Zwrotnica",
    "progress_msg": "Obecny postęp to $PROGRESS%. Na jaką pozycję procentową chcesz przeskoczyć? Jeśli chcesz połowę, wpisz 50.",
    "wrong_progress_input": "Nieprawidłowe dane wejściowe! Wprowadź wartość procentową z zakresu od 0 do 100 jako liczbę całkowitą.",
    "learned_these_words": "Właśnie nauczyłeś się tych słów.",
    "select_wrong_word": "Wybierz niewłaściwe słowo.",
    "Span_start_learn": "Zacząć naukę",
  },
  "km": {
    "type_e-mail": "វាយបញ្ចូលអាសយដ្ឋានអ៊ីមែលរបស់អ្នក",
    "type_e-mail_again": "វាយបញ្ចូលអាសយដ្ឋានអ៊ីមែលរបស់អ្នកម្តងទៀត",
    "type_e-mail_twice": "បញ្ចូលអ៊ីមែលរបស់អ្នកពីរដង",
    "listen_and_fill": "ស្តាប់ហើយបំពេញចន្លោះ",
    "match_correct": "ផ្គូផ្គងគូត្រឹមត្រូវ",
    "choose_the_level": "ជ្រើសរើសកម្រិតដែលអ្នកមានអារម្មណ៍ចំពោះបញ្ហានេះ។",
    "select_what_you_hear": "ជ្រើសរើសអ្វីដែលអ្នកឮ",
    "select_correct_one": "ជ្រើសរើសត្រឹមត្រូវ",
    "learned_these_word": "អ្នកទើបតែបានរៀនពាក្យទាំងនេះ",
    "span_learn_by_examples": "រៀនភាសា Esperanto ដោយឧទាហរណ៍",
    "Btn_Start_learning": "ចាប់ផ្តើមរៀន",
    "btn_continue": "បន្ត",
    "btn_listen_continue": "ស្តាប់ហើយបន្ត",
    "btn_listen": "ស្តាប់",
    "btn_hard": "ពិបាកសម្រាប់ខ្ញុំ",
    "btn_easy": "ងាយស្រួលសម្រាប់ខ្ញុំ",
    "btn_too_easy": "ងាយស្រួល​មែនទែន",
    "btn_login": "ចូល",
    "Btn_StartA": "ចាប់ផ្តើមរៀន",
    "Btn_logout": "ចាកចេញ",
    "wordsA": "ពាក្យ",
    "words_to_reviewA": "ពាក្យដើម្បីពិនិត្យឡើងវិញ",
    "familiarA": "ធ្លាប់ស្គាល់",
    "masteredA": "ស្ទាត់ជំនាញ",
    "progressA": "វឌ្ឍនភាព",
    "pointsA": "ពិន្ទុ",
    "progress_msg": "វឌ្ឍនភាពបច្ចុប្បន្នគឺ PROGRESS  តើអ្នកចង់លោតទៅទីតាំងប៉ុន្មានភាគរយ? ប្រសិនបើអ្នកចង់បានពាក់កណ្តាលសូមបញ្ចូល 50 ។",
    "wrong_progress_input": "ការបញ្ចូលមិនត្រឹមត្រូវ",
    "learned_these_words": "អ្នកទើបតែបានរៀនពាក្យទាំងនេះ",
    "select_wrong_word": "ជ្រើសរើសពាក្យខុស។",
    "Span_start_learn": "ចាប់ផ្តើមរៀន",
  },
  "my": {
    "type_e-mail": "သင့်အီးမေးလ်လိပ်စာကို ရိုက်ထည့်ပါ။",
    "type_e-mail_again": "သင့်အီးမေးလ်လိပ်စာကို ထပ်မံရိုက်ထည့်ပါ။",
    "type_e-mail_twice": "သင့်အီးမေးလ်ကို နှစ်ကြိမ်ထည့်ပါ။",
    "listen_and_fill": "နားထောင်ပြီး ကွက်လပ်ဖြည့်ပါ။",
    "match_correct": "မှန်ကန်သောအတွဲများ",
    "choose_the_level": "ယင်းအပေါ် သင်မည်ကဲ့သို့ ခံစားရသည့် အဆင့်ကို ရွေးချယ်ပါ။",
    "select_what_you_hear": "သင်ကြားသောအရာကို ရွေးပါ။",
    "select_correct_one": "မှန်ကန်သောတစ်ခုကို ရွေးပါ။",
    "learned_these_word": "ဒီစကားလုံးတွေကို မင်းအခုမှပဲ သင်ယူပြီးပြီ။",
    "span_learn_by_examples": "ဥပမာများဖြင့် Esperanto ကို လေ့လာပါ။",
    "Btn_Start_learning": "စတင်လေ့လာပါ။",
    "btn_continue": "ဆက်လက်",
    "btn_listen_continue": "နားထောင်ပြီး ဆက်လုပ်ပါ။",
    "btn_listen": "နားထောင်ပါ။",
    "btn_hard": "ငါ့အတွက်ခက်တယ်။",
    "btn_easy": "လွယ်လိုက်တာ",
    "btn_too_easy": "လွယ်လွန်းတယ်။",
    "btn_login": "လော့ဂ်အင်",
    "Btn_StartA": "စတင်လေ့လာပါ။",
    "Btn_logout": "ထွက်လိုက်ပါ။",
    "wordsA": "စကား",
    "words_to_reviewA": "သုံးသပ်ရန်စကားလုံးများ",
    "familiarA": "ရင်းနှီးသည်။",
    "masteredA": "ကျွမ်းကျင်တယ်။",
    "progressA": "တိုးတက်မှု",
    "pointsA": "အမှတ်များ",
    "progress_msg": "လက်ရှိတိုးတက်မှုသည် $PROGRESS % ဖြစ်သည်။ ဘယ်ရာခိုင်နှုန်း ရာထူးကို တက်ချင်လဲ။ တစ်ဝက်လိုချင်ရင် 50 ကိုထည့်ပါ။",
    "wrong_progress_input": "ထည့်သွင်းမှု မမှန်ပါ။ ကိန်းပြည့်အဖြစ် 0 နှင့် 100 ကြား ရာခိုင်နှုန်းတန်ဖိုးကို ထည့်ပါ။",
    "learned_these_words": "ဒီစကားလုံးတွေကို မင်းအခုမှပဲ သင်ယူပြီးပြီ။",
    "select_wrong_word": "မှားသောစကားလုံးကို ရွေးပါ။",
    "Span_start_learn": "စတင်လေ့လာပါ။",
  },
  "bn": {
    "type_e-mail": "আপনার ই-মেইল ঠিকানা টাইপ করুন.",
    "type_e-mail_again": "আপনার ই-মেইল ঠিকানা আবার টাইপ করুন.",
    "type_e-mail_twice": "আপনার ই-মেইল দুবার লিখুন।",
    "listen_and_fill": "শুনুন এবং শূন্যস্থান পূরণ করুন।",
    "match_correct": "সঠিক জোড়া মেলে।",
    "choose_the_level": "আপনি এটি সম্পর্কে কেমন অনুভব করেন তা চয়ন করুন।",
    "select_what_you_hear": "আপনি যা শুনছেন তা নির্বাচন করুন।",
    "select_correct_one": "সঠিক একটি নির্বাচন করুন.",
    "learned_these_word": "আপনি এই শব্দ শিখেছি.",
    "span_learn_by_examples": "উদাহরণ দিয়ে এস্পেরান্তো শিখুন",
    "Btn_Start_learning": "শেখা শুরু করো",
    "btn_continue": "চালিয়ে যান",
    "btn_listen_continue": "শুনুন এবং চালিয়ে যান",
    "btn_listen": "শুনুন",
    "btn_hard": "আমার জন্য কঠিন",
    "btn_easy": "আমার কাছে সহজ",
    "btn_too_easy": "খুব সহজ",
    "btn_login": "প্রবেশ করুন",
    "Btn_StartA": "শেখা শুরু করো",
    "Btn_logout": "প্রস্থান",
    "wordsA": "শব্দ",
    "words_to_reviewA": "পর্যালোচনা শব্দ",
    "familiarA": "পরিচিত",
    "masteredA": "আয়ত্ত করেছে",
    "progressA": "অগ্রগতি",
    "pointsA": "পয়েন্ট",
    "progress_msg": "বর্তমান অগ্রগতি হল $PROGRESS %৷ আপনি কোন শতাংশ অবস্থানে লাফ দিতে চান? আপনি যদি অর্ধেক চান, 50 লিখুন।",
    "wrong_progress_input": "অবৈধ ইনপুট! একটি পূর্ণসংখ্যা হিসাবে 0 এবং 100 এর মধ্যে একটি শতাংশ মান লিখুন।",
    "learned_these_words": "আপনি এই শব্দ শিখেছি.",
    "select_wrong_word": "একটি ভুল শব্দ নির্বাচন করুন।",
    "Span_start_learn": "শেখা শুরু করো",
  },
  "ta": {
    "type_e-mail": "உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும்.",
    "type_e-mail_again": "உங்கள் மின்னஞ்சல் முகவரியை மீண்டும் தட்டச்சு செய்யவும்.",
    "type_e-mail_twice": "உங்கள் மின்னஞ்சலை இருமுறை உள்ளிடவும்.",
    "listen_and_fill": "கேட்டு வெற்றிடங்களை நிரப்பவும்.",
    "match_correct": "சரியான ஜோடிகளைப் பொருத்தவும்.",
    "choose_the_level": "இதைப் பற்றி நீங்கள் எப்படி உணருகிறீர்கள் என்பதைத் தேர்ந்தெடுக்கவும்.",
    "select_what_you_hear": "நீங்கள் கேட்பதைத் தேர்ந்தெடுக்கவும்.",
    "select_correct_one": "சரியான ஒன்றைத் தேர்ந்தெடுக்கவும்.",
    "learned_these_word": "இந்த வார்த்தைகளை நீங்கள் கற்றுக்கொண்டீர்கள்.",
    "span_learn_by_examples": "எஸ்பெராண்டோவை எடுத்துக்காட்டுகள் மூலம் கற்றுக்கொள்ளுங்கள்",
    "Btn_Start_learning": "கற்றலைத் தொடங்குங்கள்",
    "btn_continue": "தொடரவும்",
    "btn_listen_continue": "கேட்டு தொடரவும்",
    "btn_listen": "கேள்",
    "btn_hard": "எனக்கு கடினமானது",
    "btn_easy": "எனக்கு எளிதானது",
    "btn_too_easy": "மிக சுலபம்",
    "btn_login": "உள்நுழைய",
    "Btn_StartA": "கற்றலைத் தொடங்குங்கள்",
    "Btn_logout": "வெளியேறு",
    "wordsA": "சொற்கள்",
    "words_to_reviewA": "மதிப்பாய்வு செய்ய வார்த்தைகள்",
    "familiarA": "தெரிந்தவர்",
    "masteredA": "தேர்ச்சி பெற்றவர்",
    "progressA": "முன்னேற்றம்",
    "pointsA": "புள்ளிகள்",
    "progress_msg": "தற்போதைய முன்னேற்றம் $PROGRESS %. நீங்கள் எந்த சதவீத நிலைக்கு செல்ல விரும்புகிறீர்கள்? பாதி வேண்டுமென்றால் 50ஐ உள்ளிடவும்.",
    "wrong_progress_input": "தவறான உள்ளீடு! 0 மற்றும் 100க்கு இடைப்பட்ட சதவீத மதிப்பை முழு எண்ணாக உள்ளிடவும்.",
    "learned_these_words": "இந்த வார்த்தைகளை நீங்கள் கற்றுக்கொண்டீர்கள்.",
    "select_wrong_word": "தவறான வார்த்தையைத் தேர்ந்தெடுக்கவும்.",
    "Span_start_learn": "கற்றலைத் தொடங்குங்கள்",
  },
  "pa": {
    "type_e-mail": "ਆਪਣਾ ਈ-ਮੇਲ ਪਤਾ ਟਾਈਪ ਕਰੋ।",
    "type_e-mail_again": "ਆਪਣਾ ਈ-ਮੇਲ ਪਤਾ ਦੁਬਾਰਾ ਟਾਈਪ ਕਰੋ।",
    "type_e-mail_twice": "ਆਪਣੀ ਈ-ਮੇਲ ਦੋ ਵਾਰ ਦਾਖਲ ਕਰੋ।",
    "listen_and_fill": "ਸੁਣੋ ਅਤੇ ਖਾਲੀ ਥਾਂ ਭਰੋ।",
    "match_correct": "ਸਹੀ ਜੋੜਿਆਂ ਦਾ ਮੇਲ ਕਰੋ।",
    "choose_the_level": "ਪੱਧਰ ਚੁਣੋ ਕਿ ਤੁਸੀਂ ਇਸ ਬਾਰੇ ਕਿਵੇਂ ਮਹਿਸੂਸ ਕਰਦੇ ਹੋ।",
    "select_what_you_hear": "ਜੋ ਤੁਸੀਂ ਸੁਣਦੇ ਹੋ ਉਸਨੂੰ ਚੁਣੋ।",
    "select_correct_one": "ਇੱਕ ਸਹੀ ਚੁਣੋ।",
    "learned_these_word": "ਤੁਸੀਂ ਇਹ ਸ਼ਬਦ ਹੁਣੇ ਹੀ ਸਿੱਖੇ ਹਨ।",
    "span_learn_by_examples": "ਉਦਾਹਰਨਾਂ ਦੁਆਰਾ ਐਸਪੇਰਾਂਟੋ ਸਿੱਖੋ",
    "Btn_Start_learning": "ਸਿੱਖਣਾ ਸ਼ੁਰੂ ਕਰੋ",
    "btn_continue": "ਜਾਰੀ ਰੱਖੋ",
    "btn_listen_continue": "ਸੁਣੋ ਅਤੇ ਜਾਰੀ ਰੱਖੋ",
    "btn_listen": "ਸੁਣੋ",
    "btn_hard": "ਮੇਰੇ ਲਈ ਔਖਾ",
    "btn_easy": "ਮੇਰੇ ਲਈ ਆਸਾਨ",
    "btn_too_easy": "ਬਹੁਤ ਆਸਾਨ",
    "btn_login": "ਲਾਗਿਨ",
    "Btn_StartA": "ਸਿੱਖਣਾ ਸ਼ੁਰੂ ਕਰੋ",
    "Btn_logout": "ਲਾੱਗ ਆਊਟ, ਬਾਹਰ ਆਉਣਾ",
    "wordsA": "ਸ਼ਬਦ",
    "words_to_reviewA": "ਸਮੀਖਿਆ ਕਰਨ ਲਈ ਸ਼ਬਦ",
    "familiarA": "ਜਾਣੂ",
    "masteredA": "ਮੁਹਾਰਤ ਹਾਸਲ ਕੀਤੀ",
    "progressA": "ਤਰੱਕੀ",
    "pointsA": "ਅੰਕ",
    "progress_msg": "ਮੌਜੂਦਾ ਪ੍ਰਗਤੀ $PROGRESS % ਹੈ। ਤੁਸੀਂ ਕਿਸ ਪ੍ਰਤੀਸ਼ਤ ਸਥਿਤੀ 'ਤੇ ਜਾਣਾ ਚਾਹੁੰਦੇ ਹੋ? ਜੇ ਤੁਸੀਂ ਅੱਧਾ ਚਾਹੁੰਦੇ ਹੋ, ਤਾਂ 50 ਦਰਜ ਕਰੋ।",
    "wrong_progress_input": "ਅਵੈਧ ਇਨਪੁਟ! ਇੱਕ ਪੂਰਨ ਅੰਕ ਵਜੋਂ 0 ਅਤੇ 100 ਦੇ ਵਿਚਕਾਰ ਇੱਕ ਪ੍ਰਤੀਸ਼ਤ ਮੁੱਲ ਦਾਖਲ ਕਰੋ।",
    "learned_these_words": "ਤੁਸੀਂ ਇਹ ਸ਼ਬਦ ਹੁਣੇ ਹੀ ਸਿੱਖੇ ਹਨ।",
    "select_wrong_word": "ਇੱਕ ਗਲਤ ਸ਼ਬਦ ਚੁਣੋ।",
    "Span_start_learn": "ਸਿੱਖਣਾ ਸ਼ੁਰੂ ਕਰੋ",
  },
  "mr": {
    "type_e-mail": "तुमचा ई-मेल पत्ता टाइप करा.",
    "type_e-mail_again": "तुमचा ई-मेल पत्ता पुन्हा टाइप करा.",
    "type_e-mail_twice": "तुमचा ई-मेल दोनदा एंटर करा.",
    "listen_and_fill": "ऐका आणि रिक्त जागा भरा.",
    "match_correct": "योग्य जोड्या जुळवा.",
    "choose_the_level": "तुम्हाला याबद्दल कसे वाटते ते स्तर निवडा.",
    "select_what_you_hear": "तुम्ही जे ऐकता ते निवडा.",
    "select_correct_one": "योग्य एक निवडा.",
    "learned_these_word": "तुम्ही हे शब्द नुकतेच शिकलात.",
    "span_learn_by_examples": "उदाहरणांद्वारे एस्पेरांतो शिका",
    "Btn_Start_learning": "शिकणे सुरू करा",
    "btn_continue": "सुरू",
    "btn_listen_continue": "ऐका आणि सुरू ठेवा",
    "btn_listen": "ऐका",
    "btn_hard": "माझ्यासाठी कठीण",
    "btn_easy": "माझ्यासाठी सोपे",
    "btn_too_easy": "खूप सोपे",
    "btn_login": "लॉगिन करा",
    "Btn_StartA": "शिकणे सुरू करा",
    "Btn_logout": "बाहेर पडणे",
    "wordsA": "शब्द",
    "words_to_reviewA": "पुनरावलोकन करण्यासाठी शब्द",
    "familiarA": "परिचित",
    "masteredA": "मास्टर्ड",
    "progressA": "प्रगती",
    "pointsA": "गुण",
    "progress_msg": "सध्याची प्रगती $PROGRESS % आहे. तुम्हाला कोणत्या टक्के स्थानावर जायचे आहे? तुम्हाला अर्धा हवा असल्यास, 50 प्रविष्ट करा.",
    "wrong_progress_input": "अवैध इनपुट! पूर्णांक म्हणून 0 आणि 100 मधील टक्केवारी मूल्य प्रविष्ट करा.",
    "learned_these_words": "तुम्ही हे शब्द नुकतेच शिकलात.",
    "select_wrong_word": "चुकीचा शब्द निवडा.",
    "Span_start_learn": "शिकणे सुरू करा",
  },
  "te": {
    "type_e-mail": "మీ ఇ-మెయిల్ చిరునామాను టైప్ చేయండి.",
    "type_e-mail_again": "మీ ఇమెయిల్ చిరునామాను మళ్లీ టైప్ చేయండి.",
    "type_e-mail_twice": "మీ ఇమెయిల్‌ను రెండుసార్లు నమోదు చేయండి.",
    "listen_and_fill": "వినండి మరియు ఖాళీలను పూరించండి.",
    "match_correct": "సరైన జతలను సరిపోల్చండి.",
    "choose_the_level": "దీని గురించి మీరు ఎలా భావిస్తున్నారో స్థాయిని ఎంచుకోండి.",
    "select_what_you_hear": "మీరు విన్నదాన్ని ఎంచుకోండి.",
    "select_correct_one": "సరైనదాన్ని ఎంచుకోండి.",
    "learned_these_word": "మీరు ఇప్పుడే ఈ పదాలు నేర్చుకున్నారు.",
    "span_learn_by_examples": "ఉదాహరణల ద్వారా ఎస్పరాంటో నేర్చుకోండి",
    "Btn_Start_learning": "నేర్చుకోవడం ప్రారంభించండి",
    "btn_continue": "కొనసాగించు",
    "btn_listen_continue": "వినండి మరియు కొనసాగించండి",
    "btn_listen": "వినండి",
    "btn_hard": "నాకు కష్టం",
    "btn_easy": "నాకు తేలిక",
    "btn_too_easy": "చాలా సులభం",
    "btn_login": "ప్రవేశించండి",
    "Btn_StartA": "నేర్చుకోవడం ప్రారంభించండి",
    "Btn_logout": "లాగ్అవుట్",
    "wordsA": "పదాలు",
    "words_to_reviewA": "సమీక్షించడానికి పదాలు",
    "familiarA": "తెలిసిన",
    "masteredA": "పట్టు సాధించారు",
    "progressA": "పురోగతి",
    "pointsA": "పాయింట్లు",
    "progress_msg": "ప్రస్తుత పురోగతి $PROGRESS %. మీరు ఏ శాతం స్థానానికి వెళ్లాలనుకుంటున్నారు? మీకు సగం కావాలంటే, 50ని నమోదు చేయండి.",
    "wrong_progress_input": "ఇన్‌పుట్ చెల్లదు! 0 మరియు 100 మధ్య ఉన్న శాతం విలువను పూర్ణాంకంగా నమోదు చేయండి.",
    "learned_these_words": "మీరు ఈ పదాలను ఇప్పుడే నేర్చుకున్నారు.",
    "select_wrong_word": "తప్పు పదాన్ని ఎంచుకోండి.",
    "Span_start_learn": "నేర్చుకోవడం ప్రారంభించండి",
  },
  "uk": {
    "type_e-mail": "Введіть свою електронну адресу.",
    "type_e-mail_again": "Введіть свою електронну адресу ще раз.",
    "type_e-mail_twice": "Введіть свій e-mail двічі.",
    "listen_and_fill": "Послухайте та заповніть пропуски.",
    "match_correct": "З’єднайте правильні пари.",
    "choose_the_level": "Виберіть рівень, як ви ставитеся до цього.",
    "select_what_you_hear": "Виберіть те, що ви чуєте.",
    "select_correct_one": "Виберіть правильний.",
    "learned_these_word": "Ви щойно вивчили ці слова.",
    "span_learn_by_examples": "Вивчайте есперанто на прикладах",
    "Btn_Start_learning": "Почніть навчання",
    "btn_continue": "Продовжити",
    "btn_listen_continue": "Слухайте і продовжуйте",
    "btn_listen": "Слухай",
    "btn_hard": "Важко для мене",
    "btn_easy": "Мені легко",
    "btn_too_easy": "Занадто просто",
    "btn_login": "Логін",
    "Btn_StartA": "Почніть навчання",
    "Btn_logout": "Вийти",
    "wordsA": "Слова",
    "words_to_reviewA": "Слова для перегляду",
    "familiarA": "Знайомий",
    "masteredA": "Опанував",
    "progressA": "Прогрес",
    "pointsA": "Очки",
    "progress_msg": "Поточний прогрес становить $PROGRESS %. На яку відсоткову позицію ви хочете перейти? Якщо ви хочете половину, введіть 50.",
    "wrong_progress_input": "Неправильні дані! Введіть відсоткове значення від 0 до 100 як ціле число.",
    "learned_these_words": "Ви щойно вивчили ці слова.",
    "select_wrong_word": "Виберіть неправильне слово.",
    "Span_start_learn": "Почніть навчання",
  },
  "sv": {
    "type_e-mail": "Skriv in din e-postadress.",
    "type_e-mail_again": "Skriv in din e-postadress igen.",
    "type_e-mail_twice": "Ange din e-post två gånger.",
    "listen_and_fill": "Lyssna och fyll tomrum.",
    "match_correct": "Matcha rätt par.",
    "choose_the_level": "Välj vilken nivå du tycker om detta.",
    "select_what_you_hear": "Välj det du hör.",
    "select_correct_one": "Välj rätt.",
    "learned_these_word": "Du har precis lärt dig dessa ord.",
    "span_learn_by_examples": "Lär dig esperanto genom exempel",
    "Btn_Start_learning": "Börja lära sig",
    "btn_continue": "Fortsätta",
    "btn_listen_continue": "Lyssna och fortsätt",
    "btn_listen": "Lyssna",
    "btn_hard": "Svårt för mig",
    "btn_easy": "Lätt för mig",
    "btn_too_easy": "Alltför lätt",
    "btn_login": "Logga in",
    "Btn_StartA": "Börja lära sig",
    "Btn_logout": "Logga ut",
    "wordsA": "Ord",
    "words_to_reviewA": "Ord att recensera",
    "familiarA": "Bekant",
    "masteredA": "Bemästrade",
    "progressA": "Framsteg",
    "pointsA": "Poäng",
    "progress_msg": "Aktuella framsteg är $PROGRESS %. Vilken procentposition vill du hoppa till? Om du vill ha hälften, ange 50.",
    "wrong_progress_input": "Felaktig input! Ange ett procentvärde mellan 0 och 100 som ett heltal.",
    "learned_these_words": "Du har precis lärt dig dessa ord.",
    "select_wrong_word": "Välj ett fel ord.",
    "Span_start_learn": "Börja lära sig",
  },
  "sw": {
    "type_e-mail": "Andika anwani yako ya barua pepe.",
    "type_e-mail_again": "Andika anwani yako ya barua pepe tena.",
    "type_e-mail_twice": "Ingiza barua pepe yako mara mbili.",
    "listen_and_fill": "Sikiliza na ujaze nafasi zilizoachwa wazi.",
    "match_correct": "Linganisha jozi sahihi.",
    "choose_the_level": "Chagua kiwango jinsi unavyohisi kuhusu hili.",
    "select_what_you_hear": "Chagua unachosikia.",
    "select_correct_one": "Chagua moja sahihi.",
    "learned_these_word": "Umejifunza maneno haya.",
    "span_learn_by_examples": "Jifunze Kiesperanto kwa Mifano",
    "Btn_Start_learning": "Anza Kujifunza",
    "btn_continue": "Endelea",
    "btn_listen_continue": "Sikiliza na Uendelee",
    "btn_listen": "Sikiliza",
    "btn_hard": "Ngumu kwangu",
    "btn_easy": "Rahisi kwangu",
    "btn_too_easy": "Rahisi sana",
    "btn_login": "Ingia",
    "Btn_StartA": "Anza Kujifunza",
    "Btn_logout": "Ondoka",
    "wordsA": "Maneno",
    "words_to_reviewA": "Maneno ya kukagua",
    "familiarA": "Inajulikana",
    "masteredA": "Mwenye ujuzi",
    "progressA": "Maendeleo",
    "pointsA": "Pointi",
    "progress_msg": "Maendeleo ya sasa ni $PROGRESS %. Unataka kuruka kwa asilimia ngapi? Ikiwa unataka nusu, ingiza 50.",
    "wrong_progress_input": "Ingizo batili! Weka thamani ya asilimia kati ya 0 na 100 kama nambari kamili.",
    "learned_these_words": "Umejifunza maneno haya.",
    "select_wrong_word": "Chagua neno lisilo sahihi.",
    "Span_start_learn": "Anza Kujifunza",
  },
  "nl": {
    "type_e-mail": "Voer uw e-mailadres in.",
    "type_e-mail_again": "Vul nogmaals uw e-mailadres in.",
    "type_e-mail_twice": "Voer uw e-mailadres twee keer in.",
    "listen_and_fill": "Luister en vul lege plekken in.",
    "match_correct": "Match de juiste paren.",
    "choose_the_level": "Kies op het niveau hoe jij je hierover voelt.",
    "select_what_you_hear": "Selecteer wat je hoort.",
    "select_correct_one": "Selecteer de juiste.",
    "learned_these_word": "Je hebt zojuist deze woorden geleerd.",
    "span_learn_by_examples": "Leer Esperanto aan de hand van voorbeelden",
    "Btn_Start_learning": "Begin met leren",
    "btn_continue": "Doorgaan",
    "btn_listen_continue": "Luister en ga door",
    "btn_listen": "Luisteren",
    "btn_hard": "Moeilijk voor mij",
    "btn_easy": "Makkelijk voor mij",
    "btn_too_easy": "Te makkelijk",
    "btn_login": "Log in",
    "Btn_StartA": "Begin met leren",
    "Btn_logout": "Uitloggen",
    "wordsA": "Woorden",
    "words_to_reviewA": "Woorden om te beoordelen",
    "familiarA": "Bekend",
    "masteredA": "Onder de knie",
    "progressA": "Voortgang",
    "pointsA": "Punten",
    "progress_msg": "De huidige voortgang is $PROGRESS %. Naar welk percentage positie wilt u springen? Als u de helft wilt, vult u 50 in.",
    "wrong_progress_input": "Ongeldige invoer! Voer een percentagewaarde tussen 0 en 100 in als geheel getal.",
    "learned_these_words": "Je hebt zojuist deze woorden geleerd.",
    "select_wrong_word": "Selecteer een verkeerd woord.",
    "Span_start_learn": "Begin met leren",
  },
  "no": {
    "type_e-mail": "Skriv inn e-postadressen din.",
    "type_e-mail_again": "Skriv inn e-postadressen din på nytt.",
    "type_e-mail_twice": "Skriv inn e-posten din to ganger.",
    "listen_and_fill": "Lytt og fyll ut tomrom.",
    "match_correct": "Match riktige par.",
    "choose_the_level": "Velg nivået hvordan du føler om dette.",
    "select_what_you_hear": "Velg det du hører.",
    "select_correct_one": "Velg riktig.",
    "learned_these_word": "Du har nettopp lært disse ordene.",
    "span_learn_by_examples": "Lær esperanto med eksempler",
    "Btn_Start_learning": "Begynn å lære",
    "btn_continue": "Fortsette",
    "btn_listen_continue": "Lytt og fortsett",
    "btn_listen": "Lytte",
    "btn_hard": "Vanskelig for meg",
    "btn_easy": "Lett for meg",
    "btn_too_easy": "For enkelt",
    "btn_login": "Logg Inn",
    "Btn_StartA": "Begynn å lære",
    "Btn_logout": "Logg ut",
    "wordsA": "Ord",
    "words_to_reviewA": "Ord å anmelde",
    "familiarA": "Velkjent",
    "masteredA": "Mestret",
    "progressA": "Framgang",
    "pointsA": "Poeng",
    "progress_msg": "Nåværende fremgang er $PROGRESS %. Hvilken prosentposisjon vil du hoppe til? Hvis du vil ha halvparten, skriv inn 50.",
    "wrong_progress_input": "Ugyldig inndata! Angi en prosentverdi mellom 0 og 100 som et heltall.",
    "learned_these_words": "Du har nettopp lært disse ordene.",
    "select_wrong_word": "Velg et feil ord.",
    "Span_start_learn": "Begynn å lære",
  },
  "da": {
    "type_e-mail": "Indtast din e-mail-adresse.",
    "type_e-mail_again": "Indtast din e-mail-adresse igen.",
    "type_e-mail_twice": "Indtast din e-mail to gange.",
    "listen_and_fill": "Lyt og udfyld tomrum.",
    "match_correct": "Match rigtige par.",
    "choose_the_level": "Vælg det niveau, hvordan du har det med dette.",
    "select_what_you_hear": "Vælg det, du hører.",
    "select_correct_one": "Vælg den rigtige.",
    "learned_these_word": "Du har lige lært disse ord.",
    "span_learn_by_examples": "Lær esperanto ved eksempler",
    "Btn_Start_learning": "Begynd at lære",
    "btn_continue": "Blive ved",
    "btn_listen_continue": "Lyt og fortsæt",
    "btn_listen": "Hør efter",
    "btn_hard": "Svært for mig",
    "btn_easy": "Nemt for mig",
    "btn_too_easy": "For nemt",
    "btn_login": "Log på",
    "Btn_StartA": "Begynd at lære",
    "Btn_logout": "Log ud",
    "wordsA": "Ord",
    "words_to_reviewA": "Ord at anmelde",
    "familiarA": "Velkendt",
    "masteredA": "Mestret",
    "progressA": "Fremskridt",
    "pointsA": "Points",
    "progress_msg": "Aktuel fremgang er $PROGRESS %. Hvilken procentstilling vil du springe til? Hvis du vil have halvdelen, skal du indtaste 50.",
    "wrong_progress_input": "Ugyldigt input! Indtast en procentværdi mellem 0 og 100 som et heltal.",
    "learned_these_words": "Du har lige lært disse ord.",
    "select_wrong_word": "Vælg et forkert ord.",
    "Span_start_learn": "Begynd at lære",
  },
  "lv": {
    "type_e-mail": "Ierakstiet savu e-pasta adresi.",
    "type_e-mail_again": "Vēlreiz ierakstiet savu e-pasta adresi.",
    "type_e-mail_twice": "Divreiz ievadiet savu e-pastu.",
    "listen_and_fill": "Klausieties un aizpildiet tukšās vietas.",
    "match_correct": "Saskaņojiet pareizos pārus.",
    "choose_the_level": "Izvēlieties līmeni, kā jūs jūtaties šajā jautājumā.",
    "select_what_you_hear": "Izvēlieties to, ko dzirdat.",
    "select_correct_one": "Izvēlieties pareizo.",
    "learned_these_word": "Jūs tikko esat iemācījušies šos vārdus.",
    "span_learn_by_examples": "Mācieties esperanto pēc piemēriem",
    "Btn_Start_learning": "Sāciet mācīties",
    "btn_continue": "Turpināt",
    "btn_listen_continue": "Klausieties un turpiniet",
    "btn_listen": "Klausies",
    "btn_hard": "Grūti man",
    "btn_easy": "Man viegli",
    "btn_too_easy": "Pārāk viegli",
    "btn_login": "Pieslēgties",
    "Btn_StartA": "Sāciet mācīties",
    "Btn_logout": "Izlogoties",
    "wordsA": "Vārdi",
    "words_to_reviewA": "Pārskatāmie vārdi",
    "familiarA": "Pazīstams",
    "masteredA": "Apgūts",
    "progressA": "Progress",
    "pointsA": "Punkti",
    "progress_msg": "Pašreizējais progress ir $ PROGRESS %. Uz kādu procentu pozīciju vēlaties pāriet? Ja vēlaties pusi, ievadiet 50.",
    "wrong_progress_input": "Nepareiza ievade! Ievadiet procentuālo vērtību no 0 līdz 100 kā veselu skaitli.",
    "learned_these_words": "Jūs tikko esat iemācījušies šos vārdus.",
    "select_wrong_word": "Izvēlieties nepareizu vārdu.",
    "Span_start_learn": "Sāciet mācīties",
  },
  "ro": {
    "type_e-mail": "Introdu adresa ta de e-mail.",
    "type_e-mail_again": "Introduceți din nou adresa dvs. de e-mail.",
    "type_e-mail_twice": "Introduceți e-mailul dvs. de două ori.",
    "listen_and_fill": "Ascultă și completează spațiile libere.",
    "match_correct": "Potriviți perechile corecte.",
    "choose_the_level": "Alegeți nivelul cum vă simțiți despre asta.",
    "select_what_you_hear": "Selectați ceea ce auziți.",
    "select_correct_one": "Selectați unul corect.",
    "learned_these_word": "Tocmai ai învățat aceste cuvinte.",
    "span_learn_by_examples": "Învață esperanto prin exemple",
    "Btn_Start_learning": "Începe să înveți",
    "btn_continue": "Continua",
    "btn_listen_continue": "Ascultă și continuă",
    "btn_listen": "Asculta",
    "btn_hard": "Greu pentru mine",
    "btn_easy": "Ușor pentru mine",
    "btn_too_easy": "Prea ușor",
    "btn_login": "Log in",
    "Btn_StartA": "Începe să înveți",
    "Btn_logout": "Deconectare",
    "wordsA": "Cuvinte",
    "words_to_reviewA": "Cuvinte de revizuit",
    "familiarA": "Familiar",
    "masteredA": "Stăpânit",
    "progressA": "Progres",
    "pointsA": "Puncte",
    "progress_msg": "Progresul curent este $PROGRESS %. În ce procentaj vrei să sari? Dacă vrei jumătate, introduceți 50.",
    "wrong_progress_input": "Intrare nevalidă! Introduceți o valoare procentuală între 0 și 100 ca număr întreg.",
    "learned_these_words": "Tocmai ai învățat aceste cuvinte.",
    "select_wrong_word": "Selectați un cuvânt greșit.",
    "Span_start_learn": "Începe să înveți",
  },
  "lt": {
    "type_e-mail": "Įveskite savo el. pašto adresą.",
    "type_e-mail_again": "Dar kartą įveskite savo el. pašto adresą.",
    "type_e-mail_twice": "Du kartus įveskite savo el.",
    "listen_and_fill": "Klausykite ir užpildykite tuščias vietas.",
    "match_correct": "Suderinkite tinkamas poras.",
    "choose_the_level": "Pasirinkite lygį, kaip jaučiatės šiuo klausimu.",
    "select_what_you_hear": "Pasirinkite tai, ką girdite.",
    "select_correct_one": "Pasirinkite tinkamą.",
    "learned_these_word": "Jūs ką tik išmokote šiuos žodžius.",
    "span_learn_by_examples": "Išmokite esperanto pagal pavyzdžius",
    "Btn_Start_learning": "Pradėti mokytis",
    "btn_continue": "Tęsti",
    "btn_listen_continue": "Klausyk ir Tęsk",
    "btn_listen": "Klausyk",
    "btn_hard": "Sunku man",
    "btn_easy": "Man lengva",
    "btn_too_easy": "Per lengva",
    "btn_login": "Prisijungti",
    "Btn_StartA": "Pradėti mokytis",
    "Btn_logout": "Atsijungti",
    "wordsA": "Žodžiai",
    "words_to_reviewA": "Žodžiai peržiūrėti",
    "familiarA": "Pažįstamas",
    "masteredA": "Įvaldyta",
    "progressA": "Progresas",
    "pointsA": "Taškai",
    "progress_msg": "Dabartinė pažanga yra $ PROGRESS %. Į kokią procentinę poziciją norite peršokti? Jei norite pusės, įveskite 50.",
    "wrong_progress_input": "Neteisinga įvestis! Įveskite procentinę reikšmę nuo 0 iki 100 kaip sveikąjį skaičių.",
    "learned_these_words": "Jūs ką tik išmokote šiuos žodžius.",
    "select_wrong_word": "Pasirinkite neteisingą žodį.",
    "Span_start_learn": "Pradėti mokytis",
  },
  "bg": {
    "type_e-mail": "Въведете своя имейл адрес.",
    "type_e-mail_again": "Въведете своя имейл адрес отново.",
    "type_e-mail_twice": "Въведете своя имейл два пъти.",
    "listen_and_fill": "Слушайте и попълвайте празните места.",
    "match_correct": "Свържете правилните двойки.",
    "choose_the_level": "Изберете нивото как се чувствате за това.",
    "select_what_you_hear": "Изберете това, което чувате.",
    "select_correct_one": "Изберете правилния.",
    "learned_these_word": "Вие току-що научихте тези думи.",
    "span_learn_by_examples": "Научете есперанто чрез примери",
    "Btn_Start_learning": "Започнете да учите",
    "btn_continue": "продължи",
    "btn_listen_continue": "Слушайте и продължавайте",
    "btn_listen": "Слушам",
    "btn_hard": "Трудно за мен",
    "btn_easy": "Лесно за мен",
    "btn_too_easy": "Твърде лесно",
    "btn_login": "Влизам",
    "Btn_StartA": "Започнете да учите",
    "Btn_logout": "Излез от профила си",
    "wordsA": "Думи",
    "words_to_reviewA": "Думи за преглед",
    "familiarA": "познато",
    "masteredA": "Овладян",
    "progressA": "Напредък",
    "pointsA": "Точки",
    "progress_msg": "Текущият напредък е $PROGRESS %. До каква процентна позиция искате да скочите? Ако искате половината, въведете 50.",
    "wrong_progress_input": "Невалиден вход! Въведете процентна стойност между 0 и 100 като цяло число.",
    "learned_these_words": "Вие току-що научихте тези думи.",
    "select_wrong_word": "Изберете грешна дума.",
    "Span_start_learn": "Започнете да учите",
  },
  "sk": {
    "type_e-mail": "Zadajte svoju e-mailovú adresu.",
    "type_e-mail_again": "Znova zadajte svoju e-mailovú adresu.",
    "type_e-mail_twice": "Zadajte svoj e-mail dvakrát.",
    "listen_and_fill": "Počúvajte a vyplňte prázdne miesta.",
    "match_correct": "Spojte správne dvojice.",
    "choose_the_level": "Vyberte si úroveň, ako sa na to cítite.",
    "select_what_you_hear": "Vyberte, čo počujete.",
    "select_correct_one": "Vyberte ten správny.",
    "learned_these_word": "Práve ste sa naučili tieto slová.",
    "span_learn_by_examples": "Naučte sa esperanto na príkladoch",
    "Btn_Start_learning": "Začnite sa učiť",
    "btn_continue": "ďalej",
    "btn_listen_continue": "Počúvajte a pokračujte",
    "btn_listen": "Počúvaj",
    "btn_hard": "Pre mňa ťažké",
    "btn_easy": "Pre mňa ľahké",
    "btn_too_easy": "Príliš ľahké",
    "btn_login": "Prihlásiť sa",
    "Btn_StartA": "Začnite sa učiť",
    "Btn_logout": "Odhlásiť sa",
    "wordsA": "Slová",
    "words_to_reviewA": "Slová na preskúmanie",
    "familiarA": "Známy",
    "masteredA": "Zvládol",
    "progressA": "Pokrok",
    "pointsA": "Body",
    "progress_msg": "Aktuálny pokrok je $PROGRESS %. Na akú percentuálnu pozíciu chcete skočiť? Ak chcete polovicu, zadajte 50.",
    "wrong_progress_input": "Neplatný vstup! Zadajte percentuálnu hodnotu medzi 0 a 100 ako celé číslo.",
    "learned_these_words": "Práve ste sa naučili tieto slová.",
    "select_wrong_word": "Vyberte nesprávne slovo.",
    "Span_start_learn": "Začnite sa učiť",
  },
  "sl": {
    "type_e-mail": "Vnesite svoj e-poštni naslov.",
    "type_e-mail_again": "Ponovno vnesite svoj e-poštni naslov.",
    "type_e-mail_twice": "Dvakrat vnesite svoj e-mail.",
    "listen_and_fill": "Poslušaj in izpolni praznine.",
    "match_correct": "Poveži pravilne pare.",
    "choose_the_level": "Izberite raven, kako se počutite glede tega.",
    "select_what_you_hear": "Izberite, kar slišite.",
    "select_correct_one": "Izberite pravilno.",
    "learned_these_word": "Pravkar ste se naučili te besede.",
    "span_learn_by_examples": "Naučite se esperanta na primerih",
    "Btn_Start_learning": "Začnite se učiti",
    "btn_continue": "Nadaljuj",
    "btn_listen_continue": "Poslušaj in nadaljuj",
    "btn_listen": "poslušaj",
    "btn_hard": "Težko zame",
    "btn_easy": "Zame enostavno",
    "btn_too_easy": "Preveč lahko",
    "btn_login": "Vpiši se",
    "Btn_StartA": "Začnite se učiti",
    "Btn_logout": "Odjava",
    "wordsA": "Besede",
    "words_to_reviewA": "Besede za pregled",
    "familiarA": "Poznan",
    "masteredA": "Obvladal",
    "progressA": "Napredek",
    "pointsA": "Točke",
    "progress_msg": "Trenutni napredek je $PROGRESS %. Na kateri odstotek položaja želite skočiti? Če želite polovico, vnesite 50.",
    "wrong_progress_input": "Neveljaven vnos! Vnesite odstotno vrednost med 0 in 100 kot celo število.",
    "learned_these_words": "Pravkar ste se naučili te besede.",
    "select_wrong_word": "Izberite napačno besedo.",
    "Span_start_learn": "Začnite se učiti",
  },
  "et": {
    "type_e-mail": "Sisestage oma e-posti aadress.",
    "type_e-mail_again": "Sisestage oma e-posti aadress uuesti.",
    "type_e-mail_twice": "Sisesta oma e-mail kaks korda.",
    "listen_and_fill": "Kuulake ja täitke lüngad.",
    "match_correct": "Sobitage õiged paarid.",
    "choose_the_level": "Valige tase, kuidas te sellesse suhtute.",
    "select_what_you_hear": "Valige, mida kuulete.",
    "select_correct_one": "Valige õige.",
    "learned_these_word": "Õppisite just need sõnad selgeks.",
    "span_learn_by_examples": "Õppige esperantot näidete järgi",
    "Btn_Start_learning": "Alustage õppimist",
    "btn_continue": "Jätka",
    "btn_listen_continue": "Kuula ja jätka",
    "btn_listen": "Kuulake",
    "btn_hard": "Minu jaoks raske",
    "btn_easy": "Minu jaoks lihtne",
    "btn_too_easy": "Liiga lihtne",
    "btn_login": "Logi sisse",
    "Btn_StartA": "Alustage õppimist",
    "Btn_logout": "Logi välja",
    "wordsA": "Sõnad",
    "words_to_reviewA": "Sõnad ülevaatamiseks",
    "familiarA": "Tuttav",
    "masteredA": "Meisterdatud",
    "progressA": "Edusammud",
    "pointsA": "Punktid",
    "progress_msg": "Praegune areng on $ PROGRESS %. Millisele protsendipositsioonile soovite hüpata? Kui soovite poole, sisestage 50.",
    "wrong_progress_input": "Vigane sisestus! Sisestage täisarvuna protsendiväärtus vahemikus 0 kuni 100.",
    "learned_these_words": "Õppisite just need sõnad selgeks.",
    "select_wrong_word": "Valige vale sõna.",
    "Span_start_learn": "Alustage õppimist",
  },
  "cs": {
    "type_e-mail": "Zadejte svou e-mailovou adresu.",
    "type_e-mail_again": "Zadejte znovu svou e-mailovou adresu.",
    "type_e-mail_twice": "Zadejte svůj e-mail dvakrát.",
    "listen_and_fill": "Poslouchejte a vyplňte prázdná místa.",
    "match_correct": "Spojte správné dvojice.",
    "choose_the_level": "Vyberte si úroveň, jak se na to cítíte.",
    "select_what_you_hear": "Vyberte, co slyšíte.",
    "select_correct_one": "Vyberte ten správný.",
    "learned_these_word": "Právě jste se naučili tato slova.",
    "span_learn_by_examples": "Naučte se esperanto na příkladech",
    "Btn_Start_learning": "Začněte se učit",
    "btn_continue": "Pokračovat",
    "btn_listen_continue": "Poslouchejte a pokračujte",
    "btn_listen": "Poslouchat",
    "btn_hard": "Těžké pro mě",
    "btn_easy": "Pro mě snadné",
    "btn_too_easy": "Příliš snadné",
    "btn_login": "Přihlásit se",
    "Btn_StartA": "Začněte se učit",
    "Btn_logout": "Odhlásit se",
    "wordsA": "Slova",
    "words_to_reviewA": "Slova ke kontrole",
    "familiarA": "Známý",
    "masteredA": "Zvládl",
    "progressA": "Pokrok",
    "pointsA": "Body",
    "progress_msg": "Aktuální pokrok je $PROGRESS %. Na jaké procento pozice chcete skočit? Pokud chcete polovinu, zadejte 50.",
    "wrong_progress_input": "Neplatný vstup! Zadejte procentuální hodnotu mezi 0 a 100 jako celé číslo.",
    "learned_these_words": "Právě jste se naučili tato slova.",
    "select_wrong_word": "Vyberte špatné slovo.",
    "Span_start_learn": "Začněte se učit",
  },
  "fi": {
    "type_e-mail": "Kirjoita sähköpostiosoitteesi.",
    "type_e-mail_again": "Kirjoita sähköpostiosoitteesi uudelleen.",
    "type_e-mail_twice": "Kirjoita sähköpostiosoitteesi kahdesti.",
    "listen_and_fill": "Kuuntele ja täytä tyhjät kohdat.",
    "match_correct": "Yhdistä oikeat parit.",
    "choose_the_level": "Valitse taso, miltä sinusta tuntuu.",
    "select_what_you_hear": "Valitse mitä kuulet.",
    "select_correct_one": "Valitse oikea.",
    "learned_these_word": "Olet juuri oppinut nämä sanat.",
    "span_learn_by_examples": "Opi esperantoa esimerkkien avulla",
    "Btn_Start_learning": "Aloita oppiminen",
    "btn_continue": "Jatkaa",
    "btn_listen_continue": "Kuuntele ja Jatka",
    "btn_listen": "Kuunnella",
    "btn_hard": "Vaikea minulle",
    "btn_easy": "Helppoa minulle",
    "btn_too_easy": "Liian helppo",
    "btn_login": "Kirjaudu sisään",
    "Btn_StartA": "Aloita oppiminen",
    "Btn_logout": "Kirjautua ulos",
    "wordsA": "Sanat",
    "words_to_reviewA": "Sanat arvosteltavaksi",
    "familiarA": "Tuttu",
    "masteredA": "Masteroitu",
    "progressA": "Edistyminen",
    "pointsA": "Pisteet",
    "progress_msg": "Tämänhetkinen edistys on $PROGRESS %. Mihin prosenttiin haluat hypätä? Jos haluat puolet, syötä 50.",
    "wrong_progress_input": "Virheellinen syöte! Syötä kokonaislukuna prosenttiarvo väliltä 0–100.",
    "learned_these_words": "Olet juuri oppinut nämä sanat.",
    "select_wrong_word": "Valitse väärä sana.",
    "Span_start_learn": "Aloita oppiminen",
  },
  "hu": {
    "type_e-mail": "Írja be az e-mail címét.",
    "type_e-mail_again": "Írja be újra az e-mail címét.",
    "type_e-mail_twice": "Írja be kétszer az e-mail címét.",
    "listen_and_fill": "Hallgassa meg és töltse ki az üres helyeket.",
    "match_correct": "Párosítsa össze a megfelelő párokat.",
    "choose_the_level": "Válassza ki azt a szintet, amit ezzel kapcsolatban érzel.",
    "select_what_you_hear": "Válassza ki, amit hall.",
    "select_correct_one": "Válassza ki a megfelelőt.",
    "learned_these_word": "Most tanultad meg ezeket a szavakat.",
    "span_learn_by_examples": "Tanuljon eszperantót példák alapján",
    "Btn_Start_learning": "Kezdje el a tanulást",
    "btn_continue": "Folytatni",
    "btn_listen_continue": "Hallgassa meg és folytassa",
    "btn_listen": "Hallgat",
    "btn_hard": "Nehéz nekem",
    "btn_easy": "Könnyű nekem",
    "btn_too_easy": "Túl könnyű",
    "btn_login": "Belépés",
    "Btn_StartA": "Kezdje el a tanulást",
    "Btn_logout": "Kijelentkezés",
    "wordsA": "Szavak",
    "words_to_reviewA": "Szavak felülvizsgálatra",
    "familiarA": "Ismerős",
    "masteredA": "Elsajátította",
    "progressA": "Előrehalad",
    "pointsA": "Pontok",
    "progress_msg": "A jelenlegi haladás $ PROGRESS %. Hány százalékos pozícióra szeretne ugrani? Ha a felét szeretné, írja be az 50-et.",
    "wrong_progress_input": "Hibás bemenet! Adjon meg egy százalékos értéket 0 és 100 között egész számként.",
    "learned_these_words": "Most tanultad meg ezeket a szavakat.",
    "select_wrong_word": "Válasszon ki egy rossz szót.",
    "Span_start_learn": "Kezdje el a tanulást",
  },
  "el": {
    "type_e-mail": "Πληκτρολογήστε τη διεύθυνση e-mail σας.",
    "type_e-mail_again": "Πληκτρολογήστε ξανά τη διεύθυνση e-mail σας.",
    "type_e-mail_twice": "Εισαγάγετε το e-mail σας δύο φορές.",
    "listen_and_fill": "Ακούστε και συμπληρώστε τα κενά.",
    "match_correct": "Ταίριαξε σωστά ζεύγη.",
    "choose_the_level": "Επιλέξτε το επίπεδο που αισθάνεστε για αυτό.",
    "select_what_you_hear": "Επιλέξτε αυτό που ακούτε.",
    "select_correct_one": "Επιλέξτε το σωστό.",
    "learned_these_word": "Μόλις μάθατε αυτές τις λέξεις.",
    "span_learn_by_examples": "Μάθετε Εσπεράντο με Παραδείγματα",
    "Btn_Start_learning": "Ξεκινήστε να μαθαίνετε",
    "btn_continue": "Να συνεχίσει",
    "btn_listen_continue": "Ακούστε και Συνέχισε",
    "btn_listen": "Ακούω",
    "btn_hard": "Δύσκολο για μένα",
    "btn_easy": "Εύκολο για μένα",
    "btn_too_easy": "Πολύ εύκολο",
    "btn_login": "Σύνδεση",
    "Btn_StartA": "Ξεκινήστε να μαθαίνετε",
    "Btn_logout": "Αποσύνδεση",
    "wordsA": "Λόγια",
    "words_to_reviewA": "Λέξεις για αναθεώρηση",
    "familiarA": "Οικείος",
    "masteredA": "Mastered",
    "progressA": "Πρόοδος",
    "pointsA": "Πόντοι",
    "progress_msg": "Η τρέχουσα πρόοδος είναι $PROGRESS %. Σε τι τοις εκατό θέση θέλετε να μεταβείτε; Αν θέλετε το μισό, βάλτε 50.",
    "wrong_progress_input": "Μη έγκυρη εισαγωγή! Εισαγάγετε μια ποσοστιαία τιμή μεταξύ 0 και 100 ως ακέραιος.",
    "learned_these_words": "Μόλις μάθατε αυτές τις λέξεις.",
    "select_wrong_word": "Επιλέξτε μια λάθος λέξη.",
    "Span_start_learn": "Ξεκινήστε να μαθαίνετε",
  },
}
