A_course = [
    'mi, vi',
    'estas, estis',
    'mi estas ~',
    'vi estas ~',
    'saluton',
    'saluton, mi estas ~',
    'mia, via',
    'nomo',
    'mia nomo, via nomo',
    'mia nomo estas ~',
    'via nomo estas ~',
    'fartas, fartis',
    'estis, estos',
    'nomo, nomon',
    'mia amo',
    'vi fartas',
    'kiel',
    'kiel vi fartas?',
    'kio',
    'kio estas via nomo?',
    'bona, bone',
    'fartas bone',
    'mi fartas bone',
    'kaj',
    'bone, kaj vi?',
    'ĝis ~',
    'vidas, vidis',
    'vidis, revidis',
    'revidis, revidos',
    'revido, revidon',
    'ĝis revido!',
    'dankon',
    'dankon kaj ĝis revido!',
    'al ~',
    'al vi, al mi',
    'dankas, dankis',
    'mi dankas al vi',
    'jes, ne',
    'jes, dankon',
    'manĝas, manĝos',
    'mi ne manĝas',
    'ne, mi ne manĝas',
    'bela, bele',
    '-inda',
    'dankinda, dankinde',
    'tuta, tute',
    'tuto, tuton',
    'nedankinde',
    'tute ne',
    'pardoni ~, pardono',
    'pardonon al mi',
    'pardonon',
    'pardonon, mi petas',
    'bona mateno',
    'bonan matenon',
    'bonan nokton',
    'bonan sonĝon',
    'bonan vojaĝon, al vi',
    'bonan tagon',
    'ĉu ~',
    'ĉu vi fartas bone?',
    'jes, mi fartas bone',
    'ne, tute ne',
    'tre, tro',
    'granda, grande',
    'tre bona, tro granda',
    'vi tre bone fartas',
    'ne tre bone',
    'lerni ~, lerno',
    'vidanta, vidanto',
    'lernanta, lernanto',
    '-anta, -anto',
    'lernanto, lerninto',
    'mi estas lernanto',
    '~ estas mia amiko',
    'li, ŝi',
    'sidi, sidas',
    'sidanta, sidinta, sidonta',
    'li sidas kaj ŝi lernas',
    'ĉambro',
    'lernas en ĉambro',
    'lernanto kaj sportisto',
    'sporto kaj sportisto',
    'sportisto nun sportas',
    'li estas lernanto',
    'estas lernanto kaj sportisto',
    'li nun sidas',
    'kaj nun lernas',
    'sidas kaj lernas',
    'nun en ĉambro',
    'estas sur tablo',
    'papero kaj paperoj',
    'tablo kaj tabloj',
    'libro kaj libroj',
    'la paperoj kaj libroj',
    'ĝi estas sur tablo',
    'skribas sur la skribotablo',
    'la libroj estas ~',
    'sur la tablo',
    'lernolibro kaj la lernolibroj',
    'sur la tablo estas ~',
    'patro kaj patrino',
    'la patro kaj la patrino',
    'la patrino de mia amiko',
    'en la ĉambro',
    'ne estas en la ĉambro',
    'ili nun laboras',
    'lia patro estas laboristo',
    'li laboras en hotelo',
    'la patrino instruas',
    'ŝi estas instruistino',
    'ĉu ŝi estas patrino?',
    'ne, ŝi estas hotelisto',
    'ne, mi ne laboras',
    'kio estas ŝia nomo?',
    'kiu nun respondas?',
    'la lingvo de ilia patrino',
    'ĉu via nomo estas ~ ?',
    'ni sidas kaj respondas',
    'ŝia labora seĝo',
    'ĝia nomo ne estas ~',
    'ŝia lingvo estas ilia lingvo',
    'nia patro kaj patrino',
    'via lernanto, viaj lernantoj',
    'ĉu ili estas viaj lernantoj?',
    'ĉu vi estas lernanto?',
    'ĉu vi estas en la ĉambro?',
    'mi ne estas ~',
    'esperantisto kaj esperantistino',
    'enskribis por la hotelĉambro',
    'lingvisto kaj laboristino',
    'lia amikino estas ~',
    'lernantoj kaj sportistoj',
    'mia familia nomo estas ~',
    'kiu estas ŝi?',
    'estas via amikino',
    'ĉu via amiko estas ~ ?',
    'skribas nun en la ĉambro',
    'ĉu la amiko de via patro ~ ?',
    'laboras en hotelo',
    'kio estas sur la tablo?',
    'sur la tablo en nia ĉambro',
    'ĉu la lernolibro de Esperanto ~ ?',
    'estas sur via tablo',
    'havas amikinon',
    'ŝia nomo estas ~',
    'juna kaj bela',
    'estas juna kaj bela',
    'junaj kaj belaj amikoj',
    'estas geamikoj',
    'hejmo de ŝia instruisto',
    'venis al la hejmo',
    'la hejmo de ~',
    'bonvolu eniri',
    'saluton! kion vi faras?',
    'kion vi faras?',
    'sed nun mi volas ~',
    'mi volas paroli',
    'kun tri geamikoj',
    'parolis kun vi',
    'volas paroli kun vi',
    'ĉu vi havas geamikojn?',
    'li havas libron',
    'havas bonan libron',
    'jes, mi havas',
    'ili ŝatas ĝin',
    'ŝi legis libron',
    'ŝatas legi librojn',
    'nur bona libro',
    'multaj bonaj libroj',
    'legis nur bonajn librojn',
    'ŝatas legi bonajn librojn',
    'ĉu vi volas legi?',
    'la junulo trinkis kafon',
    'volas trinki akvon',
    'patro kaj patrino, gepatroj',
    'frato kaj fratino, gefratoj',
    'viaj gepatroj kaj gefratoj',
    'estas en via hejmo',
    'jen la kafo',
    'ankoraŭ ne trinkis',
    'estas ankoraŭ varma',
    'hieraŭ kuiris ĝin',
    'mi nun kuiris',
    'dankon. tiel li diris',
    'povas trinki kaj manĝi',
    'trinkis malvarman kafon',
    'ankaŭ varma kafo',
    'trinkas ankaŭ malvarman kafon',
    'povas trinki ankaŭ malvarman kafon',
    'rigardas ŝian okulon',
    'la plej bela okulo',
    'la belaj okuloj',
    'rigardis la belajn okulojn',
    'la belaj okuloj de ŝi',
    'vidas kaj komprenas',
    'mi vidas, ke ~',
    'ke li amas ŝin',
    'ŝi sentis, ke li amas ŝin',
    'demandas, ĉu tio estis granda',
    'pri facila demando',
    'diris pri nova mono',
    'tre belaj okuloj',
    'rigardis la grandan fraton',
    'malgranda fratino forgesis ĝin',
    'akuzativo',
    'ne forgesu akuzativon',
    'kiun vi vidas?',
    'mi vidas amikon',
    'havas bonajn geamikojn',
    'ili laboras pri la malnova domo',
    'laboras, laboris, laboros',
    'vidas, ke mi manĝas',
    'diris, ke li iros',
    'malbela kaj malbona',
    'kion ŝi diris?',
    'kion vi atendas?',
    'eniris en la ĉambron',
    'enhavo estis tre malfacila',
    'alvenis al la kunsido',
    'bonvenon, al la kunveno',
    'maljuna viro donis trinkmonon',
    'alvenis kaj estis bonvena',
    'ili malamas sed kunlaboras.',
    'iris al la hotelo',
    'havas facilajn lernolibrojn',
    'kia estis via patrino?',
    'via malnova hejmo',
    'kiujn librojn vi legis?',
    'ĉu ili estis bonaj?',
    'kion faris hieraŭ?',
    'en la malgranda ĉambro',
    'tre longe parolis',
    'parolis antaŭ la lernejo',
    'poste parolis pri la libro',
    'ĝoje iris al la lernejo',
    'tra la strato',
    'iris tra la strato',
    'estis varma tago',
    'ili vidis kafejon',
    'vidis ruĝajn kukojn',
    'vidis kukojn en ĝi',
    'vidis kafejon kaj en ĝi kukojn',
    'eniru kaj manĝu!',
    'ni eniru kaj manĝu',
    'havas sufiĉan monon',
    'ĉu vi havas sufiĉan monon?',
    'ĉu vi komprenas?',
    'kompreneble!',
    'tio ne sufiĉas',
    'cent dolaroj sufiĉas',
    'dolaro, dolaroj, dolarojn',
    'havas cent dolarojn',
    'kompreneble, mi havas',
    'ho! vi estas riĉa!',
    'kelnero, kelnerino',
    'kelnero portas menuon',
    'portis tion al ni, alportis tion',
    'kelnero alportis multajn kukojn',
    'ili manĝis iom',
    'post la manĝo',
    'nova, denove',
    'la kelnero denove venis',
    'en iu loko',
    'serĉis en iu loko',
    'serĉis en alia loko',
    'lia vizaĝo estis ĝoja',
    'ŝi estis malĝoja',
    'fine kaj finfine',
    'via forta voĉo',
    'en malforta voĉo',
    'ne havas monon',
    'kio okazis tie?',
    'akcidento okazis poste',
    'ĉu vi scias, kiam ĝi okazis?',
    'scias pri la afero',
    'ankoraŭ unu afero restas',
    'vi aŭ ŝi, ajna homo',
    'kiel kantisto',
    'kantis kiel profesia kantisto',
    'tie, kie ŝi loĝis',
    'kiel vi scias pri la aŭto?',
    'nu, vidu la rapidan aŭton',
    'suko sen sukero',
    'li havis rapidan veturilon',
    'tro forte',
    'li tro forte malfermis',
    'veturis tro rapide',
    'manĝis per kulero',
    'ni forte dubas',
    'vera letero de li',
    'amletero kun kvin fotoj',
    'revenis, revenintoj',
    'ankaŭ ses leteroj revenis',
    'volis vidi la foton',
    'revenis el la lernejo',
    'kiam revenos la fratino?',
    'volis legi denove',
    'faris, fariĝis',
    'rapide fariĝis ruĝa',
    'staris kaj sidis',
    'tie staris antaŭ la foto',
    'mi havas tion',
    'kion vi havas en via mano?',
    'antaŭ aŭ malantaŭ?',
    'antaŭ aŭ post?',
    'tie malantaŭ la pordo',
    'aliaj, aliaj homoj',
    'leteroj de aliaj',
    'falis el la mano',
    'sur la tablo, sur la tablon',
    'ĝi falis sur la tablon',
    'petis pardonon',
    'serĉis kvin librojn',
    'pardonu, mi serĉis mian libron',
    'sed vi bone scias',
    'ne estas sur mia tablo',
    'viaj libroj ne estas sur mia tablo',
    'ree donis, redonis',
    'redonu la leteron al mi.',
    'ricevis bonan lecionon',
    'plu lavis, ne plu manĝis',
    'ne plu legos',
    'ankaŭ mi ricevis',
    'devas fermi',
    'mi devas bone fermi',
    'bone fermis la pordon',
    'trankvila, trankviliĝu',
    'aŭdis sed ne aŭskultis',
    'aŭdis trankvilan sonon',
    'ĉe mi estis kvar poŝoj',
    'dek tagoj post la lasta leciono',
    'inter la du tabloj',
    'tri leteroj, ses paperoj',
    'de kapo ĝis piedo',
    'kvar, kvara, kvaropo, kvarono',
    'kien iris la triopo?',
    'kvin fingroj en ambaŭaj manoj',
    'si mem, sia poŝo',
    'meti, kunmeti, kunmetaĵo',
    'metis en sian poŝon',
    'du cent nacioj en la mondo',
    'prenis, forprenis',
    'prenis sep el siaj naŭ libroj',
    'lasi, forlasita',
    'lasu min sola kaj trankvila',
    'mil ok cent ok dek sep',
    'taso da teo',
    'oni lavis ok tasojn',
    'du mil dek naŭ',
    'li lavis sin',
    'sia korpo, sia propra posedo',
    'sur la tablo, la kato dormis',
    'la kato saltis sur la tablon',
    'en la halo, en la halon',
    'enfalis en lian manon',
    'labori, ellabori',
    'ellabori por tiu libro',
    'scias, scivolas, scivolo',
    'dulingva, dulingveco',
    'scivolas pri trilingva lernanto',
    'iris, reiris',
    'la katoj reiris al siaj domoj',
    'en la sako, en la sakon',
    'enmetu ĝin en vian sakon',
    'piedo, piediras, piediranto',
    'dek-tage ili piediris',
    'preni, elpreni',
    'belaj floroj, prenis belajn florojn',
    'li elprenis nur belajn florojn',
    'malfermis, sed tuj fermis',
    'malfermis internacian kunvenon',
    'eldonis kaj disdonis',
    'la eldonisto eldonis dudek tri librojn',
    'revenis kaj revidis sian filon',
    'en la jaro dumil dudek tri',
    'sinjoro eniris la vendejon',
    'la vendejo de aŭtoj',
    'tie li vidas sinjorinon',
    'karaj gesinjoroj',
    'tio plaĉis al mi',
    'la sinjorino plaĉis al li',
    'vidis la belan sinjorinon',
    'kiu plaĉis al li?',
    'la virino, kiu plaĉis al mi',
    'tiu, kiu eniris la domon',
    'la viro, kiu donacis ĝin',
    'li donacis ringon al lia edzino',
    'la ringo plaĉis al ŝi',
    'la edzino, al kiu la ringo plaĉis',
    'vendisto laboras en la vendejo',
    'vendisto de aŭtoj',
    'la sinjoro demandis al la vendisto',
    'kiu aŭto plaĉas al vi?',
    'kiun aŭton vi elektos?',
    'mi elektis tiun aŭton',
    'ĝi estas pli bona',
    'pli bona ol ĉi tio',
    'plej bona el ili',
    'estas la plej bona',
    'kiu aŭto estas la plej bona?',
    'tiu ĉi aŭto estas pli bona',
    'tiu ĉi estas la plej bona',
    'vidis ĉiujn aŭtojn',
    'la plej bona el ĉiuj',
    'ĉu ĝi estas rapida?',
    'pli rapida ol aliaj',
    'estas ankaŭ forta',
    'ho jes, kompreneble!',
    'estas tre forta',
    'certe ĝi estas forta',
    'estas ankaŭ multekosta',
    'la plej multekosta el ĉiuj',
    'malmultekosta sed forta',
    'bedaŭras kaj bedaŭrindas',
    'bedaŭrinde mi ne aĉetos',
    'estas bedaŭrinda afero',
    'li aĉetis novan aŭton',
    'ĉar mi ne havas monon',
    'mia malnova aŭto',
    'la plej malmultekosta el ĉiuj',
    'mi veturos tien',
    'ankoraŭ veturos per ĝi',
    'dum la tuta tago',
    'dum li diris tion',
    'li denove rigardis ŝin',
    'sed la vendisto diris',
    'estus pli bone, ke ~',
    'rigardu tiun ĉi sinjorinon',
    'ankaŭ tio estas tre multekosta',
    'mi estas ŝia edzo',
    'kiom via vojaĝo kostis?',
    'aŭskultu la kanton de via edzino',
    'ne forgesu, ke ĝi tre multe kostas',
    'li helpis la vendiston dum du horoj',
    'jam pli ol tri jaroj',
    'kovri, kovrilo, malkovri',
    'la kialon li ankoraŭ ne malkovris',
    'kial vi komencis sendi leterojn?',
    'dum ok monatoj li vivis tie',
    'ne havis tempon por aŭskulti',
    'la aŭto estis jam plena',
    'kion vi manĝas?',
    'kia estas la vetero?',
    'kian aŭton vi havas?',
    'kiaj estis ŝiaj leteroj?',
    'kie ni estas?',
    'kien vi iras?',
    'al kiu vi donis ĝin?',
    'la viro, kun kiu vi vojaĝis',
    'pli granda ol la aŭto',
    'la plej alta el tiuj homoj',
    'li sidis dum la manĝo',
    'ŝi skribas dum li legas',
    'ĉi tie, en ĉi tiu ĉambro',
    'tiu ĉi sinjoro',
    'aŭskultinda novaĵo',
    'la libro estas vere leginda',
    'bedaŭra afero',
    'bedaŭrinde, mi ne povas',
    'nedankinde. estis mia plezuro',
    'eta belulino ege belas',
    'ĉiuj amikoj amas ŝin',
    'antaŭ tri monatoj',
    'okazis malbono al ŝi',
    'ŝi falis pro aŭto',
    'malsaniĝis kaj temperaturo altiĝis',
    'patrino diris, ke ŝi devas ripozi',
    'ŝi devas resti hejme',
    'ŝi vokos doktoron',
    'je la naŭa horo',
    'matene venis je la oka',
    'je la sepa morgaŭ vespere',
    'montris liajn manojn',
    'vesto, vestiĝas',
    'vestiĝu kaj varmigu vian korpon',
    'hejme tuj malvestis kaj duŝis',
    'doktoro rigardis ĉion',
    'bone rigardis kaj fine diris',
    'unu semajnon restu hejme',
    'deziras, ke vi estu trankvila',
    'post unu semajno',
    'vi fartos pli bone',
    'trinku multe da teo',
    'venos por revidi vin',
    'ankaŭ li estu trankvila',
    'sana homo, sanulo',
    'zorgis pri si mem',
    'tuta afero tuje utilis al mi',
    'rimarkis, ke teruraĵo proksimas',
    'petis tuj rimarki ĝin',
    'pensis, ke tio ne necesas',
    'loĝis proksime, kaj tio utilis',
    'nia lando hodiaŭ teruriĝis',
    'karaj infanoj el ĉiuj familioj',
    'unu fojon hieraŭ, du fojojn morgaŭ',
    'hodiaŭ familioj bezonas infanojn',
    'esperis, ke li fartos bone morgaŭ',
    'li fartis ege trankvila',
    'tri etuloj altigis la monton',
    'gravuloj ne petis helpon',
    'piediris tien por helpi',
    'restu hejme se temperaturo altas',
    'temperaturo restis simila hodiaŭ',
    'voku la doktoron je la naŭa',
    'montru ĝin al via doktoro',
    'por montri vian piedon',
    'vestu ĉi tiun ĉemizon',
    'semajnfine ĉio trankviliĝos',
    'sub la te-taso kion vi trovis?',
    'mi deziras matenan teon',
    'esperis trankvilan vesperon',
    'deziras, ke vi lernu',
    'insistis, ke mi iru',
    'je kioma horo?',
    'je kvina horo',
    'je la sesa, li venos',
    'la libreto estis ĉarma',
    'estu trankvila',
    'li estu trankvila',
    'ankaŭ li',
    'mi deziras',
    'mi deziras, ke ~',
    'ke vi lernu',
    'mi deziras, ke vi lernu',
    'patro insistas',
    'patro insistas, ke ~',
    'ke mi iru',
    'patro insistas, ke mi iru',
    'je kioma horo',
    'je kioma horo vi venos?',
    'je la kvina',
    'je la kvina horo',
    'kiel li fartas?',
    'kiel vi fartis lastatempe?',
    'etaj libroj belas',
    'libreto, belaj libroj',
    'bela, beleta, belega',
    'varma, varmeta, varmega',
    'librego, libreto',
    'bona, bonega, bonege',
    'riĉa, riĉiĝi, riĉulo',
    'trankvila, trankviliĝi, trankviliĝu',
    'sana, resaniĝi, resaniĝis',
    'edzo, edziĝo, geedziĝis',
    'leterportisto',
    'hejmlando',
    'iom, iomete',
    'ni bonege vespermanĝis',
    'espereble, prizorgu vin',
    'mi zorgis pri la altkvalita loĝejo',
    'pripensu dufoje, multfoje',
    'kiu deprenis la libreton?',
    'kato, kiu nomiĝas Cezaro',
    'kuko, kiu estas sur la tablo',
    'manĝu kukon, kiu estas sur la tablo',
    'fariĝis varmega kaj ruĝiĝis',
    'patro volas, ke lia infano manĝu',
    'en malgranda ĉambro',
    'ni loĝas en ~',
    'mi fariĝis maltrankvila',
    'tiam, kiam mi vidis vin',
    'ĉiuj rimarkis tion',
    'tion, ke ŝi estas belega',
    'ĉu vi deziras, ke ~ ?',
    'ke mi montru al vi',
    'ĉu vi deziras, ke mi montru?',
    'mian plej novan libron',
    'morgaŭ matene, kion vi volas?',
    'matenmanĝis malfrue',
    'kiam Marko alvenos?',
    'je la kvina aŭ je la oka horo',
    'kiam vi rimarkis, ke ~ ?',
    'la tuta familio nomas min bonfarulo',
    'utila por vi',
    'ĉu la libreto estis utila?',
    'tiu libreto, kiun mi sendis',
    'matene dormis tre longe',
    'kiam li vidis la sunon',
    'subite li eksaltis',
    'li estis ĉiam frua',
    'ĉiam li malfruas',
    'tiam, kiam li devas iri',
    'iri al la lernejo',
    'li scias, ke ~',
    'li scias tion, ke ~',
    'tion, ke la instruisto malŝatas abelon',
    'scias tion, ke la instruisto malŝatas abelon',
    'scias, ke la instruisto malŝatas tion',
    'sed hodiaŭ li trinkis la kafon',
    'li rapide surmetas la vestaĵon',
    'li ne volas malfrui',
    'rapidege kun la libroj en la mano',
    'poste li kuris kaj saltis',
    'li kuris kaj saltis',
    'laŭ la strato',
    'la homoj rigardis lin',
    'rigardis lin kaj diris',
    'saĝa kaj malsaĝa',
    'kia malsaĝa knabo!',
    'estis antaŭ lernejo',
    'baldaŭ',
    'li estis antaŭ ~',
    'iri kaj eniri',
    'li volis eniri',
    'eniri la lernejon',
    'sed tamen',
    'sed li ne povis',
    'fermi kaj fermita',
    'ĝi estis fermita',
    'nek ~ nek ~',
    'nek instruisto nek gelernantoj',
    'vidis nek instruiston nek gelernantojn',
    'sidi, eksidi',
    'eksidis',
    'li eksidis',
    'antaŭ la lernejo',
    'kaj pensis',
    'kio okazis?',
    'diable',
    'damne',
    'memoras',
    'nun mi memoras',
    'dimanĉo',
    'hodiaŭ estas ~',
    'hodiaŭ estas dimanĉo',
    'dormi kaj ekdormi',
    'suno kaj luno',
    'subita kaj subite',
    'ek!',
    'salti kaj eksaltis',
    'ĉiam frua',
    'hodiaŭ metis kaj kuris',
    'aĵo, ne aĝo',
    'kuris laŭ homoj saĝaj',
    'laŭeble baldaŭ',
    'kia knabo, kia knabino',
    'nek pensita nek memorita',
    'diablo atendis akvon dimanĉe',
    'tiom malgranda momento',
    'eĉ tiom malgranda momento valoras',
    'kriis for ĝis nokto',
    'lasis la poŝton de la mano',
    'ridis mem lasante la poŝton',
    'nek li nek ŝi ridis',
    'ŝi nek ridis nek respondis',
    'li nek sidas nek rigardas',
    'neniam mi vidis',
    'mi neniam diros al iu',
    'diru al neniu',
    'mi neniam diros',
    'mem',
    'mi mem faris',
    'faris tion',
    'mem faris tion',
    'ĝis la revido, ĝis revido',
    'ĝis!',
    'ekparoli',
    'ekparolis, komencis paroli finfine',
    'trinkis rapidege',
    'trinkis matenan trinkaĵon',
    'por frue veni',
    'veni al la lernejo',
    'frue veni al ~',
    'ne aŭdis novaĵon',
    'ankoraŭ ne aŭdis',
    'mi ankoraŭ ne aŭdis',
    'en tiu momento',
    'en tiu momento li ekkriis',
    'knabo, kiu ne amas',
    'geknaboj',
    'aliaj geknaboj',
    'ne amas aliajn geknabojn',
    'nek amikojn, nek amikinojn',
    'havas nek monon, nek tempon',
    'kiu havis la libron?',
    'la libron, kiun vi atendis',
    'tiun, kiun vi atendis pli ol du jarojn',
    'ĉu vi volas tion?',
    'ĉu vi volas, ke ~ ?',
    'plej kara',
    'plej kara foto',
    'mian plej karan foton',
    'kie vi aĉetis ~ ?',
    'tiu vestaĵo',
    'tiun vestaĵon',
    'aĉetis tiun vestaĵon',
    'vi iros tien',
    'kien vi iros?',
    'suna tago',
    'estos suna tago',
    'se estos suna tago',
    'via frato jam ekiris',
    'ĉu via frato jam ekiris?',
    'kie estas la akvo?',
    'kunporti la akvon',
    'vi mem kunportis',
    'la akvon, kion vi mem kunportis',
    'estis tre trankvila',
    'hodiaŭ mia patrino estis ~',
    'mi venis el ~',
    'el la lernejo',
    'raportis al ~',
    'kaj raportis al ŝi',
    'raportis, ke ~',
    'raportis, ke mi ricevos',
    'mi ricevos malbonan noton',
    'ŝi diris, ke ~',
    'vi devas laborigi ~',
    'pli multe',
    'pli multe laborigi',
    'laborigi vian kapon',
    'kiom da malbonaj notoj',
    'vi havas tiom da malbonaj notoj',
    'estis malĝoja',
    'en vian ĉambron',
    'iru en vian ĉambron',
    'iru kaj lernu',
    'mi sidis',
    'en mia ĉambro',
    'sidis en mia ĉambro',
    'nek lerni nek legi',
    'sed mi povis nek lerni nek legi',
    'miaj pensoj',
    'ĉe ludo',
    'ludo kun miaj amikoj',
    'ĉe sporto',
    'al mi mem',
    'diris al mi mem',
    'tiom malsaĝa',
    'ĉu mi estas tiom malsaĝa?',
    'kvankam mi lernis multe',
    'la patrino eniris',
    'miaj vortoj',
    'kaj aŭdis miajn vortojn',
    'ŝi tuj respondis',
    'ne, mia kara',
    'vi ne estas malsaĝa',
    'la problemo estas, ke ~',
    'ke vi devas lerni',
    'devas lerni multe pli',
    'tiam vi ne havos',
    'malbonaj notoj',
    'havos nur malbonajn notojn',
    'ankaŭ nun',
    'mi ne havas ilin',
    'mi havas bonan noton',
    'pri muziko',
    'bonan noton pri muziko',
    'la patrino subite ekridis',
    'tio plibeligis ~',
    'mian tagon',
    'plibeligis mian tagon',
    'sed tamen restis',
    'sed la problemo tamen restis',
    'kilogramo da ~',
    'kilogramo da sukero',
    'glaso da ~',
    'glaso da akvo',
    'multe da ~',
    'multe da ideoj',
    'deteni sin',
    'ordigis ĉion',
    'transdonis al li',
    'mi petas',
    'glason da kafo',
    'kaj iom da akvo',
    'mi petas glason da kafo',
    'mi petas tason da teo',
    'doloris lin',
    'la kapo doloris lin',
    'li malsaniĝis',
    'ŝatas esti bela',
    'ŝi beligis sian vizaĝon',
    'la knabo ŝatas esti bela',
    'pro tio ŝi beligis ĝin',
    'post la tagmanĝo',
    'purigi la kuirejon',
    'kiu purigos la kuirejon?',
    'volas trinki',
    'kion vi volas trinki?',
    'trinki teon',
    'iom da akvo',
    'ĉu vi volas nenion?',
    'tiel subite',
    'kial vi decidis ~ ?',
    'kial vi tiel subite decidis ~ ?',
    'via ĉambro',
    'via ĉambreto',
    'vian ĉambreton',
    'renovigi vian ĉambreton',
    'decidis renovigi vian ĉambreton',
    'al kiu',
    'vi donis ~',
    'al kiu vi donis ~ ?',
    'puraj glasoj',
    'vi donis la purajn glasojn',
    'la puraj glasoj por la vino',
    'kontraŭ kiu',
    'via sportklubo',
    'ludas kontraŭ ~',
    'antaŭ du semajnoj',
    'kontraŭ kiu via sportklubo ludis?',
    'ĉu vi vidas ~ ?',
    'ĉu vi ofte vidas ~ ?',
    'ofte vidas la policiston',
    'tiu, kiu loĝas en ~',
    'loĝas en la loĝejo',
    'la loĝejo super vi',
    'vidas la policiston, kiu loĝas en ~',
    'plano pri veturado',
    'volis vojaĝi',
    'vojaĝi al alia lando',
    'en libertempo',
    'ili decidis iri',
    'decidis iri al Italio',
    'malnovaj urboj',
    'lando kun malnovaj urboj',
    'aliaj belaĵoj',
    'kaj aliaj belaĵoj',
    'bela lando kun malnovaj urboj kaj aliaj belaĵoj',
    'ili estis feliĉaj',
    'kie estas ~ ?',
    'kie estas mia vestaĵo?',
    'ŝi demandis ~',
    'ni ne forgesu kunporti ~',
    'kunporti la libron',
    'libro por lerni Esperanton',
    'kunporti libron por lerni',
    'ni povas komenci ~',
    'en la vagonaro',
    'jam en la vagonaro',
    'ni nenion faros',
    'ni veturos per ~',
    'veturos per aŭto',
    'mi havas sekreton',
    'mia riĉa onklo',
    'mia deziro',
    'plenumis mian deziron',
    'donis al ni',
    'sian aŭton',
    'kaj donis al ni sian aŭton',
    'por uzo',
    'ĝi staras antaŭ ~',
    'staras antaŭ la domo',
    'mi devas diri ~',
    'nenion diru',
    'ni eksidu',
    'eksidu en la aŭton',
    'veturi al ~',
    'kaj veturu al Italio',
    'sidis en la aŭto',
    'ankaŭ la vestaĵoj',
    '~ estis en la aŭto',
    'ankoraŭ sidadis kaj atendis',
    'sed li atendis',
    'kial ni ne ~ ?',
    'kial ni ne ekveturas?',
    'ankaŭ mi havas ~',
    'veturigus la aŭton',
    'sed mi ne scias ~',
    'mi neniam lernis tion',
    'mi kredus ~',
    'se mi estus sana',
    'mi estus tre feliĉa',
    'kvazaŭ vi estus riĉulo',
    'vi sidas tie kvazaŭ vi estus riĉulo',
    'kvazaŭa lernejo',
    'kvazaŭ riĉulo',
    'vi sidas tie kvazaŭ riĉulo',
    'tiom da mono',
    'tiom da mono kiom da ideoj',
    'se mi havus tiom da mono',
    'mi vojaĝadus',
    'ĉirkaŭ la mondo',
    'en ĉiu vortaro',
    'mankas io',
    'mankas kelkaj vortoj',
    'homo, kiu longe parolis',
    'ĉe la manĝotablo',
    'homo, kiu rakontas, restos malsata',
    'rakontadas ĉe la manĝo tablo',
    'li devis atenti ~',
    'ne rajtis ~',
    'rajtis resti',
    'ne rajtis longe resti',
    'resti ekstere en pluvo',
    'tial li malvarmumis',
    'li havas sian klaran ideon',
    'sed li kredos ĉion',
    'ĉion, kion vi diros',
    'kvazaŭ vi estus lia edzino',
    'viaj gepatroj',
    'ĝojigi viajn gepatrojn',
    'kio povus ĝojigi ~ ?',
    'kio povus plej ĝojigi viajn gepatrojn?',
    'post la lernado',
    'almenaŭ post la lernado',
    'en la urbocentron',
    'se vi irus kun mi',
    'se vi irus kun mi en la urbocentron',
    'kien vi dezirus vojaĝi?',
    'se vi havus ~',
    'sufiĉe da mono',
    'se vi havus sufiĉe da mono kaj tempo',
    'ĉu vi planas ~ ?',
    'planas veturi al Parizo',
    'veturi per aŭto',
    'multe pli bone',
    'ŝajnas multe pli bone',
    'per vagonaro',
    'aŭ ĉu ne ŝajnas esti multe pli bone?',
    'diversaj homoj',
    'kial homoj klarigas diversmaniere?',
    'samaj ideoj',
    'klarigas samajn ideojn',
    'familianoj kunvenas',
    'kiel rapide',
    'tagoj pasas',
    'kiel rapide pasas tagoj!',
    'morgaŭ estos ~',
    'la naskiĝtago de via patro',
    'kelkaj familianoj',
    'alvenos kelkaj familianoj',
    'kaj geamikoj',
    'ĉu vi bonvolus ~ ?',
    'ĉu vi bonvolus iom helpi?',
    'iomete da tempo',
    'trovu iomete da tempo',
    'por ordigi vian ĉambron',
    'almenaŭ por ordigi vian ĉambron',
    'mi ŝatus ~',
    'mi ŝatus kuiri ion',
    'ion bonan',
    'kuiri ion bonan',
    'por la naskiĝitaga kuko',
    'mankas lakto',
    'en la hejmo',
    'necesas havigi ~',
    'iom da manĝaĵo',
    'el vendejo',
    'havigi iom da manĝaĵo el vedejo',
    'mi aĉetumos',
    'por la naskiĝtago',
    'anstataŭ sidi kaj manĝegi',
    'interesaj homoj',
    'kun neinteresaj familianoj',
    'mi ŝatus ekskursi',
    'kun klubanoj',
    'kun kiuj klubanoj?',
    'diris la patro',
    'ia papero, iaj paperoj',
    'en paperujo',
    'en paperujon',
    'ĵetis paperojn en paperujon',
    'ĵetis iajn paperojn en paperujon',
    'morgaŭ frue',
    'anoj de mia sporta klubo',
    'kara mia',
    'ĉu ĝuste ~ ?',
    'vi devas foresti',
    'ĉu vi ne ~ ?',
    'viaj samklubanoj',
    'intervidiĝas kun viaj samklubanoj',
    'trifoje semajne',
    'ĉu mi rajtas ~ ?',
    'rajtas ion proponi',
    'mi kunmanĝos kun la familianoj',
    'sed en la dua parto',
    'mi foriros kun miaj geamikoj',
    'parolos pri ~',
    'malsukcesa veturado',
    'certe parolos pri la malsukcesa veturado',
    'per aŭto',
    'post la kuko',
    'mi ne plu volas tion',
    'volas tion aŭdi',
    'kial ni ne havas ~ ?',
    'ideoriĉa onklo',
    'havas iun ideoriĉan onklon',
    'en mia familio',
    'la patrino ridetis',
    'je liaj vortoj',
    'ŝi scias, ke ~',
    'iom tro parolas',
    'ne sufiĉas nur ~',
    'riĉeco de la ideoj',
    'necesas ankaŭ ~',
    'plena monujo por realigi ĝin',
    'la patrino daŭrigis ~',
    'post iom da silento',
    'antaŭ kelkaj minutoj',
    'Ana telefonis, ke ŝi ~',
    'ankaŭ ŝi vizitos nin',
    'dolĉa kuko',
    'ŝi tre ŝatas dolĉan kukon',
    'atentas por ne dikiĝi',
    'kvankam ŝi atentos',
    'tuj ŝanĝis la opinion',
    'dum la ekskurso',
    'sen ŝi',
    'li estus tre soleca',
    'mi tamen pasigos',
    'mi tamen pasigos la morgaŭan tagon hejme',
    'en juneco',
    'oni havas',
    'havas ankaŭ belecon',
    'malsimplaj laboroj',
    'malsimplajn laborojn',
    'devus plisimpligi',
    'en tiu aĝo',
    'li jam fariĝis ~',
    'estro de la sporta klubo',
    'monon oni metas',
    'en monujon',
    'metas en monujon',
    'sekvu la ekzemplojn',
    'de la bonaj familianoj',
    'ĉu amikeco pli felĉigas?',
    'feliĉigas vin',
    'ol la amo',
    'kiel ofte vi ~ ?',
    'vi skribas leterojn al ~',
    'skrivas leteojn al viaj amikinoj',
    'viaj amikinoj en Italio',
    'la rilato inter vi kaj via instruisto',
    'ĉu la rilato ŝanĝiĝis?',
    'ĉu vi jam scias ~ ?',
    'sufiĉe bone',
    'estis vespero en ~',
    'centoj da homoj',
    'plenigas la placon',
    'junuloj kaj militistoj',
    'maristoj de sur la ŝipoj',
    'elstara sinjorino',
    'elstaraj sinjorinoj',
    'alilandaj vojaĝantoj',
    'ĉiuj moviĝas al urbomezo',
    'iom plue',
    'ne malproksime de la maro',
    'troviĝis malgranda placo',
    'iom plue sed ne malproksime',
    'fine de ĝi',
    'proksime de la maro',
    'proksime staris homo',
    'laŭ la vestaĵo',
    'oni facile scii ~',
    'oni povis ekscii, ke ~',
    'gondolisto de iu riĉulo',
    'povis ekscii, ke li estas gondolisto',
    'li rigardis ~',
    'rigaridis la ĝojan hommulton',
    'rideto lumigis lian vizaĝon',
    'kiam li ekvidis mariston',
    'la mariston, kiu alvenis',
    'la flanko de la maro',
    'alvenis el la flanko de la maro',
    'ĉu tio estas vi, Stefano?',
    'ekkriis la gondolisto',
    'ĉiuj diras, ke ~',
    'en la manojn de la Turkoj',
    'ke vi falis en la manojn de la Turkoj',
    'ni renkontis unu',
    'el niaj ŝipoj',
    'ĝi sekvis nin',
    'dum pli ol unu horo',
    'sed ne estas facile iri ~',
    'iri pli rapide ol nia ŝipo',
    'kiaj novaĵoj estas tie ĉi?',
    'tie ĉi en Venecio',
    'nenio interesa',
    'nur granda malfeliĉo',
    'ĉu vi konas Pietron?',
    'mi konas lin',
    'granda ŝipo subakvigis lian gondolon',
    'kaj kio pri li?',
    'la gondolo subakviĝis',
    'okazis, ke ~',
    'ni troviĝis proksime',
    'ni prenis lin en nian gondolon',
    'en la sama tempo',
    'mia estro subakviĝis',
    'por helpi junulinon',
    'junulinon, kiu preskaŭ mortis',
    'kun sia onklo',
    'preskaŭ mortis kun sia onklo',
    'tie estis junulino',
    'lin ni ne povis helpi',
    'estis grava homo',
    'kio alvenigis vin en Venecion?',
    'amiko mia',
    'la maristo ekrigardis',
    'rapide ekrigardis sian amikon',
    'kaj komencis diri',
    'do vi scias ~',
    'mi alportis ~',
    'la gondolisto subite haltigis lin',
    'li diris',
    'tiam iu homo pasis',
    'iu homo pasis apud li',
    'li ankoraŭ ne estis tridekjara',
    'kaj lia vizaĝo estis senkolora',
    'lia iro estis certa kaj facila',
    'lia vizaĝo estis malĝoja',
    'kiam li ekvidis la homon, ~',
    'oni diras, ke ~',
    'multaj gravuloj donas ~',
    'sekreta laboro',
    'sekretaj laboroj',
    'donas sekretajn laborojn al li',
    'tro da sekretoj',
    'li scias tro da sekretoj',
    'tial ili timas',
    'sendi lin en malliberejon',
    'diris la maristo',
    'kaj dum li parolis',
    'li montris la domegon',
    'la domego de Doĝoj',
    'multaj gravuloj bezonas lian helpon',
    'kiom ili pagas?',
    'pagas al li',
    'pagas por unu mortigo',
    'certe ne malpli ol ~',
    'ol cent moneroj',
    'ne forgesu, ke ~',
    'ke li laboras por tiuj',
    'por tiuj, kiuj havas sufiĉe da mono',
    'por pagi al li',
    'en Venecio estas ~',
    'tiuj aferoj',
    'forgesi tiujn aferojn',
    'aferoj, kiujn estas pli bone forgesi',
    'se vi volas trankvile manĝi',
    'trankvile manĝi vian panon',
    'estis iom da silento',
    'kaj poste',
    'la gondolisto denove ekparolis',
    'vi venis ĝustatempe',
    'por vidi ŝipkuron',
    'iu diris malforte',
    'proksime de la gondolisto',
    'la estro de la urbo',
    'senvorte montris al la gondolo',
    'diris la gondolisto',
    'kaj prenis la manon de sia amiko',
    'ĵetas la paperon',
    'en la paperujon',
    'la knabinoj ĵetis la paperojn',
    'kie estas mia skribilo?',
    'mi volas respondi al li',
    'la suno malaperis',
    'kaj nun estas preskaŭ malhele',
    'bonvolu manĝi',
    'bonvolu manĝi la panon',
    'per manĝiloj',
    'pardonu min',
    'rajtas resti',
    'mi ne rajtas resti',
    'ĉu vi povas kunporti ~ ?',
    'de mia fratino',
    'kiam vi aĉetis ~ ?',
    'aĉetis tiun muzikilon',
    'kiu laste uzis ?',
    'uzis mian ŝlosilon',
    'ĉu vi veturis?',
    'en Venecio',
    'ankaŭ per gondolo',
    'ĉu vi povos ekdormi?',
    'tiam, kiam silentiĝis',
    'la sinjoro estis alta',
    'alta, dika',
    'dika, peza',
    'peza kaj larĝa',
    'estis alta, dika, peza, kaj larĝa',
    'donis forton',
    'havinda forto',
    'havinda korpoforto',
    'tio donis',
    'donis al li',
    'tio donis forton',
    'donis havindan korpoforton',
    'lia aspekto',
    'grandula aspekto',
    'eta rolo',
    'ludis rolon',
    'ne eta rolo',
    'ludis etan rolon',
    'ludis ne etan rolon',
    'en la fakto, ke ~',
    'la plimulto el la homoj',
    'se ne timis',
    'lin timis',
    'se lin timis',
    'se ne lin timis',
    'certe respektis',
    'almenaŭ pripensis ~',
    'antaŭ ol ~',
    'kontentigi lin',
    'malkontentigi lin',
    'antaŭ ol malkontentigi ~',
    'antaŭ ol decidi ~',
    'decidi malkontentigi ~',
    'decidi kontentigi lin',
    'antaŭ ol decidi malkontentigi lin',
    'tio, kio estas utila',
    'ofte utila dumtage',
    'malplaĉa ĝeno',
    'per si',
    'prezentas malplaĉan ĝenon',
    'prezentas per si malplaĉan ĝenon',
    'en loko arboplena',
    'tiam, kiam oni devojiĝis',
    'en nehoma sovaĝejo',
    'kaj ekstervoje iraĉas',
    'alta larĝa korpo',
    'ne sukcesis pasi ~',
    'inter la arbetoj',
    'krome tuŝi la naturaĵojn',
    'ĝenerale malsekajn',
    'meze de malsekaj naturaĵoj',
    'malsekaj naturaĵoj, meze de kiuj ~',
    'li malfacile paŝis',
    'estis travivaĵo',
    'ne malofte',
    'doloriga kaj ĉiam malagrabla',
    'ju pli ~',
    'antaŭeniris en la vivo',
    'en la kastela arbaro',
    'ju pli antaŭeniris des pli malŝatis ~',
    'malŝatis la noktan naturon',
    'viro kun okuloj bone videblaj',
    'okuloj, kiuj kapablis bone vidi',
    'bone vidi en la mallumo',
    'rigardis la malfacilan iron',
    'de nia industriisto',
    'li ridetis',
    'apud tiu viro',
    'en vestaĵo de policano',
    'staris alia persono',
    'en simila vestaĵo',
    'ĉi lasta estis virino',
    'ni iru',
    'la viro diris mallaŭte',
    'en la orelon de sia kunulino',
    'nun estas la ĝusta momento',
    'ambaŭ paŝis direkte al la persono',
    'ili zorgis fari ~',
    'kiel eble plej ~',
    'kiel eble plej malmulte da bruo',
    'laŭeble plej malmulte da bruo',
    'ili preskaŭ plene sukcesis',
    'en ĉi tiu aĉa situacio',
    'aĉa situacio, kie arboj ĵetis siajn branĉojn',
    'ĵetis siajn malsekajn branĉojn',
    'rekte en la vizaĝojn',
    'de la industriisto',
    'multpiedaj bestetoj',
    'prenis liajn piedojn',
    'por promenejo',
    'naturo faligis lian piedon',
    'plej dolorige',
    'faligis lian piedon en kavon',
    'kavo plena de akvo',
    'akvo aĉ-odora',
    'rapide alvenis al la penso',
    'oni devas esti preta',
    'ĉi tie',
    'iu ajn ~',
    'preta por iu ajn malplaĉa renkonto',
    'ion ajn',
    'li atendis ion ajn',
    'krom homa voĉo',
    'kiam voĉo aŭdigis, ~',
    'aŭdiĝis tuj proksime',
    'li faris belan surlokan salton',
    'kiu movis lian koron',
    'supren ĝis la buŝo',
    'kun la provo rekapti trankvilon',
    'iom da trankvilo',
    'la lumo de lampeto',
    'oni direktis rekte al liaj okuloj',
    'la lampo, kiun oni direktis al okuloj',
    'malhelpis repaciĝon',
    'ŝajnis al li, ke ~',
    'la homformo, kiu tenis la lampon',
    'surhavas vestojn policajn',
    'kion vi faras ĉi tie?',
    'sonas la aŭtorita voĉo',
    'bonvolu paroli ~',
    'iom klare',
    'la alia diris',
    'eĉ pli grav-tone',
    'mi promenas',
    'vi promenas en la bieno',
    'de la grafino',
    'la bieno de la grafino',
    'meze de la nokto',
    'ĉu la grafino vin invitis?',
    'ĉu ŝi scias pri ~',
    'pri via ĉeesto',
    'via ĉeesto ĉi tie',
    'mi devas peti vin ~',
    'petas vin sekvi min',
    'kaj li klarigis ~',
    'klarigis, ke ~',
    'ekde la fuŝa provo',
    'la fuŝa provo kapti la grafinon',
    'fare de ~',
    'fare de teroristoj',
    'la polico kontrolas atente',
    'kontrolas, kio okazas',
    'okazas en la ĉirkaŭaĵo',
    'de la kastelo',
    'la ĉirkaŭaĵo de la kastelo',
    'al la industriisto',
    'ŝajnis, ke ~',
    'lia koro ĉifoje falis',
    'falis ĝis liaj piedoj',
    'li sciis, ke ~',
    'nur malfacile li provos trovi ~',
    'trovi akcepteblan klarigon',
    'pri sia ĉeesto',
    'la ideo, ke la grafino ĉion scias',
    'la ideo perdigis al li malmulton da espero',
    'malmulto da espero',
    'malmulta espero, kiu restis',
    'post la unuaj vortoj de la policano',
    'ju pli ~ des pli ~',
    'ju pli longe des pli bone',
    'kiom ajn',
    'antaŭ kvarona horo',
    'ili revenis',
    'post la terura malfeliĉo',
    'la homoj foriris',
    'kaj la malnovaj urboj disfalis',
    'ni devus revidi vin',
    'mia amiko',
    'ju pli ofte',
    'mi pripensas',
    'des pli mi koleras',
    'ŝi loĝas en ~',
    'en iu ajn domo',
    'ĉu ni revidos nin?',
    'kie ajn kaj kiam ajn',
    'kiam mi rericevos ~ ?',
    'la alian duonon de la libroj',
    'ĉu vi bezonos ~ ?',
    'bezonas pli ol kvaronan jaron',
    'por tiuj laboroj',
    'kial estas ~ ?',
    'des pli malvarma',
    'ju pli longe',
    'ni atendas ~',
    'ĉu vi kontentas kun ~ ?',
    'kun iu ajn viro',
];

