B_course = [
    'saluton!',
    'mi estas ~',
    'kiu vi estas?',
    'mia nomo estas ~',
    'mi ĝojas',
    'ankaŭ mi ĝojas',
    'ofte venas',
    'al tiu ĉi dancejo',
    'ĉu vi ofte venas al tiu ĉi dancejo?',
    'ne, ĉu vi?',
    'ankaŭ mi ne',
    '~ estas interesa nomo',
    'ĉu?',
    'ĉu ne?',
    'en kiu maniero?',
    'rilatas al ~',
    'ĝi rilatas al Esperanto',
    'kio?',
    'mi ne aŭdis bone',
    '~ estas tro laŭta',
    'la muziko estas tro laŭta',
    'mi diris, ke ~',
    'mi diris ke via nomo rilatas al Esperanto',
    'ĉu vere?',
    'novaĵo por mi',
    'tio estas novaĵo por mi',
    'ĉu vi aŭdis pri ~?',
    'ĉu vi aŭdis pri Esperanto?',
    'mi ne sciis, ke ~',
    'sed mi ne sciis ke mia nomo rilatas al ĝi',
    'fakte',
    'kia estas ~ ?',
    'kia estas la rilato?',
    'ho!',
    'tio estas longa rakonto',
    'rakontos al vi',
    'se vi volas',
    'mi rakontos al vi poste, se vi volas',
    'en ĉi tiu loko',
    'tro da bruo',
    'en ĉi tiu loko estas tro da bruo',
    'jes, vi pravas',
    'ĉu ni dancu?',
    'bona ideo!',
    'dankon por agrabla vespero',
    'dankon al vi',
    'estis vere bona',
    'muziko plaĉas al ~',
    'la muziko ege plaĉis al mi',
    'ankaŭ al mi',
    'danci estis tre amuze',
    'danci kun vi',
    'estis tre amuze danci kun vi',
    'jen mia nomkarto',
    'se vi volas ĝin',
    'jen mia karto, se vi volas',
    'sur ĝi estas ankaŭ ~',
    'sur ĝi estas ankaŭ adreso',
    'estas ankaŭ adreso al paĝaro',
    'adreso al paĝaro kun Esperanto-kurso',
    'dankon',
    'mi retpoŝtos al vi',
    'bone!',
    'ĝis kaj bonan nokton!',
    'ĝis la!',
    'aperas en ~',
    'tujmesaĝilo',
    '~ aperas en la tujmesaĝilo',
    'ĉu vi estas tiu?',
    'tiu, kiu dancis kun mi',
    'sabata nokto',
    'ĉu vi estas tiu, kiu dancis kun mi sabatnokte?',
    'jes, estas mi',
    'mi ĝojas, ke ~',
    'mi ĝojas, ke vi venis al la paĝaro',
    'ĉu ĝi plaĉas al vi?',
    'jes ja',
    'ĝi estas tre bela',
    'ŝajnas interesa',
    'ĝi estas tre bela kaj ŝajnas interesa',
    'ankoraŭ ne ~',
    'ne estas tute preta',
    'ĝi ankoraŭ ne estas tute preta',
    'sed baldaŭ estos',
    'mi komprenas',
    'sed jam estas multaj helpiloj',
    'vortaro',
    'superrigardo',
    'ekzerco',
    'ekzemple vortaroj, superrigardo, tujmesaĝilo kaj ekzercoj',
    'superrigardo de la gramatiko',
    'tujmesaĝilo kaj diversaj ekzercoj',
    'estas bona komenco',
    'pardonon',
    'mi devas paroli kun ~',
    'paroli kun alia persono',
    'pardonon, mi devas paroli kun alia persono',
    'lingvohelpanto',
    'mi estas ŝia "lingvohelpanto"',
    'kaj nun ŝi volas paroli pri ~',
    'paroli pri unu ekzerco',
    'baldaŭ revenos',
    'mi baldaŭ revenos al vi',
    'post kelkaj minutoj',
    'finparolis',
    'nun ni finparolis pri la ekzerco',
    'dume',
    'mi legis pri Esperanto dume',
    'mi ne certas',
    'scias sufiĉe pri ~',
    'mi ankoraŭ ne scias sufiĉe pri la lingvo',
    'saĝa respondo',
    'mi rigardos en la paĝaro',
    'kaj provos iom lerni',
    'ĉu vi volas esti mia "lingvohelpanto"?',
    'volonte!',
    'nedankinde!',
    'nedankinde, sed kisinde',
    'diras tion en Esperanto',
    'kio? mi ne komprenas',
    'vi povas rigardi en la vortaro',
    'bedaŭrinde',
    'mi devas foriri de Interreto nun',
    'mi revenos vespere',
    'mi pensas, ke mi estos ĉe la paĝaro tiam',
    'perfekte!',
    'do, ĝis tiam!',
    'ĝis poste!',
    'vespere, ankaŭ ĉe la tujmesaĝilo',
    'resaluton!',
    'saluton denove!',
    'mi rigardis preskaŭ ĉiujn paĝojn de la paĝaro',
    'bonege!',
    'mi havas kelkajn demandojn',
    'ĉu vi havas tempon?',
    'jes, mi havas liberan vesperon',
    'do, skribu viajn demandojn',
    'mi provos respondi',
    'mi legis ke Esperanto havas kulturon',
    'tamen mi ne komprenas ~',
    'kie mi povas trovi tiun kulturon',
    'vi trovos ĝin ĉie, kie estas ~',
    'ĉie, kie estas homoj, kiuj parolas Esperanton',
    'sed neniu popolo uzas Esperanton',
    'prave',
    'sed homoj, kiuj parolas Esperanton',
    'ofte vojaĝas kaj renkontas aliajn Esperantistojn',
    'dum tiuj renkontoj',
    'ili uzas la lingvon en plej diversaj situacioj',
    'do, tie vi trovos ~',
    'vi trovos la kulturon',
    'trovos la kulturon de Esperanto',
    'bone ĉu ekzistas muziko?',
    'muziko, literaturo, teatraĵo',
    'k.t.p.',
    'same kiel ~',
    'same kiel estas por aliaj lingvoj',
    'la kvanto ne estas same granda',
    'same granda kiel en naciaj lingvoj',
    'sed tio ne gravas',
    'almenaŭ ne por mi',
    'se vi volas aŭskulti ~',
    'aŭskulti kanton en Esperanto',
    'jen la kanto, "Liza pentras bildojn"',
    'aŭskultas la kanton',
    'ne malbone',
    'kaj vi trovos multajn librojn en Esperanto',
    'rigardas la librojn',
    'sufiĉe multaj',
    'ĉu vi legas multe en Esperanto?',
    'jes, de tempo al tempo',
    'se vi iam lernos la lingvon',
    'mi rekomendos al vi kelkajn bonajn librojn',
    'temas pri ~',
    'mia alia demando temas pri mia nomo',
    'vi diris antaŭe ke ~',
    'havas rilaton al ~',
    'diris ke ĝi havas rilaton al Esperanto',
    'ha, jes, pri tio',
    'viro kun la nomo ~',
    'iam vivis viro kun la nomo ~',
    'li estis tre aktiva en la Esperanto-movado',
    'kiam ĝi estis tute nova',
    'tradukis la libron al ~',
    'kaj tradukis multajn librojn al Esperanto',
    'kaj tio faris lin fama?',
    'unu el la plej gravaj por Esperanto tiam',
    'kaj li multe influis la stilon de la lingvo',
    'ne, certe li estis grava kaj influis multe',
    'tamen, li subite forlasis la movadon',
    'mi imagas ke ~',
    'mi imagas ke estis granda ŝoko por multaj',
    'kial li forlasis Esperanton?',
    'mi kredas ke ~',
    'li estis malkontenta pri la Esperantistoj',
    'li diris ion similan al ~',
    'Esperanton devas lerni la Esperantistoj mem!',
    'kion li volis diri per ~ ?',
    'kion li volis diri per tio?',
    'verŝajne ke ~',
    'homoj malbone parolis Esperanton',
    'verŝajne ke homoj tiam malbone parolis',
    'en la jaro 1911, li forlasis Esperanton',
    'sed mi pensas ke ~',
    'estas pli alta',
    'hodiaŭ la lingvonivelo estas pli alta',
    'la lingvonivelo de la Esperantistoj',
    'sed mi pensas ke hodiaŭ la nivelo estas pli alta',
    'do mi devas bone lerni la lingvon',
    'por esti bona homo',
    'kaj vi devas uzi simplan stilon',
    'ĉar tio estis tre grava por li',
    'tio plaĉas al mi',
    'en Esperanto eĉ ekzistas vorto ~',
    'eĉ ekzistas vorto "kabei"',
    'forlasi la movadon',
    'vorto "kabei", kiu signifas forlasi la movadon',
    'interese!',
    'mi nun scias unu vorton en Esperanto',
    'neniam forgesos',
    'kaj verŝajne mi neniam forgesos ĝin',
    'en kafejo, post pluraj semajnoj',
    'li sukcesis lerni Esperanton',
    'kaj ili nun uzas la lingvon',
    'inviti, invitilo',
    'jen, rigardu, invitilo por IJK!',
    'kio? I-J-kio?',
    'junulo, junularo',
    'I-J-K estas "Internacia Junulara Kongreso"',
    'mi planas iri al ĝi',
    'ĉu ankaŭ vi volas iri?',
    'nu, "kongreso" ne sonas tre interese',
    'sed estas (interese)!',
    'ne pensu pri iu teda malvigla kongreso',
    'simple temas pri ~',
    'simple temas pri renkonto kun junuloj',
    'renkonto kun junuloj de multaj landoj',
    '300 ĝis 400 homoj estos tie',
    'verŝajne estos 300 ĝis 400 homoj tie',
    'preskaŭ ĉiuj',
    'kaj preskaŭ ĉiuj parolos Esperanton',
    'ne bone parolas',
    'bone, sed mi ne bone parolas Esperanton',
    'ne gravas',
    'eblas partopreni en ~',
    'partopreni en Esperanto-kursoj tie',
    'kutime',
    'kutime estas du niveloj',
    'homoj, kiuj jam eklernis la lingvon',
    'unu por komencantoj',
    'kaj alia por homoj kiuj jam eklernis la lingvon',
    'jes, kio?',
    'vi diris, "kutime"',
    'ha, IJK okazas ĉiu-jare',
    'ĉiu-foje en alia lando',
    'pro tio, ĉiu IJK estas alispeca',
    'sed ankaŭ estas programeroj',
    'programeroj, kiuj ofte revenas',
    'sed ankaŭ estas programeroj, kiuj ofte revenas',
    'ekzemple',
    'ekzemple, preskaŭ ĉiam eblas sportumi, kart-ludi',
    'babili kun amikoj dum la tuta nokto',
    'kanti ĉirkaŭ fajro kaj danci',
    'partopreni koncertojn, ktp',
    'nu, tion mi povas fari ankaŭ hejme',
    'prave, sed',
    'sed la grava afero dum IJK estas ~',
    'venas de multaj diversaj landoj',
    'estas ke la partoprenantoj venas de diversaj landoj',
    'pro tiu mikso de diversaj homoj',
    'estas bona etoso, kiu tre plaĉas al mi',
    'bone sonas interese',
    'mi pripensos',
    'certe',
    'tamen, problemo estas ~',
    'tiom da mono',
    'mi ne havas tiom da mono nun',
    'problemo estas ke mi ne havas tiom da mono',
    'mi komprenas, sed ne estus multe-koste',
    'ne estus multe-koste, mia-krede',
    'tabelo de kotizo de programeroj',
    'jen, se vi rigardas la kotiztabelon',
    'la kotiztabelo de la IJK-invitilo',
    'vi vidas, ke ~',
    'temas pri entute nur 50 eŭroj',
    'vi vidas, ke por vi temas pri entute nur 50 eŭroj',
    'se ni dormas surplanke',
    'en ordo',
    'bone, tio sonas en ordo',
    'sed kio pri la vojaĝo',
    'trajno kostus ĉirkaŭ 70 eŭrojn',
    'ĉu tio eblus por vi?',
    'espereble',
    'sed daŭrus sufiĉe longe per trajno',
    'jes, sed ni povas halti en unu aŭ du urboj',
    'dum la vojo',
    'kaj la tranoktado?',
    'ĉu vi pagus por ĝi?',
    'ne, ne mi, sed ne estas problemo',
    'ĉu vere, ke tio ne estas problemo?',
    'kiel vi planas solvi tion?',
    'montris la oran kronon',
    'nu, mi baldaŭ montros al vi',
    'sed unue pli da teo',
    'ĉu ankaŭ vi volas?',
    'jes, dankon',
    'en la sama kafejo',
    'io daŭras, daŭrigas tion',
    'plano, plani, planado',
    'ŝi kaj li daŭrigas la planadon',
    'bonvolu, jen via teo',
    'mi dume rigardis la invitilon',
    'rigardis la invitilon por IJK',
    'mi multon komprenas, sed ne ĉion',
    'bone bone, nur demandu',
    'jen la aferoj',
    'klaraj aferoj',
    'la aferoj kiuj estas malklaraj',
    'estas malklaraj por mi',
    'aliĝi, aliĝilo',
    'TEJO (la organizo)',
    'Pepo (la TEJO-birdo)',
    'loĝi, loĝejo',
    'amasloĝejo',
    'aliĝilo estas ilo por al-iĝi',
    'aliĝilo en kiu vi skribas vian nomon, adreson ktp',
    'longa, mallongigo',
    'mallongigo de Tutmonda Esperantista Junulara Organizo',
    'Pepo estas la amuza birdo de TEJO',
    'amasloĝejo estas ejo kie amaso de homoj loĝas',
    'dormo, dormigilo, dormosako',
    'kutime oni bezonas dormosakon tie',
    'vi klarigis tro rapide',
    'mi ne kaptis ĉion',
    'ne tre gravas',
    'mi pensas ke ne tre gravas nun',
    'poste ni povas pli paroli',
    'pli paroli pri la IJK-invitilo',
    'do, vi volas plani la vojaĝon nun, ĉu?',
    'jes, volonte',
    'tiel vi vidos ke ~',
    'kostos tiom multe',
    'vidos ke la vojaĝo ne kostos tiom multe',
    'mi volas scii',
    'mi scivolas pri ~',
    'kiel vi solvos la tranoktadon',
    'ĉar mi ne havas monon',
    'junulara gastejo',
    'havas monon por hotelo aŭ junulargastejo',
    'jen la solvo!',
    'pasporto',
    'Pasporta Servo',
    'libreto kun la nomo "Pasporta Servo"',
    'servo por kio?',
    'por homoj kiel ni',
    'sperti, spertulo',
    'homoj kiuj ŝatas vojaĝi kaj sperti landojn',
    'enspezi kaj elspezi',
    'sen elspezi multe da mono',
    'servo, la servo, tiu servo',
    'bone, kaj kiel funkcias tiu servo?',
    'mi vidas ke en la libreto estas ~',
    'multe da adresoj',
    'estas multe da adresoj de pluraj landoj',
    'ĝuste!',
    'je via dispono',
    'ili ĉiuj',
    'fakte ili ĉiuj estas je via dispono!',
    'signifis, signifo',
    '"je mia dispono", kion signifas tio?',
    'signifas ke ~',
    'gasti, gasto, gastigi',
    'estas preta, pretas, pretiĝu!',
    'homoj ĉe tiuj adresoj pretas gastigi vin',
    'koni, konata, konatiĝi',
    'kaj helpi vin konatiĝi kun ilia regiono',
    'signifas ke homoj pretas gastigi vin kaj helpi',
    'sonas interese!',
    'do',
    'oni loĝas en la hejmo de aliaj Esperantistoj, ĉu?',
    'prave!',
    'pluraj spertoj per Pasporta Servo',
    'mi havis plurajn interesajn spertojn',
    'mi uzis ĝin en tri kontinentoj',
    'malbone funkcias',
    'kaj ĝis nun funkciis tre bone',
    'bonege! kien ni iru?',
    'do, mia plano estas ke ni ~',
    'venas, alvenis',
    'post sukcesa vojaĝo',
    'post uzado de Pasporta Servo en du urboj',
    'ili alvenas post sukcesa vojaĝo',
    'jen, vidu!',
    'tie estas granda Esperanto-flago',
    'ŝildo kun la teksto "Bonvenon al IJK!"',
    'jes, kaj sub ĝi estas ~',
    'hu ra!',
    'ni do finfine alvenis',
    'mi estas tre laca kaj malsata',
    'ĉu vi pensas ke ni povas ~',
    'manĝi ion',
    'ĉu vi pensas ke ni povas tuj ion manĝi?',
    'mi dubas pri tio',
    'unue ni devas akceptiĝi',
    'devas akceptiĝi ĉe la akceptejo',
    'kaj tio povas daŭri longe',
    'daŭri longe miasperte',
    'ho ve!',
    'ĉu tio estas la vico por la akceptejo?',
    'mi timas ke jes',
    'ne estas tute perfekte fari ~',
    'tute perfekte alveni vespere',
    'ni povas babili kun homoj',
    'sed ni povas babili kun homoj en la vico',
    'jen, mi vidas amikon de rusio!',
    'mi estas malsata, mi volas manĝi',
    'post ĉirkaŭ 2 horoj',
    'en la vico kun novaj kaj malnovaj amikoj',
    'LKK (Loka Kongresa Komitato)',
    'LKK-ano',
    'bonvenon, kiu vi estas?',
    'de kiu lando?',
    'ĉu vi antaŭpagis?',
    'bonvolu montri',
    'se jes, bonvolu montri la kvitancon',
    'ĉu vi estas TEJO-membro?',
    'membriĝi ĉe la budo',
    'se ne, vi povas membriĝi ĉe la venonta budo',
    'jen kvitancoj de antaŭpagoj',
    'membrokartoj kaj niaj pasportoj',
    'tre bone',
    'do, mi vidas ke vi loĝos en amasloĝejo',
    'kaj manĝos en la junulargastejo',
    'ĉu ĝustas tiuj informoj?',
    'jes, perfekte',
    'sako kun programo, mapo ktp',
    'vi povas pagi kaj ricevi sakon kun programo, mapo ktp',
    'ĉe la ruĝa budo, tie',
    'bone, dankon',
    'aspektas laca sed sana',
    'tiuj personoj vere aspektis lacaj',
    'kaj ne estis tre afablaj',
    'vi pravas',
    'sed memoru ke ~',
    'laboras dum ok horoj',
    'la LKK laboras jam dum eble ok horoj',
    'sen multe da paŭzoj',
    'sed memoru ke la LKK laboras sen paŭzoj',
    'babilema dum la semajno',
    'mi certas ke ~',
    'mi certas ke ili estos pli afablaj',
    'ili estos pli afablaj kaj babilemaj',
    'ni trovu ĝin',
    'bone nun ni trovu la amasloĝejon',
    'kaj poste mi ŝatus ion manĝi',
    'ĉu vi vidis la knabinon ĉe la TEJO-budo?',
    'jes, kio pri ŝi?',
    'ĉu vi konas ŝin?',
    'bedaŭrinde ne',
    'sed ŝi estas ege bela, ĉu ne?',
    'mi konsentas',
    'tamen ne bone komprenas',
    'mi konsentas tamen ne komprenas',
    'ĉu al vi plaĉas inoj?',
    'jes, mi volis diri al vi antaŭe',
    'sed ial ne faris',
    'virinoj plaĉas al mi pli ol viroj',
    'aspekte ktp',
    'ĉu, ĉu vi estas ?',
    'jes, mi estas samseksemulo',
    'oni ankaŭ povas diri lesbo',
    'bone, mi tute ne sciis',
    'sed mi ĝojas ke vi diris',
    'fakte mi ankaŭ ĝojas ke vi estas samseksemulo',
    'vi estas la plej afabla kaj agrabla lesbo',
    'la plej agrabla lesbo kiun mi konas',
    'dankon! ĉu vi konas aliajn?',
    'sed kiel vi scias tion?',
    'tiu knabino preferas virojn!',
    'ĉiukaze mi kredas ke tiu knabino preferas virojn!',
    'tiu knabino pri kiu vi parolis',
    'ni vidos',
    'en la amasloĝejo',
    'bonan matenon!',
    'ĉu vi bone dormis?',
    'apenaŭ vidas',
    'male, mi apenaŭ dormis',
    'sed kial?',
    'eble vi estis nervoza pri via unua IJK-tago?',
    'ne vere',
    'la tutan nokton, dum la tuta nokto',
    'tre laŭte ronkis',
    'simple iu tre laŭte ronkis la tutan nokton',
    'ne ĝenu min',
    'kaj tio ege ĝenis min',
    'ĉu vi ne aŭdis tion?',
    'tute ne, mi profunde dormis',
    'ĉu mi forgesis diri al vi ke ~?',
    'orelo, ŝtopi, orelŝtopiloj',
    'indas uzi orelŝtopilojn',
    'indas uzi ~',
    'diris al vi ke indas uzi orelŝtopilojn',
    'kiam vi dormas en amasloĝejo',
    'evidente jes',
    'ho, kompatinda Kaĉjo!',
    'pri kiu vi parolas?',
    'pri vi',
    'karesi, karesa nomo, karesnomo',
    'per -ĉj- eblas krei karesnomojn en Esperanto',
    'ha, jes, mi iam legis pri tio',
    'kaj vi do estus Injo?',
    'se vi volas iri tien',
    'kioma horo estas nun?',
    'jam estas kvin minutoj antaŭ la deka',
    'kvin minutoj antaŭ la deka, aŭ naŭa kvindek kvin',
    'trafis aŭ maltrafis?',
    'vi maltrafis la matenmanĝon',
    'o, fek!',
    'ĉu vi estas sata?',
    'kaj mi kiu estas ege malsata',
    'se vi hastos',
    'povas almenaŭ trafi la malfermon',
    'la malfermo de la kongreso',
    'vi povas almenaŭ trafi la malfermon de la kongreso',
    'kiam ĝi estos?',
    'je kvarono post la deka',
    'ĝi daŭros horon',
    'kaj je la dek dua eblos manĝi',
    'bele mi antaŭĝojas',
    'diru, kio okazas dum la malfermo?',
    'ĉu ĝi estas vizitinda entute?',
    'laŭ mi jes',
    'kutime ĝi ne estas tre vigla',
    'sed por vi, kiel "novulo"',
    'povus esti interese ĉeesti ĝin',
    'mi supozas ke ~',
    'la prezidanto de TEJO diros kelkajn vortojn',
    'la temon de la kongreso',
    'ŝajnas, verŝajne',
    'iu de LKK verŝajne prezentos la temon de la kongreso',
    'ĉiu IJK havas sian temon',
    'mi esperas ke estos iom da muziko ankaŭ',
    'bone, kie ĝi okazos?',
    'en la granda prelegejo',
    'kiel trovi tiun?',
    'kiam vi eliras tiun ĉi ejon',
    'iru dekstren ĝis la fino de la konstruaĵo',
    'dum eble 100 metroj',
    'dekstren denove, rekten dum eble 100 metroj',
    'kaj estas flava domo',
    'je la maldekstra flanko de la vojo',
    'ŝildoj pri ĉiuj ejoj de IJK',
    'en ĝi, vi trovos ŝildojn pri ĉiuj ejoj de IJK',
    'mi sendos mesaĝon per poŝtelefono',
    'se mi ne trovos',
    'ha, bona ideo ĝis tie!',
    'en la prelegejo',
    'gardanĝeloj? ĉu vi ŝercas?',
    'prezidanto de TEJO',
    'fine mi deziras al vi ĉiuj amuzan semajnon',
    'laŭ la lastaj informoj',
    'ni estas 423 ĉi tie de 38 landoj',
    'mi deziras fruktodonan kaj amuzegan IJK-semajnon',
    'koran bonvenon nome de la TEJO-estraro',
    'post granda aplaŭdo',
    'ĉu vi sukcesis resti veka?',
    'jes, ĉefe pro mia malsato',
    'ne, mi ŝercas, estis interese aŭdi',
    'estis interese aŭdi iom pri la agado',
    'aŭdi pri la agado kaj strukturo de la movado',
    'TEJO-kunsido interesos vin',
    'eble iu el la TEJO-kunsidoj povas interesi vin',
    'jes eble',
    'mi provos',
    'provos ĉeesti',
    'mi provos ĉeesti',
    'ĉeesti unu',
    'ĉeesti por vidi',
    'iun tagon',
    'mi provos iun tagon',
    'iun tagon ĉeesti',
    'ĉeesti iun tagon por vidi',
    'mi provos iun tagon ĉeesti unu por vidi',
    'kio estas tio?',
    'kio estas tio pri ~',
    'gard-anĝelo',
    'tio pri "gardanĝelo"',
    'sed kio estas',
    'sed kio estas tio pri "gardanĝelo"?',
    'ĉu ŝerco?',
    'ĉu malbona ŝerco?',
    'malbona ŝerco',
    'iu ŝerco',
    'iu malbona ŝerco',
    'ĉu iu malbona ŝerco?',
    'mi ŝercas',
    'ne, mi ŝercas',
    'estis interese aŭdi',
    'kiel kontakti ~',
    'kaj kiel kontakti tiujn anĝelojn?',
    'per iu IJK-preĝo eble',
    'provu! se ne funkcias vi povas iri al ~',
    'vi povas iri al la ĉambro "La ĉielo" post la tagmanĝo',
    'bonege, unue manĝo, poste ĉielen',
    'unue manĝo, poste ĉielen al la anĝelinoj',
    'maltro da manĝo',
    'post iom maltro da manĝo',
    'Kabe iras al la ĉambro "La ĉielo"',
    'saluton. ĉu estas via unua IJK?',
    'bone. mi tre ĝojas. mi estas Jesi',
    'kaj tiu ĉi estas jam mia sesa IJK',
    'jen estas papero kun kelkaj demandoj',
    'papero kun demandoj kaj taskoj',
    'kelkaj demandoj kaj taskoj rilate al la kongreso',
    'vi provu solvi ilin',
    'mi proponas ke vi provu solvi ilin',
    'kun Ana de Pollando, Boris de Germanio kaj Nacuko de Japanio',
    'nur voku min se vi bezonos helpon',
    'poste en la libroservo',
    'kiel do estis en la ĉielo?',
    'mi fakte renkontis veran anĝelinon!',
    'ĉielece, mi pensas ke mi fakte renkontis veran anĝelinon!',
    'mirinde bela kaj afabla ŝi estis',
    'ho, Dio mia! kaj kio estas ŝia nomo?',
    'aj, mi jam forgesis!',
    'pli kaj pli ebriiĝas',
    'en la trinkejo, Kabe pli kaj pli ebriiĝas',
    'ĉu ankaŭ la trinkejestro?',
    'unu bieron mi petas',
    'ĝi kostas 1 eŭron',
    'ĉu vi ŝatus ankaŭ ion alian?',
    'ne dankon, biero sufiĉas por mi',
    'ĉu vere? kio pri vodko, labambo kaj inoj?',
    'nu, kial ne',
    'laŭdire ĝi estas amuza',
    'mi ankoraŭ ne dancis labambon, sed laŭdire ĝi estas amuza',
    'dum la kantaĵo "La Bamba" homoj dancas',
    'homoj dancas en granda rondo',
    'kaj ene de tiu rondo dancas aliaj homoj',
    'funkcias tiel ke ~',
    'funkcias tiel ke homoj dancas en granda rondo',
    'dancas en granda rondo kaj ene de tiu rondo',
    'homoj dancas kaj dancas aliaj homoj',
    'tiuj dancantaj ene de la rondo',
    'tiuj dancantoj elektas dancanton de la rondo',
    'elektas dancanton kaj kisas ŝin aŭ lin',
    'kisas ŝin aŭ lin tri-foje sur la vangoj',
    'elektas dancanton kaj kisas sur la vangoj',
    'elektas dancanton de la rondo kaj kisas',
    'poste ili ŝanĝas lokon',
    'kisas, kisanto, kisito, kisonto, kisoto',
    'kaj la kisito iĝas kisonto',
    'tiuj dancantoj elektas kaj poste ili ŝanĝas lokon',
    'la kisinto nun estas kisoto',
    'tre facile, ĉu ne?',
    'nu, mi esperas ke estas ~',
    'pli facile en la praktiko',
    'esperas ke estas pli facile',
    'estas pli facile en la praktiko',
    'mi provos iam',
    'sed unue la bieron!',
    'mi provos iam, sed unue la bieron!',
    'saĝa knabo',
    'vi, kiu konas preskaŭ ĉiujn',
    'konas preskaŭ ĉiujn ĉi tie',
    'ĉu vi scias kiu estas la knabino',
    'la knabino kiu kunordigis',
    'la knabino kiu kunordigis la ’gardanĝelojn’',
    'vi verŝajne pensas pri Jesi',
    'jes, ĝuste!',
    'mi memoras ke mi aŭdis',
    'nun mi memoras ke ~',
    'memoras ke mi aŭdis ŝian nomon',
    'laŭ mi',
    'ŝi estas stranga persono',
    'laŭ mi ŝi estas stranga persono',
    'tute ne trinkas bieron',
    'kaj ne manĝas viandon',
    'ŝajnas ke ~',
    'ŝia sola intereso estas ~',
    'sola intereso estas Esperanto-agado',
    'ŝajnas ke ŝia sola intereso estas Esperanto',
    'sed ŝi estas tre bela',
    'estas tre bela kaj afabla',
    'tre bela kaj afabla laŭ mi',
    'eble vi pravas',
    'eble vi pravas pri tio',
    'preskaŭ neniam estas en la trinkejo',
    'ŝi preskaŭ neniam estas ~',
    'ne renkontas ŝin ofte',
    'mi ne renkontas ofte',
    'kaj do mi ne renkontas ŝin ofte',
    'fajfas pri tiaj homoj',
    'fakte, mi tute fajfas',
    'mi komprenas ~',
    'tiel parolas vera trinkejestro',
    'prave. je via sano!',
    'je via sano! ho, bonega biero',
    'kompreneble. estis ja mi kiu elektis ĝin',
    'ĉu vi havas ideon?',
    'kie eblus trovi tiun strangan knabinon?',
    'trovi tiun strangan sed tre belan knabinon',
    'ideo kie eblus trovi ~',
    'havas ideon kie eblus trovi ~',
    'tutcerte en la Gufujo',
    'tiaj homoj konstante sidas',
    'konstante sidas tie teumante',
    'kia teda vivo!',
    'Gufujo, estas trankvila ejo',
    'trankvila ejo kie eblas trinki teon',
    'trinki teon, babili, aŭskulti trankvilan muzikon',
    'aŭskulti trankvilan muzikon kaj simile',
    'vi trovos ĝin fine de la koridoro',
    'fine de la koridoro ekster la trinkejo',
    'vi ne povas porti vian bieron',
    'porti vian bieron tien',
    'sed vi ne povas porti vian bieron tien',
    'vere estas ujo de gufoj!',
    'al la dancejo unue',
    'eble mi iru unue',
    'mi iru al la dancejo unue',
    'la venonta persono!',
    'kion vi volas kara?',
    'ĉu estas libera loko?',
    'jes, certe',
    'tre agrable ĉi tie',
    'ĉi tie en la gufujo',
    'mi bezonas iom da trankvilo',
    'post tre streĉa tago',
    'trankvilo post streĉa tago',
    'la etoso en gufujo',
    '~ estas tre bona kontrasto',
    'kontrasto al la aliaj okazaĵoj',
    'la aliaj okazaĵoj dum IJK',
    'la etoso estas kontrasto al la aliaj okazaĵoj',
    'estas tre bona kontrasto, ĉu ne?',
    'jes, mallaŭta muziko',
    'mallaŭta muziko, trankvila babilado',
    'trankvila babilado kaj iu interesa teo',
    'perfekte por rehavi fortojn',
    'vi ŝajnas ege laca',
    'kion vi faris dum la tuta tago?',
    'unue mi faris afiŝon',
    'afiŝo por la morgaŭaj ekskursoj',
    'mi faris afiŝon por ekskursoj',
    'cetere, ĉu vi iros?',
    'iros al ekskurso',
    'ĉu vi iros al iu ekskurso?',
    'jes, al la granda akvofalo',
    'kaj poste al ekspozicio',
    'ekspozicio pri moderna arto',
    'al akvofalo kaj poste al ekspozicio',
    'bona elekto',
    'ankaŭ mi iros tien',
    'ĉiukaze, mi gvidis diskutrondon',
    'pendigi afiŝojn',
    'post la pendigado de la ekskursafiŝoj',
    'diskutrondo kun la titolo "feminismo"',
    'gvidis diskuton kun la titolo "feminismo"',
    'ĉu feminismo samas en diversaj landoj?',
    'interesa kaj vigla diskuto',
    'estis tre interesa kaj vigla',
    'dum la lastaj kvin horoj',
    'mi estis en longa kunsido',
    'dum lastaj horoj mi estis en komitatkunsido',
    'en longa komitatkunsido',
    'vere estis tro longa',
    'la komitato finkunsidis',
    'sed nun la komitato finis kunsidon',
    'vere estis longa, sed nun finiĝis',
    'ha, vi do estas komitatano?',
    'la estraro de TEJO',
    'mi ankaŭ estas en la estraro',
    'jes, mi ankaŭ estas ~',
    'ankaŭ estas en la estraro de TEJO',
    'jes, kaj mi estas ~',
    'mi neniam estis aktiva',
    'tre aktiva en la movado',
    'neniam estis aktiva en la movado',
    'la ĉefa agado de TEJO',
    'kio estas la ĉefa agado nun?',
    'fakte kio estas la ĉefa agado?',
    'ĝi estas vasta',
    'plej diversaj kampoj',
    'en diversaj kampoj ni havas agadon',
    'seminarioj pri homaj rajtoj',
    'homaj rajtoj kaj interkulturaj rilatoj',
    'biciklo, karavano, festivalo',
    'ekzemple seminarioj, biciklokaravanoj kaj festivaloj',
    'lingvaj festivaloj, konstruado de ttt-paĝoj',
    'ekzemple biciklokaravanoj, festivaloj ktp',
    'seminario pri rajtoj kaj rilatoj',
    'karavano, festivalo, konstruado ktp',
    'oficialaj instancoj kiel UNESKO',
    'reprezentitaj en oficialaj instancoj',
    'ni ankaŭ estas reprezentitaj',
    'estas reprezentita en diversaj instancoj',
    'instancoj kiel Forumo Junulara Eŭropa, UNESKO',
    'la junulara sekcio de Unuiĝintaj Nacioj',
    'diversaj instancoj kiel UNESKO kaj la junulara sekcio de UN',
    'UNESKO kaj la junulara sekcio de Unuiĝintaj Nacioj',
    'Forumo Junulara Eŭropa kaj la junulara sekcio de UN',
    'sonas interese',
    'folio, foliumi, vento, ventumi, esperanto, esperantumi',
    'por mi sufiĉas esperantumi',
    'esperantumi unu aŭ du semajnojn',
    'unu aŭ du semajnojn jare',
    'tamen por mi sufiĉas',
    'jes, oni trovu ~',
    'trovi ekvilibron',
    'oni trovu sian ekvilibron',
    'mi sentas ke estas tro',
    'ĝuste nun mi sentas',
    'mi sentas ke ~',
    'sentas ke estas tro da ~',
    'tro da Esperanto en mia vivo',
    'estas tro da Esperanto en mia vivo',
    'ĉu vi estas membro?',
    'ĉu vi estas membro de organizo?',
    'membro de iu alia organizo',
    'ne vere organizo, sed ~',
    'sed mi ludas gitaron',
    'ludas gitaron en bando',
    'bele! mi tre ŝatas',
    'mi ŝatas kanti',
    'tre ŝatas kanti',
    'kian muzikon vi ludas?',
    'nu, estas simpla popo',
    'ni ĵus fondis la bandon',
    'sed eventuale ni ludos',
    'ni ludis dum la IJK',
    'ludos dum la venonta IJK',
    'mi jam antaŭĝojas!',
    'nur diru se vi bezonas ~',
    'bezonas iun helpkantiston',
    'se vi bezonas helpkantiston',
    'kial ne? eble vi volas ~',
    'vi volas kanti ion nun',
    'mi povas ludi gitaron',
    'vi volas kanti kaj mi povas ludi',
    'kanti ion nun kaj ludi gitaron',
    'jes, mi ŝatus tion',
    'venigi mian gitaron',
    'tuj venigos mian gitaron',
    'tre bone, mi venigos gitaron',
    'mi tuj venigos mian gitaron',
    'atendas vian revenon',
    'via espereble rapida reveno',
    'mi atendas rapidan revenon',
    'atendas vian espereble rapidan revenon',
    'du tagojn poste',
    'ekster la dancejo',
    'tagojn poste, ekster la dancejo',
    'ej Kabe, vi aspektas ~',
    'vi aspektas feliĉega',
    'jes, mi estas ~',
    'bele, mi ĝojas!',
    'kongreso plaĉas al vi?',
    'ĉu la kongreso tiom plaĉas al vi?',
    'jes kaj ne',
    'certe mi tre kontentas',
    'tre kontentas pri IJK',
    'sed estas io alia',
    'io alia, kio feliĉigas min',
    'estas io kio feliĉigas ~',
    'pli ĝuste dirite',
    'estas iu, kiu batigas ~',
    'iu kiu batigas mian koron',
    'diru, diru, ĉu vi enamiĝis?',
    'enamiĝis al iu knabino',
    'ĉu vi enamiĝis al knabino?',
    'ne certas ĉu mi enamiĝis',
    'ne certas, sed sentiĝas bone',
    'mi ne certas ĉu mi jam enamiĝis',
    'sed sentiĝas tre bone',
    'ŝi eĉ kisis min',
    'kisis min sur la buŝon',
    'eĉ kisis min dum labambo',
    'mirinde kian kison',
    'kian kison ŝi donis!',
    'bonege! nun mi komprenas',
    'komprenas kial vi elradias',
    'vi elradias tiom da ĝojo',
    'fakte, io simila okazis',
    'io simila okazis al mi',
    'sed mi pensis ke ~',
    'pensis ke vi ne ŝatas ~',
    'vi ne ŝatas labambumi',
    'prave, ne okazis',
    'okazis en la dancejo',
    'ne okazis en dancejo',
    'sed en la Gufujo',
    'kaj ne estis kiso',
    'ne kiso sed tamen io ĝojiga',
    'sed tamen io tre ĝojiga',
    'do, rakontu!',
    'mi ne scias kion diri',
    'ne scias kion diri vere',
    'nenio speciala okazis',
    'almenaŭ ankoraŭ ne okazis',
    'sed mi iel sentis ~',
    'sentis ke ŝi tre ŝatas min',
    'iel sentis ke ŝi tre ŝatas min',
    'ŝi ŝatas min kaj mi ŝin',
    'ni longe babilis pri ~',
    'longe babilis pri muziko',
    'kaj poste kantis kune',
    'mi pensas ke ŝi flirtumis',
    'ŝi flirtumis kun mi',
    'estis tre agrable',
    'kiel diras via amiko de Kanado',
    '"Malfeke!", kiel diras amiko de Kanado',
    'jes, vere! mi esperas ~',
    'renkonti ŝin baldaŭ denove',
    'esperas renkonti ŝin denove',
    'mi esperas renkonti ŝin baldaŭ',
    'same mi',
    'ĉe lago proksime de ~',
    'lago proksime de kongresejo',
    'proksime de la kongresejo',
    'ho, ankaŭ vi estas ~',
    'ankaŭ vi estas ĉi tie!?',
    'jes, mi renkontos ~',
    'renkontos amikon ĉi tie baldaŭ',
    'por privata interparolo',
    'renkontos amikon por privata interparolo',
    'do, mi ŝatus peti vin ~',
    'mi ŝatus peti vin foriri',
    'nu, tio ne eblas',
    'tute ne eblas fakte',
    'kial? estas tre grava por mi!',
    'tiu ĉi renkonto estas tre grava',
    'do, bonvolu lasi min',
    'bonvolu lasi min sola',
    'kiel mi ĵus diris,',
    'mi diris, tio ne eblas',
    'amiko de mi baldaŭ aperos',
    'ĉar ankaŭ amiko baldaŭ aperos',
    'ankaŭ amiko aperos ĉi tie',
    'damne, tipe ke ĝuste nun',
    'fakte temas pri la knabino',
    'la knabino, pri kiu mi rakontis',
    'ŝia nomo estas Jesi cetere',
    'gekaraj! bonege ke vi povis veni',
    'mi tiom ĝojas vidi vin',
    'mi ĝojas vidi vin denove',
    'sed, vi aspektas ~',
    'vi aspektas ŝokitaj kaj konfuzitaj',
    'ŝokita kaj iel konfuzita',
    'evidente',
    'do, mi supozas ke ~',
    'vi jam ekkomprenis',
    'ekkomprenis kiel statas, ĉu?',
    'supozas ke vi jam komprenis',
    'jam ekkomprenis kiel statas',
    'mi nenion komprenas!',
    'mi pensas ke mi ne volas ~',
    'ne volas kompreni',
    'mi ne volas kompreni',
    'sed ne estas komplike!',
    'lasu al mi klarigi',
    'kiam Ina rakontis al mi',
    'rakontis al mi pri sia amiko',
    'amiko kiu lernis Esperanton',
    'lernis Esperanton tre rapide',
    'amiko kiu nomiĝas Kabe',
    'mi kaptis ke ~',
    'mi kaptis ke vi du jam konas',
    'vi du jam konas unu la alian',
    'jes, sed. sed kio?',
    'havis la impreson ke ~',
    'ni ambaŭ havis la impreson',
    'vi flirtumis kun ni, kaj',
    'la impreson ke vi flirtumis kun ni',
    'tute prave!',
    'pro tio mi volis paroli',
    'mi volis paroli kun vi',
    'paroli kun vi ambaŭ nun',
    'aŭskultu mi petas',
    'mi ofte tre ŝatas ~',
    'ŝatas plurajn personojn samtempe',
    'mi ŝatas plurajn personojn',
    'ne gravas ĉu estas ~',
    'ĉu estas viro aŭ virino',
    'kaj dum IJK okazis ~',
    'okazis ke mi enamiĝis',
    'mi enamiĝis al vi ambaŭ!',
    'kaj ni ambaŭ al vi',
    'ŝajne ni al vi',
    'momenton, mi estas laca',
    'tiom laca ke mi apenaŭ povas ~',
    'mi apenaŭ povas pensi',
    'ĉu mi ĝuste komprenis ke ~',
    'Jes! vidu',
    'kun ĝojplena vizaĝo',
    'desegnis grandan koron',
    'desegnis grandan koron en la sablo',
    'en la sablo kaj skribis en ĝi',
    'skribis en ĝi "I + J + K"',
    'post sekunda pripensado diris',
    'post pripensado diris "Jen nia IJK"',
    'kaj ili ekridis!',
    'ili ĉiuj ekridis!',
    'post sekunda pripensado kaj ili ridis',
    'Kabe diris "Jen nia IJK"',
    'ĉu vi sendis la aliĝilon?',
    'submetis aliĝilon al loka asocio',
    'mendis grupe pere de la asocio',
    'submetis pere de retpoŝto',
    'ricevis konfirmilon de aliĝo',
    'ne trovis kien submeti aliĝilon',
    'ĉu estas reta aliĝilo?',
    'ĉu vi submetis paperan mendilon?',
    'ĉu oni devas pagi per eŭro?',
    'ĉu eblas pagi surloke?',
    'pagis sed ne ricevis kvitancon',
    'povas pagi grupe pere de loka societo',
    'ĉu oni repagas se ne ĉeestus?',
    'ne mendis specialan programon',
    'kiel oni povas mendi aldone?',
    'kiel oni povas pagi por aldona mendo?',
    'ĉu ni povas vidi liston de aliĝintoj?',
    'mia nomo ne troviĝas en la listo de aliĝintoj',
    'ĉu vi bonvolus kontroli la liston?',
    'post la limdato de mendado',
    'ĉu oni povas aliĝi plu?',
    'rezervi hotelon kune',
    'oni rezervas hotelon, ĉu vi volas akompani?',
    'se estus libera ĉambro, mi volas tion rezervi',
    'ĉu eblas rezervi hotelon surloke?',
    'ĉu ni aĉetu aviadilan bileton kune?',
    'bileto de kiu dato',
    'ĉu ni akompanu al la flug-haveno?',
    'ĉu estas iu gvidanto ĉe la flug-haveno?',
    'ĉu oni devas iri al la kongresejo per si mem?',
    'giĉeto de la kongresejo',
    'mi pagis tamen mia nomŝildo ne troviĝas',
    'volas registriĝi surloke',
    'pagis grupe, tamen kial ne estas markita?',
    'kongresa sako kun kongresa libro kaj aliaj informiloj',
    'rektora halo, ekspozicio',
    'malfermo kaj fermo',
    'ekzamenejo de KER (Kadro de Eŭropa Referenco)',
    'kongresa komitato',
    'komitato de asocio',
    'kongresa bankedo',
    'Interkona Vespero',
    'solena inaŭguro',
    'Zamenhofa halo',
    'LKK (loka kongresa komitato)',
    'IKU (Internacia Kongresa Universitato)',
    'KER-ekzameno je kvar niveloj (Kadro de Eŭropa Referenco)',
    'internacia arta vespero',
    'solena fermo',
    'libroservo kun esperanto-libroj',
    'AIS (Akademio Internacia de la Sciencoj)',
    'SAT (Sennacieca Asocio Tutmonda)',
    'prelegoj enuaj',
    'deĵorantoj por diversaj fakoj',
    'deĵorantoj skipe kunlaboras',
    'vojaĝa agento',
    'aviadila bileto',
    'nuligis la hotelon kaj aviadilan bileton',
    'kongresa kuriero',
    'unua bulteno, dua bulteno',
    'kongresa temo',
    'paroligaj kursoj',
    'provizoraj programoj',
    'ĝeneralaj kondiĉoj de mendado',
    'antaŭ-kongresaj ekskursoj',
    'post-kongresa ekskurso',
    'tut-tagaj ekskursoj',
    'duon-tagaj ekskursoj',
    'tabelo de dum-kongresaj ekskursoj',
    'aranĝoj ĉirkaŭ la UK (Universala Kongreso)',
    'kontaktoj kun amas-komunikiloj',
    'vic-prezidanto prezidis la programon',
    'kun landaj aŭtoritatoj',
    'sekretario, kasisto',
    'artaj aranĝoj',
    'Infana Kongreseto',
    'sociaj retejoj',
    'reĝisoro de la kongresa temo',
    'rektoro de IKU (Internacia Kongresa Universitato)',
    'san-asekuro kaj asekuro de vojaĝo',
    'dokumentoj kaj vizoj',
    'valida identigilo',
    'pasporto valida',
    'reguloj pri viz-donado',
    'akiro de vizo',
    'CO (centra oficejo) de UEA (Universala Esperanto Asocio)',
    'elŝuti la oficialan konfirmilon (invitilon)',
    'uzante la mendilon',
    'al la viz-dona instanco',
    'la oficiala kongres-daŭro',
    'mendis loĝadon pere de UEA (Universala Esperanto Asocio)',
    'informi pri eventualaj ŝanĝoj',
    'akiri vojaĝan asekuron',
    'krom la nuligon de la vojaĝo',
    'asekuro kovras san-traktadon',
    'kaze de la akcidentoj',
    'deponi la valizojn',
    'internacia flug-haveno',
    'iri buse aŭ taksie aŭ aŭtomobile',
    'la veturo daŭras ĉirkaŭ 40 minutojn',
    'utiligi metroon ĝis la bus-haltejo',
    'ankaŭ alteriĝis en alia flug-haveno',
    'por kongres-rilataj aferoj',
    'oficiala mon-unuo estas eŭro',
    'vendejo akceptas kredit-kartojn',
    'je ordinara kurzo',
    'agnoskita kiel oficiala lingvo',
    'kran-akvo estas trinkebla',
    'aĉeti mineralan akvon kun-gasan',
    'trinkmono aprezata sed ne deviga',
    'urba transportilo',
    'aĉetebla ĉe aŭtomata giĉeto de haltejo',
    'informa budo en kongresejo',
    'programo de la Kleriga Lundo',
    'movada foiro',
    'Ekumena Diservo',
    'Kongresa Balo',
    'Estraro Respondas',
    'faka kunsido',
    'kongresa aŭkcio',
    'komitato de UEA (Universala Esperanto Asocio)',
    'registrita kongresano',
    'aliĝilo kun kongresa numero',
    'liveri ĉiujn servojn laŭ dua bulteno',
    'hazarda kunloĝigo de nekonatoj',
    'disponigas nur al anticipaj konsentitoj',
    'krom se aliloke indikite',
    'ekskursojn akompanos gvidanto',
];