var lang_msgs = {
  "msg_id": {
    "type_e-mail": "type_e-mail",
    "type_e-mail_again": "type_e-mail_again",
    "type_e-mail_twice": "type_e-mail_twice",
    "listen_and_fill": "listen_and_fill",
    "match_correct": "match_correct",
    "choose_the_level": "choose_the_level",
    "select_what_you_hear": "select_what_you_hear",
    "select_correct_one": "select_correct_one",
    "learned_these_word": "learned_these_word",
    "span_learn_by_examples": "span_learn_by_examples",
    "Btn_Start_learning": "Btn_Start_learning",
    "btn_continue": "btn_continue",
    "btn_listen_continue": "btn_listen_continue",
    "btn_listen": "btn_listen",
    "btn_hard": "btn_hard",
    "btn_easy": "btn_easy",
    "btn_too_easy": "btn_too_easy",
    "btn_login": "btn_login",
    "Btn_StartA": "Btn_StartA",
    "Btn_logout": "Btn_logout",
    "wordsA": "wordsA",
    "words_to_reviewA": "words_to_reviewA",
    "familiarA": "familiarA",
    "masteredA": "masteredA",
    "progressA": "progressA",
    "pointsA": "pointsA",
    "progress_msg": "progress_msg",
    "wrong_progress_input": "wrong_progress_input",
  },
  "ko-kr": {
    "type_e-mail": "이메일 주소를 입력해 주세요.",
    "type_e-mail_again": "이메일 주소를 한 번 더 입력해 주세요.",
    "type_e-mail_twice": "이메일을 두 번 입력해주세요.",
    "listen_and_fill": "듣고 빈칸을 채우세요.",
    "match_correct": "짝을 맞추세요.",
    "choose_the_level": "이것이 쉽나요? 어렵나요?",
    "select_what_you_hear": "들어보고 선택하세요.",
    "select_correct_one": "맞는 것을 선택하세요.",
    "learned_these_word": "방금 학습하신 목록입니다.",
    "span_learn_by_examples": "예제를 통한 에스페란토 학습",
    "Btn_Start_learning": "학습 시작하기",
    "btn_continue": "다음",
    "btn_listen_continue": "듣고 다음으로",
    "btn_listen": "들어보기",
    "btn_hard": "어려워요",
    "btn_easy": "쉬워요",
    "btn_too_easy": "너무쉬워요",
    "btn_login": "로그인",
    "Btn_StartA": "학습시작",
    "Btn_logout": "로그아웃",
    "wordsA": "전체 항목 수",
    "words_to_reviewA": "복습 필요 항목",
    "familiarA": "익숙해진 항목",
    "masteredA": "마스터한 항목",
    "progressA": "진도율",
    "pointsA": "누적 점수",
    "progress_msg": "지금 진도율이 $PROGRESS %입니다. 몇 퍼센트 위치로 점프하시겠습니까? 만약 절반을 원하시면 50을 입력해주세요.",
    "wrong_progress_input": "입력이 잘못되었습니다! 0-100사이의 퍼센트 값을 정수로 입력하세요.",
  },
  "zh-tw": {
    "type_e-mail": "請輸入電子郵件地址。",
    "type_e-mail_again": "請再輸入一次電子郵件地址。",
    "type_e-mail_twice": "請輸入兩次電子郵件",
    "listen_and_fill": "聽完後填滿空格。",
    "match_correct": "請配對。",
    "choose_the_level": "這容易嗎? 很難嗎？",
    "select_what_you_hear": "請聽後選擇。",
    "select_correct_one": "請選擇正確的。",
    "learned_these_word": "這是您剛學習的清單。",
    "span_learn_by_examples": "透過例題學習世界語",
    "Btn_Start_learning": "開始學習",
    "btn_continue": "下一個",
    "btn_listen_continue": "聽完之後",
    "btn_listen": "聽",
    "btn_hard": "好難",
    "btn_easy": "簡單",
    "btn_too_easy": "很簡單",
    "btn_login": "登入",
    "Btn_StartA": "學習開始",
    "Btn_logout": "註銷",
    "wordsA": "總項目數",
    "words_to_reviewA": "複習項目",
    "familiarA": "熟悉的項目",
    "masteredA": "掌握的項目",
    "progressA": "進度率",
    "pointsA": "累計分數",
    "progress_msg": "當前進度為 $PROGRESS %。 你想跳到百分之幾的位置？ 如果您想要一半，請輸入 50。",
    "wrong_progress_input": "輸入無效！ 輸入 0 到 100 之間的整數百分比值。",
  },
  "zh-cn": {
    "type_e-mail": "请输入电子邮件地址。",
    "type_e-mail_again": "请再输入一次电子邮件地址。",
    "type_e-mail_twice": "请输入两次电子邮件",
    "listen_and_fill": "听完后填满空格。",
    "match_correct": "请配对。",
    "choose_the_level": "这容易吗? 很难吗？",
    "select_what_you_hear": "请听后选择。",
    "select_correct_one": "请选择正确的。",
    "learned_these_word": "这是您刚刚学习的列表。",
    "span_learn_by_examples": "通过例题学习世界语",
    "Btn_Start_learning": "开始学习",
    "btn_continue": "下一个",
    "btn_listen_continue": "听完之后",
    "btn_listen": "听",
    "btn_hard": "好难",
    "btn_easy": "简单",
    "btn_too_easy": "很简单",
    "btn_login": "登录",
    "Btn_StartA": "学习开始",
    "Btn_logout": "注销",
    "wordsA": "总项目数",
    "words_to_reviewA": "复习项目",
    "familiarA": "熟悉的项目",
    "masteredA": "掌握的项目",
    "progressA": "进度率",
    "pointsA": "累计分数",
    "progress_msg": "当前进度为 $PROGRESS %。 你想跳到百分之几的位置？ 如果您想要一半，请输入 50。",
    "wrong_progress_input": "输入无效！ 输入 0 到 100 之间的整数百分比值。",
  },
  "en-us": {
    "type_e-mail": "Type in your e-mail adress.",
    "type_e-mail_again": "Type in your e-mail adress again.",
    "type_e-mail_twice": "Enter your e-mail twice.",
    "listen_and_fill": "Listen and fill blanks.",
    "match_correct": "Match correct pairs.",
    "choose_the_level": "Choose the level how you feel about this.",
    "select_what_you_hear": "Select what you hear.",
    "select_correct_one": "Select correct one.",
    "learned_these_word": "You have just learned these words.",
    "span_learn_by_examples": "Learn Esperanto by Examples",
    "Btn_Start_learning": "Start Learning",
    "btn_continue": "Continue",
    "btn_listen_continue": "Listen and Continue",
    "btn_listen": "Listen",
    "btn_hard": "Hard for me",
    "btn_easy": "Easy to me",
    "btn_too_easy": "Too easy",
    "btn_login": "Login",
    "Btn_StartA": "Start Learning",
    "Btn_logout": "Logout",
    "wordsA": "Words",
    "words_to_reviewA": "Words to review",
    "familiarA": "Familiar",
    "masteredA": "Mastered",
    "progressA": "Progress",
    "pointsA": "Points",
    "progress_msg": "Current progress is $PROGRESS %. What percent position do you want to jump to? If you want half, enter 50.",
    "wrong_progress_input": "Invalid input! Enter a percentage value between 0 and 100 as an integer.",
  },
  "ja-jp": {
    "type_e-mail": "メールアドレスを入力してください。",
    "type_e-mail_again": "メールアドレスをもう一度入力してください。",
    "type_e-mail_twice": "Eメールを二度入力してください。",
    "listen_and_fill": "聞いて空欄を埋めてください。",
    "match_correct": "ペアを組んでください。",
    "choose_the_level": "これが簡単ですか？ 難しいですか？",
    "select_what_you_hear": "聞いてみて選択してください。",
    "select_correct_one": "正しいものを選択してください。",
    "learned_these_word": "先ほど学習したリストです。",
    "span_learn_by_examples": "例題によるエスペラント学習",
    "Btn_Start_learning": "学習を始める",
    "btn_continue": "次",
    "btn_listen_continue": "聞いてから次へ",
    "btn_listen": "聞いてみる",
    "btn_hard": "難しいです",
    "btn_easy": "簡単です",
    "btn_too_easy": "とても簡単です",
    "btn_login": "ログイン",
    "Btn_StartA": "学習開始",
    "Btn_logout": "ログアウト",
    "wordsA": "全項目数",
    "words_to_reviewA": "復習必要項目",
    "familiarA": "慣れた項目",
    "masteredA": "マスターな項目",
    "progressA": "進度率",
    "pointsA": "累積点数",
    "progress_msg": "今進歩率は$PROGRESS％です。 何パーセントの位置にジャンプしますか？ 半分が必要な場合は50を入力してください。",
    "wrong_progress_input": "入力が間違っています！ 0〜100の間のパーセント値を整数で入力してください。",
  },
  "vi-vn": {
    "type_e-mail": "Nhập địa chỉ email của bạn.",
    "type_e-mail_again": "Nhập lại địa chỉ email của bạn.",
    "type_e-mail_twice": "Nhập e-mail của bạn hai lần.",
    "listen_and_fill": "Nghe và điền vào chỗ trống.",
    "match_correct": "Ghép các cặp đúng.",
    "choose_the_level": "Hãy chọn mức độ bạn cảm nhận về điều này.",
    "select_what_you_hear": "Chọn những gì bạn nghe thấy",
    "select_correct_one": "Chọn đúng.",
    "learned_these_word": "Bạn vừa học được những từ này.",
    "span_learn_by_examples": "Học Esperanto qua ví dụ",
    "Btn_Start_learning": "Bắt đầu học",
    "btn_continue": "Tiếp tục",
    "btn_listen_continue": "Nghe và tiếp tục",
    "btn_listen": "Nghe này",
    "btn_hard": "Khó",
    "btn_easy": "Dễ",
    "btn_too_easy": "Quá dễ",
    "btn_login": "Đăng nhập",
    "Btn_StartA": "Bắt đầu học",
    "Btn_logout": "Đăng xuất",
    "wordsA": "Từ",
    "words_to_reviewA": "Những từ cần ôn lại",
    "familiarA": "Quen thuộc",
    "masteredA": "Thành thạo",
    "progressA": "Tiến trình",
    "pointsA": "Điểm",
    "progress_msg": "Tiến độ hiện tại là $PROGRESS %. Bạn muốn nhảy tới vị trí phần trăm nào? Nếu bạn muốn một nửa, hãy nhập 50.",
    "wrong_progress_input": "Đâu vao không hợp lệ! Nhập giá trị phần trăm từ 0 đến 100 dưới dạng số nguyên.",
  },
  "fr": {
    "type_e-mail": "Saisissez votre adresse e-mail.",
    "type_e-mail_again": "Saisissez à nouveau votre adresse e-mail.",
    "type_e-mail_twice": "Entrez votre e-mail deux fois.",
    "listen_and_fill": "Écoutez et remplissez les blancs.",
    "match_correct": "Faites correspondre les bonnes paires.",
    "choose_the_level": "Choisissez le niveau de ce que vous ressentez à ce sujet.",
    "select_what_you_hear": "Sélectionnez ce que vous entendez.",
    "select_correct_one": "Sélectionnez le bon.",
    "learned_these_word": "Vous venez d'apprendre ces mots.",
    "span_learn_by_examples": "Apprendre l'espéranto par des exemples",
    "Btn_Start_learning": "Commencer à apprendre",
    "btn_continue": "Continuer",
    "btn_listen_continue": "Écoutez et continuez",
    "btn_listen": "Écouter",
    "btn_hard": "Difficile pour moi",
    "btn_easy": "Facile pour moi",
    "btn_too_easy": "Trop facile",
    "btn_login": "Se connecter",
    "Btn_StartA": "Commencer à apprendre",
    "Btn_logout": "Se déconnecter",
    "wordsA": "Mots",
    "words_to_reviewA": "Mots à revoir",
    "familiarA": "Familier",
    "masteredA": "Maîtrisé",
    "progressA": "Progrès",
    "pointsA": "Points",
    "progress_msg": "La progression actuelle est de $PROGRESS %. À quel pourcentage de position souhaitez-vous accéder ? Si vous en voulez la moitié, entrez 50.",
    "wrong_progress_input": "Entrée invalide! Entrez une valeur de pourcentage comprise entre 0 et 100 sous forme d'entier.",
  },
  "mn": {
    "type_e-mail": "Имэйл хаягаа оруулна уу.",
    "type_e-mail_again": "Имэйл хаягаа дахин бичнэ үү.",
    "type_e-mail_twice": "Имэйлээ хоёр удаа оруулна уу.",
    "listen_and_fill": "Сонсож, хоосон зайг бөглөнө үү.",
    "match_correct": "Зөв хосуудыг тааруулна уу.",
    "choose_the_level": "Энэ талаар ямар түвшинд байгаагаа сонго.",
    "select_what_you_hear": "Сонссон зүйлээ сонго.",
    "select_correct_one": "Зөвийг сонго.",
    "learned_these_word": "Та эдгээр үгсийг саяхан сурсан.",
    "span_learn_by_examples": "Эсперанто хэлийг жишээгээр сур",
    "Btn_Start_learning": "Сураж эхэл",
    "btn_continue": "Үргэлжлүүлэх",
    "btn_listen_continue": "Сонсож, үргэлжлүүлээрэй",
    "btn_listen": "Сонсооч",
    "btn_hard": "Надад хэцүү",
    "btn_easy": "Надад амархан",
    "btn_too_easy": "Хэт амархан",
    "btn_login": "Нэвтрэх",
    "Btn_StartA": "Сураж эхэл",
    "Btn_logout": "Гарах",
    "wordsA": "Үг",
    "words_to_reviewA": "Шалгах үгс",
    "familiarA": "Танил",
    "masteredA": "Мэргэшсэн",
    "progressA": "Ахиц дэвшил",
    "pointsA": "Оноо",
    "progress_msg": "Одоогийн явц нь $PROGRESS % байна. Та хэдэн хувийн байрлал руу үсрэхийг хүсч байна вэ? Хэрэв та хагасыг хүсвэл 50-г оруулна уу.",
    "wrong_progress_input": "Буруу оролт! 0-ээс 100 хүртэлх хувийн утгыг бүхэл тоогоор оруулна уу.",
  },
  "th": {
    "type_e-mail": "พิมพ์ที่อยู่อีเมลของคุณ",
    "type_e-mail_again": "พิมพ์ที่อยู่อีเมลของคุณอีกครั้ง",
    "type_e-mail_twice": "กรอกอีเมล์ของคุณสองครั้ง",
    "listen_and_fill": "ฟังและเติมคำในช่องว่าง",
    "match_correct": "จับคู่คู่ให้ถูกต้อง",
    "choose_the_level": "เลือกระดับความรู้สึกของคุณเกี่ยวกับเรื่องนี้",
    "select_what_you_hear": "เลือกสิ่งที่คุณได้ยิน",
    "select_correct_one": "เลือกอันที่ถูกต้อง",
    "learned_these_word": "คุณเพิ่งเรียนรู้คำศัพท์เหล่านี้",
    "span_learn_by_examples": "เรียนรู้ภาษาเอสเปรันโตตามตัวอย่าง",
    "Btn_Start_learning": "เริ่มการเรียนรู้",
    "btn_continue": "ดำเนินการต่อ",
    "btn_listen_continue": "ฟังและดำเนินการต่อ",
    "btn_listen": "ฟัง",
    "btn_hard": "ยากสำหรับฉัน",
    "btn_easy": "ง่ายสำหรับฉัน",
    "btn_too_easy": "ง่ายเกินไป",
    "btn_login": "เข้าสู่ระบบ",
    "Btn_StartA": "เริ่มการเรียนรู้",
    "Btn_logout": "ออกจากระบบ",
    "wordsA": "คำ",
    "words_to_reviewA": "คำศัพท์ที่ต้องทบทวน",
    "familiarA": "คุ้นเคย",
    "masteredA": "เชี่ยวชาญ",
    "progressA": "ความคืบหน้า",
    "pointsA": "คะแนน",
    "progress_msg": "ความคืบหน้าปัจจุบันคือ $PROGRESS % คุณต้องการข้ามไปยังตำแหน่งกี่เปอร์เซ็นต์? หากต้องการครึ่งหนึ่งให้ป้อน 50",
    "wrong_progress_input": "ข้อมูลไม่ถูกต้อง! ป้อนค่าเปอร์เซ็นต์ระหว่าง 0 ถึง 100 เป็นจำนวนเต็ม",
  },
  "ms": {
    "type_e-mail": "Taipkan alamat e-mel anda.",
    "type_e-mail_again": "Taipkan alamat e-mel anda sekali lagi.",
    "type_e-mail_twice": "Masukkan e-mel anda dua kali.",
    "listen_and_fill": "Dengar dan isi tempat kosong.",
    "match_correct": "Padankan pasangan yang betul.",
    "choose_the_level": "Pilih tahap perasaan anda tentang perkara ini.",
    "select_what_you_hear": "Pilih apa yang anda dengar.",
    "select_correct_one": "Pilih yang betul.",
    "learned_these_word": "Anda baru sahaja mempelajari perkataan ini.",
    "span_learn_by_examples": "Belajar Esperanto dengan Contoh",
    "Btn_Start_learning": "Mula Belajar",
    "btn_continue": "teruskan",
    "btn_listen_continue": "Dengar dan Teruskan",
    "btn_listen": "Dengar",
    "btn_hard": "Sukar untuk saya",
    "btn_easy": "Mudah bagi saya",
    "btn_too_easy": "Terlalu mudah",
    "btn_login": "Log masuk",
    "Btn_StartA": "Mula Belajar",
    "Btn_logout": "Log keluar",
    "wordsA": "Kata-kata",
    "words_to_reviewA": "Kata-kata untuk disemak",
    "familiarA": "Biasa",
    "masteredA": "Menguasai",
    "progressA": "Kemajuan",
    "pointsA": "mata",
    "progress_msg": "Kemajuan semasa ialah $PROGRESS %. Berapa peratus kedudukan yang anda mahu lompat? Kalau nak separuh, masukkan 50.",
    "wrong_progress_input": "Input tidak sah! Masukkan nilai peratusan antara 0 dan 100 sebagai integer.",
  },
  "id": {
    "type_e-mail": "Ketikkan alamat email Anda.",
    "type_e-mail_again": "Ketik lagi alamat email Anda.",
    "type_e-mail_twice": "Masukkan email Anda dua kali.",
    "listen_and_fill": "Dengarkan dan isi bagian yang kosong.",
    "match_correct": "Cocokkan pasangan yang benar.",
    "choose_the_level": "Pilih tingkat perasaan Anda tentang hal ini.",
    "select_what_you_hear": "Pilih apa yang Anda dengar.",
    "select_correct_one": "Pilih yang benar.",
    "learned_these_word": "Anda baru saja mempelajari kata-kata ini.",
    "span_learn_by_examples": "Pelajari Esperanto dengan Contoh",
    "Btn_Start_learning": "Mulai Belajar",
    "btn_continue": "Melanjutkan",
    "btn_listen_continue": "Dengarkan dan Lanjutkan",
    "btn_listen": "Mendengarkan",
    "btn_hard": "Sulit untukku",
    "btn_easy": "Mudah bagi saya",
    "btn_too_easy": "Terlalu mudah",
    "btn_login": "Gabung",
    "Btn_StartA": "Mulai Belajar",
    "Btn_logout": "Keluar",
    "wordsA": "Kata-kata",
    "words_to_reviewA": "Kata-kata untuk ditinjau",
    "familiarA": "Akrab",
    "masteredA": "Dikuasai",
    "progressA": "Kemajuan",
    "pointsA": "Poin",
    "progress_msg": "Kemajuan saat ini adalah $PROGRESS %. Berapa persen posisi yang ingin Anda lompati? Jika ingin setengahnya, masukkan 50.",
    "wrong_progress_input": "Masukan tidak valid! Masukkan nilai persentase antara 0 dan 100 sebagai bilangan bulat.",
  },
  "hi": {
    "type_e-mail": "अपना ई-मेल पता टाइप करें.",
    "type_e-mail_again": "अपना ई-मेल पता दोबारा टाइप करें।",
    "type_e-mail_twice": "अपना ई-मेल दो बार दर्ज करें.",
    "listen_and_fill": "सुनें और रिक्त स्थान भरें.",
    "match_correct": "सही जोड़े मिलाएँ.",
    "choose_the_level": "आप इसके बारे में कैसा महसूस करते हैं, इसका स्तर चुनें।",
    "select_what_you_hear": "आप जो सुनते हैं उसे चुनें.",
    "select_correct_one": "सही का चयन करें.",
    "learned_these_word": "आपने अभी-अभी ये शब्द सीखे हैं।",
    "span_learn_by_examples": "उदाहरणों द्वारा एस्पेरान्तो सीखें",
    "Btn_Start_learning": "सीखना शुरू करें",
    "btn_continue": "जारी रखना",
    "btn_listen_continue": "सुनें और जारी रखें",
    "btn_listen": "सुनना",
    "btn_hard": "मेरे लिए मुश्किल",
    "btn_easy": "मेरे लिए आसान है",
    "btn_too_easy": "बहुत आसान",
    "btn_login": "लॉग इन करें",
    "Btn_StartA": "सीखना शुरू करें",
    "Btn_logout": "लॉग आउट",
    "wordsA": "शब्द",
    "words_to_reviewA": "समीक्षा के लिए शब्द",
    "familiarA": "परिचित",
    "masteredA": "महारत हासिल",
    "progressA": "प्रगति",
    "pointsA": "अंक",
    "progress_msg": "वर्तमान प्रगति $PROGRESS% है। आप किस प्रतिशत स्थान पर पहुंचना चाहते हैं? यदि आप आधा चाहते हैं, तो 50 दर्ज करें।",
    "wrong_progress_input": "अमान्य निवेश! पूर्णांक के रूप में 0 और 100 के बीच प्रतिशत मान दर्ज करें।",
  },
  "fa": {
    "type_e-mail": "آدرس ایمیل خود را تایپ کنید",
    "type_e-mail_again": "آدرس ایمیل خود را دوباره وارد کنید.",
    "type_e-mail_twice": "ایمیل خود را دو بار وارد کنید.",
    "listen_and_fill": "گوش کنید و جاهای خالی را پر کنید.",
    "match_correct": "جفت های صحیح را مطابقت دهید",
    "choose_the_level": "سطح احساسی که در این مورد دارید را انتخاب کنید.",
    "select_what_you_hear": "آنچه می شنوید را انتخاب کنید.",
    "select_correct_one": "صحیح را انتخاب کنید",
    "learned_these_word": "شما تازه این کلمات را یاد گرفتید.",
    "span_learn_by_examples": "اسپرانتو را با مثال بیاموزید",
    "Btn_Start_learning": "شروع به یادگیری",
    "btn_continue": "ادامه هید",
    "btn_listen_continue": "گوش کن و ادامه بده",
    "btn_listen": "گوش بده",
    "btn_hard": "برای من سخت است",
    "btn_easy": "برای من آسان است",
    "btn_too_easy": "بیش از حد آسان",
    "btn_login": "وارد شدن",
    "Btn_StartA": "شروع به یادگیری",
    "Btn_logout": "خروج",
    "wordsA": "کلمات",
    "words_to_reviewA": "کلمات برای بررسی",
    "familiarA": "آشنا",
    "masteredA": "مسلط شد",
    "progressA": "پیش رفتن",
    "pointsA": "نکته ها",
    "progress_msg": "پیشرفت فعلی $PROGRESS ٪ است. به چند درصد می خواهید بپرید؟ اگر نصف می خواهید 50 وارد کنید.",
    "wrong_progress_input": "ورودی نامعتبر! مقدار درصدی بین 0 تا 100 را به عنوان یک عدد صحیح وارد کنید.",
  },
  "ne": {
    "type_e-mail": "आफ्नो इमेल ठेगाना टाइप गर्नुहोस्।",
    "type_e-mail_again": "आफ्नो इमेल ठेगाना फेरि टाइप गर्नुहोस्।",
    "type_e-mail_twice": "आफ्नो इमेल दुई पटक प्रविष्ट गर्नुहोस्।",
    "listen_and_fill": "सुन्नुहोस् र खाली ठाउँहरू भर्नुहोस्।",
    "match_correct": "सही जोडी मिलाउनुहोस्।",
    "choose_the_level": "तपाईं यस बारे कस्तो महसुस गर्नुहुन्छ स्तर छान्नुहोस्।",
    "select_what_you_hear": "तपाईंले सुन्नु भएको कुरा चयन गर्नुहोस्।",
    "select_correct_one": "सही एक छान्नुहोस्।",
    "learned_these_word": "तपाईंले भर्खर यी शब्दहरू सिक्नुभयो।",
    "span_learn_by_examples": "उदाहरणहरूद्वारा एस्पेरान्तो सिक्नुहोस्",
    "Btn_Start_learning": "सिक्न सुरु गर्नुहोस्",
    "btn_continue": "जारी राख्नुहोस्",
    "btn_listen_continue": "सुन्नुहोस् र जारी राख्नुहोस्",
    "btn_listen": "सुन्नुहोस्",
    "btn_hard": "मेरो लागि गाह्रो",
    "btn_easy": "मलाई सजिलो",
    "btn_too_easy": "एकदम सजिलो",
    "btn_login": "लग - इन",
    "Btn_StartA": "सिक्न सुरु गर्नुहोस्",
    "Btn_logout": "बाहिर निस्कनु",
    "wordsA": "शब्दहरू",
    "words_to_reviewA": "समीक्षा गर्न शब्दहरू",
    "familiarA": "परिचित",
    "masteredA": "निपुण",
    "progressA": "प्रगति",
    "pointsA": "अंक",
    "progress_msg": "हालको प्रगति $PROGRESS % हो। तपाई कुन प्रतिशत स्थानमा उफ्रन चाहनुहुन्छ? यदि तपाईं आधा चाहनुहुन्छ भने, 50 प्रविष्ट गर्नुहोस्।",
    "wrong_progress_input": "अवैध इनपुट! पूर्णांकको रूपमा ० र १०० बीचको प्रतिशत मान प्रविष्ट गर्नुहोस्।",
  },
  "ur": {
    "type_e-mail": "اپنا ای میل ایڈریس ٹائپ کریں۔",
    "type_e-mail_again": "اپنا ای میل ایڈریس دوبارہ ٹائپ کریں۔",
    "type_e-mail_twice": "اپنا ای میل دو بار درج کریں۔",
    "listen_and_fill": "سنیں اور خالی جگہ پر کریں۔",
    "match_correct": "صحیح جوڑوں کو جوڑیں۔",
    "choose_the_level": "اس سطح کا انتخاب کریں کہ آپ اس کے بارے میں کیسا محسوس کرتے ہیں۔",
    "select_what_you_hear": "آپ جو سنتے ہیں اسے منتخب کریں۔",
    "select_correct_one": "صحیح ایک کو منتخب کریں۔",
    "learned_these_word": "آپ نے یہ الفاظ ابھی سیکھے ہیں۔",
    "span_learn_by_examples": "مثالوں سے ایسپرانٹو سیکھیں۔",
    "Btn_Start_learning": "سیکھنا شروع کریں۔",
    "btn_continue": "جاری رہے",
    "btn_listen_continue": "سنیں اور جاری رکھیں",
    "btn_listen": "سنو",
    "btn_hard": "میرے لیے مشکل",
    "btn_easy": "میرے لیے آسان",
    "btn_too_easy": "بہت آسان",
    "btn_login": "لاگ ان کریں",
    "Btn_StartA": "سیکھنا شروع کریں۔",
    "Btn_logout": "لاگ آوٹ",
    "wordsA": "الفاظ",
    "words_to_reviewA": "جائزہ لینے کے لیے الفاظ",
    "familiarA": "مانوس",
    "masteredA": "مہارت حاصل کی۔",
    "progressA": "پیش رفت",
    "pointsA": "پوائنٹس",
    "progress_msg": "موجودہ پیش رفت $PROGRESS % ہے۔ آپ کس فیصد پوزیشن پر جانا چاہتے ہیں؟ اگر آپ آدھا چاہتے ہیں تو 50 درج کریں۔",
    "wrong_progress_input": "غلط ان پٹ! بطور عدد 0 اور 100 کے درمیان فیصد کی قدر درج کریں۔",
  },
  "tr": {
    "type_e-mail": "E-posta adresinizi yazın.",
    "type_e-mail_again": "E-posta adresinizi tekrar yazın.",
    "type_e-mail_twice": "E-postanızı iki kez girin.",
    "listen_and_fill": "Dinleyin ve boşlukları doldurun.",
    "match_correct": "Doğru çiftleri eşleştirin.",
    "choose_the_level": "Bu konuda ne hissettiğinizi seviyeyi seçin.",
    "select_what_you_hear": "Ne duyduğunuzu seçin.",
    "select_correct_one": "Doğru olanı seçin.",
    "learned_these_word": "Bu kelimeleri yeni öğrendiniz.",
    "span_learn_by_examples": "Örneklerle Esperanto Öğrenin",
    "Btn_Start_learning": "Öğrenmeye başla",
    "btn_continue": "Devam etmek",
    "btn_listen_continue": "Dinle ve Devam Et",
    "btn_listen": "Dinlemek",
    "btn_hard": "Benim için zor",
    "btn_easy": "Benim için kolay",
    "btn_too_easy": "Çok kolay",
    "btn_login": "Giriş yapmak",
    "Btn_StartA": "Öğrenmeye başla",
    "Btn_logout": "Çıkış Yap",
    "wordsA": "Kelimeler",
    "words_to_reviewA": "İncelenecek kelimeler",
    "familiarA": "Aşina",
    "masteredA": "Ustalaşmış",
    "progressA": "İlerlemek",
    "pointsA": "Puanlar",
    "progress_msg": "Şu anki ilerleme %$PROGRESS. Yüzde kaç pozisyona atlamak istiyorsunuz? Yarısını istiyorsanız 50 girin.",
    "wrong_progress_input": "Geçersiz Giriş! Tam sayı olarak 0 ile 100 arasında bir yüzde değeri girin.",
  },
  "he": {
    "type_e-mail": "הקלד את כתובת הדואר האלקטרוני שלך.",
    "type_e-mail_again": "הקלד שוב את כתובת הדואר האלקטרוני שלך.",
    "type_e-mail_twice": "הכנס את המייל שלך פעמיים.",
    "listen_and_fill": "הקשיבו והשלימו מקומות ריקים.",
    "match_correct": "התאם זוגות נכונים.",
    "choose_the_level": "בחר את הרמה איך אתה מרגיש לגבי זה.",
    "select_what_you_hear": "בחר את מה שאתה שומע.",
    "select_correct_one": "בחר אחד נכון.",
    "learned_these_word": "זה עתה למדת את המילים הללו.",
    "span_learn_by_examples": "למד אספרנטו לפי דוגמאות",
    "Btn_Start_learning": "תתחיל ללמוד",
    "btn_continue": "לְהַמשִׁיך",
    "btn_listen_continue": "הקשב והמשך",
    "btn_listen": "להקשיב",
    "btn_hard": "קשה לי",
    "btn_easy": "קל לי",
    "btn_too_easy": "קל מדי",
    "btn_login": "התחברות",
    "Btn_StartA": "תתחיל ללמוד",
    "Btn_logout": "להתנתק",
    "wordsA": "מילים",
    "words_to_reviewA": "מילים לביקורת",
    "familiarA": "מוּכָּר",
    "masteredA": "מאסטר",
    "progressA": "התקדמות",
    "pointsA": "נקודות",
    "progress_msg": "ההתקדמות הנוכחית היא $PROGRESS %. לאיזה אחוז עמדה אתה רוצה לקפוץ? אם אתה רוצה חצי, הזן 50.",
    "wrong_progress_input": "קלט לא תקין! הזן ערך אחוז בין 0 ל-100 כמספר שלם.",
  },
  "ar": {
    "type_e-mail": "اكتب عنوان البريد الإلكتروني الخاص بك.",
    "type_e-mail_again": "اكتب عنوان البريد الإلكتروني الخاص بك مرة أخرى.",
    "type_e-mail_twice": "أدخل بريدك الإلكتروني مرتين.",
    "listen_and_fill": "استمع واملأ الفراغات.",
    "match_correct": "تطابق الأزواج الصحيحة.",
    "choose_the_level": "اختر المستوى الذي تشعر به حيال ذلك.",
    "select_what_you_hear": "حدد ما تسمعه.",
    "select_correct_one": "اختر واحدة صحيحة.",
    "learned_these_word": "لقد تعلمت للتو هذه الكلمات.",
    "span_learn_by_examples": "تعلم الاسبرانتو بالأمثلة",
    "Btn_Start_learning": "ابدا بالتعلم",
    "btn_continue": "يكمل",
    "btn_listen_continue": "الاستماع والمتابعة",
    "btn_listen": "يستمع",
    "btn_hard": "صعب علي",
    "btn_easy": "سهل بالنسبة لي",
    "btn_too_easy": "سهل جدا",
    "btn_login": "تسجيل الدخول",
    "Btn_StartA": "ابدا بالتعلم",
    "Btn_logout": "تسجيل خروج",
    "wordsA": "كلمات",
    "words_to_reviewA": "كلمات للمراجعة",
    "familiarA": "مألوف",
    "masteredA": "يتقن",
    "progressA": "تقدم",
    "pointsA": "نقاط",
    "progress_msg": "التقدم الحالي هو $PROGRESS %. ما هو موضع النسبة المئوية الذي تريد الانتقال إليه؟ إذا كنت تريد النصف، أدخل 50.",
    "wrong_progress_input": "مدخل غير صالح! أدخل قيمة النسبة المئوية بين 0 و100 كعدد صحيح.",
  },
}
