var lang_msgs = {
    "msg_id": {
        "type_e-mail": "type_e-mail",
        "type_e-mail_again": "type_e-mail_again",
        "type_e-mail_twice": "type_e-mail_twice",
        "listen_and_fill": "listen_and_fill",
        "match_correct": "match_correct",
        "choose_the_level": "choose_the_level",
        "select_what_you_hear": "select_what_you_hear",
        "select_correct_one": "select_correct_one",
        "learned_these_word": "learned_these_word",
        "span_learn_by_examples": "span_learn_by_examples",
        "Btn_Start_learning": "Btn_Start_learning",
        "btn_continue": "btn_continue",
        "btn_listen_continue": "btn_listen_continue",
        "btn_listen": "btn_listen",
        "btn_hard": "btn_hard",
        "btn_easy": "btn_easy",
        "btn_too_easy": "btn_too_easy",
        "btn_login": "btn_login",
        "Btn_StartA": "Btn_StartA",
        "Btn_logout": "Btn_logout",
        "wordsA": "wordsA",
        "words_to_reviewA": "words_to_reviewA",
        "familiarA": "familiarA",
        "masteredA": "masteredA",
        "progressA": "progressA",
        "pointsA": "pointsA",
        "progress_msg": "progress_msg",
        "wrong_progress_input": "wrong_progress_input",
    },
    "ko-kr": {
        "type_e-mail": "이메일 주소를 입력해 주세요.",
        "type_e-mail_again": "이메일 주소를 한 번 더 입력해 주세요.",
        "type_e-mail_twice": "이메일을 두 번 입력해주세요.",
        "listen_and_fill": "듣고 빈칸을 채우세요.",
        "match_correct": "짝을 맞추세요.",
        "choose_the_level": "이것이 쉽나요? 어렵나요?",
        "select_what_you_hear": "들어보고 선택하세요.",
        "select_correct_one": "맞는 것을 선택하세요.",
        "learned_these_word": "방금 학습하신 목록입니다.",
        "span_learn_by_examples": "예제를 통한 에스페란토 학습",
        "Btn_Start_learning": "학습 시작하기",
        "btn_continue": "다음",
        "btn_listen_continue": "듣고 다음으로",
        "btn_listen": "들어보기",
        "btn_hard": "어려워요",
        "btn_easy": "쉬워요",
        "btn_too_easy": "너무쉬워요",
        "btn_login": "로그인",
        "Btn_StartA": "학습시작",
        "Btn_logout": "로그아웃",
        "wordsA": "전체 항목 수",
        "words_to_reviewA": "복습 필요 항목",
        "familiarA": "익숙해진 항목",
        "masteredA": "마스터한 항목",
        "progressA": "진도율",
        "pointsA": "누적 점수",
        "progress_msg": "지금 진도율이 $PROGRESS %입니다. 몇 퍼센트 위치로 점프하시겠습니까? 만약 절반을 원하시면 50을 입력해주세요.",
        "wrong_progress_input": "입력이 잘못되었습니다! 0-100사이의 퍼센트 값을 정수로 입력하세요.",
    },
    "zh-tw": {
        "type_e-mail": "請輸入電子郵件地址。",
        "type_e-mail_again": "請再輸入一次電子郵件地址。",
        "type_e-mail_twice": "請輸入兩次電子郵件",
        "listen_and_fill": "聽完後填滿空格。",
        "match_correct": "請配對。",
        "choose_the_level": "這容易嗎? 很難嗎？",
        "select_what_you_hear": "請聽後選擇。",
        "select_correct_one": "請選擇正確的。",
        "learned_these_word": "這是您剛學習的清單。",
        "span_learn_by_examples": "透過例題學習世界語",
        "Btn_Start_learning": "開始學習",
        "btn_continue": "下一個",
        "btn_listen_continue": "聽完之後",
        "btn_listen": "聽",
        "btn_hard": "好難",
        "btn_easy": "簡單",
        "btn_too_easy": "很簡單",
        "btn_login": "登入",
        "Btn_StartA": "學習開始",
        "Btn_logout": "註銷",
        "wordsA": "總項目數",
        "words_to_reviewA": "複習項目",
        "familiarA": "熟悉的項目",
        "masteredA": "掌握的項目",
        "progressA": "進度率",
        "pointsA": "累計分數",
        "progress_msg": "當前進度為 $PROGRESS %。 你想跳到百分之幾的位置？ 如果您想要一半，請輸入 50。",
        "wrong_progress_input": "輸入無效！ 輸入 0 到 100 之間的整數百分比值。",
    },
    "zh-cn": {
        "type_e-mail": "请输入电子邮件地址。",
        "type_e-mail_again": "请再输入一次电子邮件地址。",
        "type_e-mail_twice": "请输入两次电子邮件",
        "listen_and_fill": "听完后填满空格。",
        "match_correct": "请配对。",
        "choose_the_level": "这容易吗? 很难吗？",
        "select_what_you_hear": "请听后选择。",
        "select_correct_one": "请选择正确的。",
        "learned_these_word": "这是您刚刚学习的列表。",
        "span_learn_by_examples": "通过例题学习世界语",
        "Btn_Start_learning": "开始学习",
        "btn_continue": "下一个",
        "btn_listen_continue": "听完之后",
        "btn_listen": "听",
        "btn_hard": "好难",
        "btn_easy": "简单",
        "btn_too_easy": "很简单",
        "btn_login": "登录",
        "Btn_StartA": "学习开始",
        "Btn_logout": "注销",
        "wordsA": "总项目数",
        "words_to_reviewA": "复习项目",
        "familiarA": "熟悉的项目",
        "masteredA": "掌握的项目",
        "progressA": "进度率",
        "pointsA": "累计分数",
        "progress_msg": "当前进度为 $PROGRESS %。 你想跳到百分之几的位置？ 如果您想要一半，请输入 50。",
        "wrong_progress_input": "输入无效！ 输入 0 到 100 之间的整数百分比值。",
    },
    "en-us": {
        "type_e-mail": "Type in your e-mail adress.",
        "type_e-mail_again": "Type in your e-mail adress again.",
        "type_e-mail_twice": "Enter your e-mail twice.",
        "listen_and_fill": "Listen and fill blanks.",
        "match_correct": "Match correct pairs.",
        "choose_the_level": "Choose the level how you feel about this.",
        "select_what_you_hear": "Select what you hear.",
        "select_correct_one": "Select correct one.",
        "learned_these_word": "You have just learned these words.",
        "span_learn_by_examples": "Learn Esperanto by Examples",
        "Btn_Start_learning": "Start Learning",
        "btn_continue": "Continue",
        "btn_listen_continue": "Listen and Continue",
        "btn_listen": "Listen",
        "btn_hard": "Hard for me",
        "btn_easy": "Easy to me",
        "btn_too_easy": "Too easy",
        "btn_login": "Login",
        "Btn_StartA": "Start Learning",
        "Btn_logout": "Logout",
        "wordsA": "Words",
        "words_to_reviewA": "Words to review",
        "familiarA": "Familiar",
        "masteredA": "Mastered",
        "progressA": "Progress",
        "pointsA": "Points",
        "progress_msg": "Current progress is $PROGRESS %. What percent position do you want to jump to? If you want half, enter 50.",
        "wrong_progress_input": "Invalid input! Enter a percentage value between 0 and 100 as an integer.",
    },
    "ja-jp": {
        "type_e-mail": "メールアドレスを入力してください。",
        "type_e-mail_again": "メールアドレスをもう一度入力してください。",
        "type_e-mail_twice": "Eメールを二度入力してください。",
        "listen_and_fill": "聞いて空欄を埋めてください。",
        "match_correct": "ペアを組んでください。",
        "choose_the_level": "これが簡単ですか？ 難しいですか？",
        "select_what_you_hear": "聞いてみて選択してください。",
        "select_correct_one": "正しいものを選択してください。",
        "learned_these_word": "先ほど学習したリストです。",
        "span_learn_by_examples": "例題によるエスペラント学習",
        "Btn_Start_learning": "学習を始める",
        "btn_continue": "次",
        "btn_listen_continue": "聞いてから次へ",
        "btn_listen": "聞いてみる",
        "btn_hard": "難しいです",
        "btn_easy": "簡単です",
        "btn_too_easy": "とても簡単です",
        "btn_login": "ログイン",
        "Btn_StartA": "学習開始",
        "Btn_logout": "ログアウト",
        "wordsA": "全項目数",
        "words_to_reviewA": "復習必要項目",
        "familiarA": "慣れた項目",
        "masteredA": "マスターな項目",
        "progressA": "進度率",
        "pointsA": "累積点数",
        "progress_msg": "今進歩率は$PROGRESS％です。 何パーセントの位置にジャンプしますか？ 半分が必要な場合は50を入力してください。",
        "wrong_progress_input": "入力が間違っています！ 0〜100の間のパーセント値を整数で入力してください。",
    },
    "vi-vn": {
        "type_e-mail": "Nhập địa chỉ email của bạn.",
        "type_e-mail_again": "Nhập lại địa chỉ email của bạn.",
        "type_e-mail_twice": "Nhập e-mail của bạn hai lần.",
        "listen_and_fill": "Nghe và điền vào chỗ trống.",
        "match_correct": "Ghép các cặp đúng.",
        "choose_the_level": "Hãy chọn mức độ bạn cảm nhận về điều này.",
        "select_what_you_hear": "Chọn những gì bạn nghe thấy",
        "select_correct_one": "Chọn đúng.",
        "learned_these_word": "Bạn vừa học được những từ này.",
        "span_learn_by_examples": "Học Esperanto qua ví dụ",
        "Btn_Start_learning": "Bắt đầu học",
        "btn_continue": "Tiếp tục",
        "btn_listen_continue": "Nghe và tiếp tục",
        "btn_listen": "Nghe này",
        "btn_hard": "Khó",
        "btn_easy": "Dễ",
        "btn_too_easy": "Quá dễ",
        "btn_login": "Đăng nhập",
        "Btn_StartA": "Bắt đầu học",
        "Btn_logout": "Đăng xuất",
        "wordsA": "Từ",
        "words_to_reviewA": "Những từ cần ôn lại",
        "familiarA": "Quen thuộc",
        "masteredA": "Thành thạo",
        "progressA": "Tiến trình",
        "pointsA": "Điểm",
        "progress_msg": "Tiến độ hiện tại là $PROGRESS %. Bạn muốn nhảy tới vị trí phần trăm nào? Nếu bạn muốn một nửa, hãy nhập 50.",
        "wrong_progress_input": "Đâu vao không hợp lệ! Nhập giá trị phần trăm từ 0 đến 100 dưới dạng số nguyên.",
    },
    "fr": {
        "type_e-mail": "Saisissez votre adresse e-mail.",
        "type_e-mail_again": "Saisissez à nouveau votre adresse e-mail.",
        "type_e-mail_twice": "Entrez votre e-mail deux fois.",
        "listen_and_fill": "Écoutez et remplissez les blancs.",
        "match_correct": "Faites correspondre les bonnes paires.",
        "choose_the_level": "Choisissez le niveau de ce que vous ressentez à ce sujet.",
        "select_what_you_hear": "Sélectionnez ce que vous entendez.",
        "select_correct_one": "Sélectionnez le bon.",
        "learned_these_word": "Vous venez d'apprendre ces mots.",
        "span_learn_by_examples": "Apprendre l'espéranto par des exemples",
        "Btn_Start_learning": "Commencer à apprendre",
        "btn_continue": "Continuer",
        "btn_listen_continue": "Écoutez et continuez",
        "btn_listen": "Écouter",
        "btn_hard": "Difficile pour moi",
        "btn_easy": "Facile pour moi",
        "btn_too_easy": "Trop facile",
        "btn_login": "Se connecter",
        "Btn_StartA": "Commencer à apprendre",
        "Btn_logout": "Se déconnecter",
        "wordsA": "Mots",
        "words_to_reviewA": "Mots à revoir",
        "familiarA": "Familier",
        "masteredA": "Maîtrisé",
        "progressA": "Progrès",
        "pointsA": "Points",
        "progress_msg": "La progression actuelle est de $PROGRESS %. À quel pourcentage de position souhaitez-vous accéder ? Si vous en voulez la moitié, entrez 50.",
        "wrong_progress_input": "Entrée invalide! Entrez une valeur de pourcentage comprise entre 0 et 100 sous forme d'entier.",
    },
}
